export {
  peopleSchema,
  personProfile,
  employment,
  jobAssignment,
  employmentDetail,
  jobFamily,
  jobProfile,
  profileSection,
  onboardingTemplate,
  onboardingTaskTemplate,
  onboardingCase,
  onboardingTask,
  offboardingTemplate,
  offboardingTaskTemplate,
  offboardingCase,
  offboardingTask,
  contractVersion,
} from './people.schema'
export { profileChangeRequest } from './change-requests.schema'
