export {
  peopleSchema,
  personProfile,
  employment,
  jobAssignment,
  employmentDetail,
  jobFamily,
  jobProfile,
  profileSection,
  profileChangeRequest,
  onboardingTemplate,
  onboardingTaskTemplate,
  onboardingCase,
  onboardingTask,
  offboardingTemplate,
  offboardingTaskTemplate,
  offboardingCase,
  offboardingTask,
  contractVersion,
} from './people.schema'
