"""Declarative sheet specs for the English maturity workbook.

Source of truth for docs/AI SDLC Maturity.xlsx — regenerate with
`python -m exporter.template` and commit the result.

Cell fill conventions: FFFFF2CC yellow = manual entry, FFF2F2F2 gray =
auto/formula, FFFCE4D6 orange = judgment flag.

Each SHEETS entry: "columns" are filled down "data_rows" — a column's
formula template expands `{r}` to the row number; a template of None just
paints the style. "cells" hold one-off values/styles at fixed coordinates;
a ("DATE", y, m, d) tuple value marks a datetime cell.
"""

STYLES = {
    's1': {'bold': True, 'color': 'FF1F4E79', 'font': 'Arial', 'size': 16.0},
    's2': {'border': {'left': 'thin', 'top': 'thin'}, 'fill': 'FFDDEBF7', 'font': 'Arial', 'halign': 'left', 'size': 10.0, 'valign': 'top', 'wrap': True},
    's3': {'border': {'top': 'thin'}},
    's4': {'border': {'left': 'thin'}},
    's5': {'bold': True, 'font': 'Arial', 'size': 10.0},
    's6': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'fill': 'FFFFF2CC', 'font': 'Arial', 'halign': 'center', 'size': 9.0, 'valign': 'center', 'wrap': True},
    's7': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'fill': 'FFF2F2F2', 'font': 'Arial', 'halign': 'center', 'size': 9.0, 'valign': 'center', 'wrap': True},
    's8': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'fill': 'FFFCE4D6', 'font': 'Arial', 'halign': 'center', 'size': 9.0, 'valign': 'center', 'wrap': True},
    's9': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'color': 'FF0563C1', 'fill': 'FFFFF2CC', 'font': 'Arial', 'halign': 'center', 'size': 9.0, 'valign': 'center', 'wrap': True},
    's10': {'bold': True, 'color': 'FF2E75B6', 'font': 'Arial', 'size': 12.0},
    's11': {'bold': True, 'border': {'left': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'color': 'FFFFFFFF', 'fill': 'FF2E75B6', 'font': 'Arial', 'halign': 'left', 'size': 10.0, 'valign': 'center', 'wrap': True},
    's12': {'border': {'top': 'thin', 'bottom': 'thin'}},
    's13': {'bold': True, 'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'color': 'FFFFFFFF', 'fill': 'FF1F4E79', 'font': 'Arial', 'halign': 'center', 'size': 9.0, 'valign': 'center', 'wrap': True},
    's14': {'bold': True, 'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'font': 'Arial', 'halign': 'center', 'size': 10.0, 'valign': 'center', 'wrap': True},
    's15': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'fill': 'FFFCE4D6', 'font': 'Arial', 'halign': 'left', 'size': 9.0, 'valign': 'top', 'wrap': True},
    's16': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'fill': 'FFF2F2F2', 'font': 'Arial', 'halign': 'left', 'size': 9.0, 'valign': 'top', 'wrap': True},
    's17': {'bold': True, 'border': {'left': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'color': 'FFFFFFFF', 'fill': 'FFC00000', 'font': 'Arial', 'halign': 'left', 'size': 10.0, 'valign': 'center', 'wrap': True},
    's18': {'bold': True, 'border': {'left': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'color': 'FFFFFFFF', 'fill': 'FF7030A0', 'font': 'Arial', 'halign': 'left', 'size': 10.0, 'valign': 'center', 'wrap': True},
    's19': {'bold': True, 'color': 'FF1F4E79', 'font': 'Arial', 'size': 13.0},
    's20': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'fill': 'FFFFF2CC', 'font': 'Arial', 'size': 10.0},
    's21': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'fill': 'FFFFF2CC'},
    's22': {'bold': True, 'color': 'FF1F4E79', 'font': 'Arial', 'size': 12.0},
    's23': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'fill': 'FFFFF2CC', 'font': 'Arial', 'numfmt': '0%', 'size': 10.0},
    's24': {'font': 'Arial', 'size': 9.0},
    's25': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'fill': 'FFFFF2CC', 'font': 'Arial', 'halign': 'center', 'numfmt': 'yyyy\\-mm\\-dd', 'size': 9.0, 'valign': 'center', 'wrap': True},
    's26': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'fill': 'FFFFF2CC', 'font': 'Arial', 'halign': 'center', 'numfmt': '0%', 'size': 9.0, 'valign': 'center', 'wrap': True},
    's27': {'bold': True, 'border': {'left': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'color': 'FFFFFFFF', 'fill': 'FF1F4E79', 'font': 'Arial', 'halign': 'center', 'size': 10.0, 'valign': 'center', 'wrap': True},
    's28': {'bold': True, 'border': {'left': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'color': 'FFFFFFFF', 'fill': 'FF2E75B6', 'font': 'Arial', 'halign': 'center', 'size': 10.0, 'valign': 'center', 'wrap': True},
    's29': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'fill': 'FFFFF2CC', 'font': 'Arial', 'halign': 'left', 'size': 9.0, 'valign': 'top', 'wrap': True},
    's30': {'fill': 'FFF2F2F2'},
    's31': {'bold': True, 'border': {'left': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'color': 'FFFFFFFF', 'fill': 'FF7030A0', 'font': 'Arial', 'halign': 'center', 'size': 10.0, 'valign': 'center', 'wrap': True},
    's32': {'bold': True, 'border': {'left': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'color': 'FFFFFFFF', 'fill': 'FF7F7F7F', 'font': 'Arial', 'halign': 'center', 'size': 10.0, 'valign': 'center', 'wrap': True},
    's33': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'fill': 'FFF2F2F2', 'font': 'Arial', 'halign': 'center', 'numfmt': 'yyyy\\-mm\\-dd', 'size': 9.0, 'valign': 'center', 'wrap': True},
    's34': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'fill': 'FFF2F2F2', 'font': 'Arial', 'halign': 'center', 'numfmt': '0%', 'size': 9.0, 'valign': 'center', 'wrap': True},
    's35': {'bold': True, 'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'fill': 'FFF2F2F2', 'font': 'Arial', 'halign': 'center', 'size': 10.0, 'valign': 'center', 'wrap': True},
    's36': {'color': 'FF595959', 'font': 'Arial', 'italic': True, 'size': 9.0},
    's37': {'bold': True, 'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'color': 'FFFFFFFF', 'fill': 'FF2E75B6', 'font': 'Arial', 'halign': 'left', 'size': 9.0, 'valign': 'top', 'wrap': True},
    's38': {'bold': True, 'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'font': 'Arial', 'halign': 'left', 'size': 10.0, 'valign': 'top', 'wrap': True},
    's39': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'font': 'Arial', 'halign': 'left', 'size': 10.0, 'valign': 'top', 'wrap': True},
    's40': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'fill': 'FFFFF2CC', 'font': 'Arial', 'halign': 'left', 'size': 10.0, 'valign': 'top', 'wrap': True},
    's41': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'font': 'Arial', 'halign': 'center', 'numfmt': '0%', 'size': 9.0, 'valign': 'center', 'wrap': True},
    's42': {'bold': True, 'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'fill': 'FFFFF2CC', 'font': 'Arial', 'size': 10.0},
    's43': {'bold': True, 'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'font': 'Arial', 'size': 10.0},
    's44': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'font': 'Arial', 'halign': 'left', 'size': 9.0, 'valign': 'top', 'wrap': True},
    's45': {'bold': True, 'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'fill': 'FFDDEBF7', 'font': 'Arial', 'size': 10.0},
    's46': {'bold': True, 'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'fill': 'FFDDEBF7', 'font': 'Arial', 'halign': 'center', 'size': 10.0, 'valign': 'center', 'wrap': True},
    's47': {'bold': True, 'color': 'FF2E75B6', 'font': 'Arial'},
    's48': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'font': 'Arial', 'numfmt': 'yyyy\\-mm', 'size': 9.0},
    's49': {'border': {'left': 'thin', 'right': 'thin', 'top': 'thin', 'bottom': 'thin'}, 'font': 'Arial', 'size': 10.0},
}

SHEETS = [{
    "name": '1. Guide',
    "widths": {'A': 6.0, 'B': 60.0},
    "heights": {1: 19.7, 3: 15.0, 14: 64.15, 20: 15.0, 28: 15.0, 36: 15.0, 44: 15.0, 52: 15.0},
    "merges": ['A20:C20', 'A28:C28', 'A36:C36', 'A3:C11', 'A44:C44', 'A52:C52'],
    "cells": [
        ('A1', 'HOW TO MEASURE & GUIDE', 's1'),
        ('A3', 'SCORING — place each dimension (A–E) at the HIGHEST LEVEL that SIMULTANEOUSLY meets the qualitative + quantitative conditions:\n•  QUALITATIVE = Yes/No flag ticked by the auditor (MANUAL) → sheet «4. Quarterly» (orange cells).\n•  QUANTITATIVE = measures auto-computed from raw numbers (AUTO) → enter in «3. Monthly» (yellow cells); metrics in «5. Metrics»; levels in «6. Levels».\nOVERALL = MIN( E-Governance , C-Quality , ROUNDED AVERAGE of the 5 dimensions ).  → C and E are GATES.\nMANUAL minimum = exactly 2 places: raw numbers («3. Monthly») + judgment flags («4. Quarterly»).\nThe "already-measured-or-not" flags (a1,a3,b1,b2,b3,c2,d1,d2) are AUTO-derived from data — not ticked.\nCodes a2/a4/b4/c3/G3… = column names in «4. Quarterly». Numeric thresholds (30/50/60/20%) are adjusted in «10. Thresholds».', 's2'),
        ('B3', None, 's3'),
        ('C3', None, 's3'),
        ('A4', None, 's4'),
        ('A5', None, 's4'),
        ('A6', None, 's4'),
        ('A7', None, 's4'),
        ('A8', None, 's4'),
        ('A9', None, 's4'),
        ('A10', None, 's4'),
        ('A11', None, 's4'),
        ('A13', 'COLOR CONVENTIONS:', 's5'),
        ('A14', 'YELLOW CELL — manual entry (raw numbers)', 's6'),
        ('B14', 'GRAY CELL — auto-computed formula', 's7'),
        ('C14', 'ORANGE CELL — Yes/No judgment flag', 's8'),
        ('A16', 'Go to:', 's5'),
        ('B16', '=HYPERLINK("#\'3. Monthly\'!A1","3. Monthly")', 's9'),
        ('C16', '=HYPERLINK("#\'4. Quarterly\'!A1","4. Quarterly")', 's9'),
        ('B17', '=HYPERLINK("#\'6. Levels\'!A1","6. Levels")', 's9'),
        ('C17', '=HYPERLINK("#\'8. Dashboard-Project\'!A1","8. Dashboard-Project")', 's9'),
        ('B18', '=HYPERLINK("#\'9. Dashboard-Portfolio\'!A1","9. Dashboard-Portfolio")', 's9'),
        ('C18', '=HYPERLINK("#\'7. SelfAssessment\'!A1","7. SelfAssessment")', 's9'),
        ('A19', 'LEVEL DEFINITIONS BY 2 METHODS', 's10'),
        ('A20', 'A. ADOPTION  —  Is AI actually being used?', 's11'),
        ('B20', None, 's12'),
        ('C20', None, 's12'),
        ('A21', 'Lv', 's13'),
        ('B21', '=HYPERLINK("#\'4. Quarterly\'!A1","QUALITATIVE  (tick → 4. Quarterly)")', 's13'),
        ('C21', '=HYPERLINK("#\'3. Monthly\'!A1","QUANTITATIVE  (auto ← 3. Monthly / 5. Metrics)")', 's13'),
        ('A22', 1, 's14'),
        ('B22', 'Sporadic use, unclear who uses it', 's15'),
        ('C22', '— (a1 auto-derived: no usage numbers yet)', 's16'),
        ('A23', 2, 's14'),
        ('B23', '—', 's15'),
        ('C23', 'a1 auto = usage numbers exist  &  usage rate ≥ 50%', 's16'),
        ('A24', 3, 's14'),
        ('B24', 'a2 = Yes (tracking dashboard exists)', 's15'),
        ('C24', 'AI PR % ≥ 30%', 's16'),
        ('A25', 4, 's14'),
        ('B25', '— (a3 auto-derived: % work assigned to agents measured)', 's15'),
        ('C25', 'AI PR % > 50%', 's16'),
        ('A26', 5, 's14'),
        ('B26', 'a4 = Yes (adoption near-universal, intentional)', 's15'),
        ('C26', '—', 's16'),
        ('A28', 'B. DELIVERY & VALUE  —  Faster & more stable delivery? (DORA)', 's11'),
        ('B28', None, 's12'),
        ('C28', None, 's12'),
        ('A29', 'Lv', 's13'),
        ('B29', '=HYPERLINK("#\'4. Quarterly\'!A1","QUALITATIVE  (tick → 4. Quarterly)")', 's13'),
        ('C29', '=HYPERLINK("#\'3. Monthly\'!A1","QUANTITATIVE  (auto ← 3. Monthly / 5. Metrics)")', 's13'),
        ('A30', 1, 's14'),
        ('B30', 'Nothing measured yet', 's15'),
        ('C30', '—', 's16'),
        ('A31', 2, 's14'),
        ('B31', '—', 's15'),
        ('C31', 'b1 auto = Deploys/week exists', 's16'),
        ('A32', 3, 's14'),
        ('B32', '—', 's15'),
        ('C32', 'b2 auto (all 4 DORA) & b3 auto (cost baseline exists)', 's16'),
        ('A33', 4, 's14'),
        ('B33', 'b4 + b5 + b6 = Yes', 's15'),
        ('C33', '(with 4 DORA improving — see trend)', 's16'),
        ('A34', 5, 's14'),
        ('B34', 'b7 + b8 = Yes (regular client reporting)', 's15'),
        ('C34', 'DORA top-quartile & stable', 's16'),
        ('A36', 'C. QUALITY & SECURITY  ★ GATE  —  Output correct, clean, safe?', 's17'),
        ('B36', None, 's12'),
        ('C36', None, 's12'),
        ('A37', 'Lv', 's13'),
        ('B37', '=HYPERLINK("#\'4. Quarterly\'!A1","QUALITATIVE  (tick → 4. Quarterly)")', 's13'),
        ('C37', '=HYPERLINK("#\'3. Monthly\'!A1","QUANTITATIVE  (auto ← 3. Monthly / 5. Metrics)")', 's13'),
        ('A38', 1, 's14'),
        ('B38', 'Not measured, assessed by eye', 's15'),
        ('C38', '—', 's16'),
        ('A39', 2, 's14'),
        ('B39', 'Has ≥1 of: G3 / c3', 's15'),
        ('C39', 'c2 auto = Rework% exists', 's16'),
        ('A40', 3, 's14'),
        ('B40', 'G3 + c3 (required review, basic scanning)', 's15'),
        ('C40', 'c2 auto (Rework% tracked); AI PRs reviewed %', 's16'),
        ('A41', 4, 's14'),
        ('B41', 'c4 + c5 + c6 (evals; SAST/PII required)', 's15'),
        ('C41', 'Rework% down; Coverage up', 's16'),
        ('A42', 5, 's14'),
        ('B42', 'c7 + c8 + c9 (prompt-leak / PII controls)', 's15'),
        ('C42', 'Vulns & defect ≈ 0', 's16'),
        ('A44', 'D. AGENT MATURITY  —  How autonomous are agents?', 's11'),
        ('B44', None, 's12'),
        ('C44', None, 's12'),
        ('A45', 'Lv', 's13'),
        ('B45', '=HYPERLINK("#\'4. Quarterly\'!A1","QUALITATIVE  (tick → 4. Quarterly)")', 's13'),
        ('C45', '=HYPERLINK("#\'3. Monthly\'!A1","QUANTITATIVE  (auto ← 3. Monthly / 5. Metrics)")', 's13'),
        ('A46', 1, 's14'),
        ('B46', '— (d1 auto-derived: no tasks assigned to agents yet)', 's15'),
        ('C46', '—', 's16'),
        ('A47', 2, 's14'),
        ('B47', '— (d2 auto-derived: completion/intervention not measured)', 's15'),
        ('C47', 'd1 auto = tasks assigned to agents exist', 's16'),
        ('A48', 3, 's14'),
        ('B48', '—', 's15'),
        ('C48', 'd2 auto = Agent success% + Human intervention% exist', 's16'),
        ('A49', 4, 's14'),
        ('B49', 'd3 + d4 (defined class + cycle time measured)', 's15'),
        ('C49', 'Autonomous ≥ 30%', 's16'),
        ('A50', 5, 's14'),
        ('B50', 'd5 + d3 + d4 (multi-agent)', 's15'),
        ('C50', 'Autonomous ≥ 60%  &  Intervention ≤ 20%', 's16'),
        ('A52', 'E. GOVERNANCE  ★ GATE  —  Disciplined AI use? (8-item checklist)', 's18'),
        ('B52', None, 's12'),
        ('C52', None, 's12'),
        ('A53', 'Lv', 's13'),
        ('B53', '=HYPERLINK("#\'4. Quarterly\'!A1","QUALITATIVE  (tick → 4. Quarterly)")', 's13'),
        ('C53', '=HYPERLINK("#\'3. Monthly\'!A1","QUANTITATIVE  (auto ← 3. Monthly / 5. Metrics)")', 's13'),
        ('A54', 1, 's14'),
        ('B54', '0–1 items Yes', 's15'),
        ('C54', 'Checklist score = 0–1 / 8', 's16'),
        ('A55', 2, 's14'),
        ('B55', '2 items Yes', 's15'),
        ('C55', 'Score = 2 / 8', 's16'),
        ('A56', 3, 's14'),
        ('B56', 'All 3 Core: G1 AGENTS.md · G2 policy · G3 review', 's15'),
        ('C56', 'Score ≥ 3 (Core complete)', 's16'),
        ('A57', 4, 's14'),
        ('B57', 'All G1–G5 (Core + Advanced)', 's15'),
        ('C57', 'Score = 5 (items 1–5)', 's16'),
        ('A58', 5, 's14'),
        ('B58', 'All 8 (plus Security & Audit)', 's15'),
        ('C58', 'Score = 8 / 8', 's16'),
    ],
    "color_scales": [
        ('A22:A26', [('num', 1.0), ('num', 3.0), ('num', 5.0)], ['FFF8696B', 'FFFFEB84', 'FF63BE7B']),
        ('A30:A34', [('num', 1.0), ('num', 3.0), ('num', 5.0)], ['FFF8696B', 'FFFFEB84', 'FF63BE7B']),
        ('A38:A42', [('num', 1.0), ('num', 3.0), ('num', 5.0)], ['FFF8696B', 'FFFFEB84', 'FF63BE7B']),
        ('A46:A50', [('num', 1.0), ('num', 3.0), ('num', 5.0)], ['FFF8696B', 'FFFFEB84', 'FF63BE7B']),
        ('A54:A58', [('num', 1.0), ('num', 3.0), ('num', 5.0)], ['FFF8696B', 'FFFFEB84', 'FF63BE7B']),
    ],
}, {
    "name": '2. Projects',
    "widths": {'A': 12.0, 'B': 22.0, 'C': 18.0, 'D': 16.0},
    "heights": {1: 16.15},
    "data_rows": (3, 20),
    "cells": [
        ('A1', 'PROJECT DIRECTORY', 's19'),
        ('A2', 'ProjectID', 's13'),
        ('B2', 'Project name', 's13'),
        ('C2', 'Main tool', 's13'),
        ('D2', 'Tech Lead', 's13'),
        ('E2', 'Client / Area', 's13'),
        ('A3', None, 's20'),
        ('B3', None, 's20'),
        ('C3', None, 's20'),
        ('D3', None, 's20'),
        ('E3', None, 's20'),
        ('A4', None, 's20'),
        ('B4', None, 's20'),
        ('C4', None, 's20'),
        ('D4', None, 's20'),
        ('E4', None, 's20'),
        ('A5', None, 's20'),
        ('B5', None, 's20'),
        ('C5', None, 's20'),
        ('D5', None, 's20'),
        ('E5', None, 's20'),
        ('A6', None, 's21'),
        ('B6', None, 's21'),
        ('C6', None, 's21'),
        ('D6', None, 's21'),
        ('E6', None, 's21'),
        ('A7', None, 's21'),
        ('B7', None, 's21'),
        ('C7', None, 's21'),
        ('D7', None, 's21'),
        ('E7', None, 's21'),
        ('A8', None, 's21'),
        ('B8', None, 's21'),
        ('C8', None, 's21'),
        ('D8', None, 's21'),
        ('E8', None, 's21'),
        ('A9', None, 's21'),
        ('B9', None, 's21'),
        ('C9', None, 's21'),
        ('D9', None, 's21'),
        ('E9', None, 's21'),
        ('A10', None, 's21'),
        ('B10', None, 's21'),
        ('C10', None, 's21'),
        ('D10', None, 's21'),
        ('E10', None, 's21'),
        ('A11', None, 's21'),
        ('B11', None, 's21'),
        ('C11', None, 's21'),
        ('D11', None, 's21'),
        ('E11', None, 's21'),
        ('A12', None, 's21'),
        ('B12', None, 's21'),
        ('C12', None, 's21'),
        ('D12', None, 's21'),
        ('E12', None, 's21'),
        ('A13', None, 's21'),
        ('B13', None, 's21'),
        ('C13', None, 's21'),
        ('D13', None, 's21'),
        ('E13', None, 's21'),
        ('A14', None, 's21'),
        ('B14', None, 's21'),
        ('C14', None, 's21'),
        ('D14', None, 's21'),
        ('E14', None, 's21'),
        ('A15', None, 's21'),
        ('B15', None, 's21'),
        ('C15', None, 's21'),
        ('D15', None, 's21'),
        ('E15', None, 's21'),
        ('A16', None, 's21'),
        ('B16', None, 's21'),
        ('C16', None, 's21'),
        ('D16', None, 's21'),
        ('E16', None, 's21'),
        ('A17', None, 's21'),
        ('B17', None, 's21'),
        ('C17', None, 's21'),
        ('D17', None, 's21'),
        ('E17', None, 's21'),
        ('A18', None, 's21'),
        ('B18', None, 's21'),
        ('C18', None, 's21'),
        ('D18', None, 's21'),
        ('E18', None, 's21'),
        ('A19', None, 's21'),
        ('B19', None, 's21'),
        ('C19', None, 's21'),
        ('D19', None, 's21'),
        ('E19', None, 's21'),
        ('A20', None, 's21'),
        ('B20', None, 's21'),
        ('C20', None, 's21'),
        ('D20', None, 's21'),
        ('E20', None, 's21'),
    ],
}, {
    "name": '10. Thresholds',
    "widths": {'A': 12.0, 'B': 10.0, 'C': 50.0},
    "cells": [
        ('A1', 'LEVEL THRESHOLDS (adjustable)', 's22'),
        ('A2', 'Parameter', 's13'),
        ('B2', 'Value', 's13'),
        ('C2', 'Meaning', 's13'),
        ('A3', 'pr_L3', 's5'),
        ('B3', 0.3, 's23'),
        ('C3', 'Adoption L3: AI PR % ≥ 30%', 's24'),
        ('A4', 'pr_L4', 's5'),
        ('B4', 0.5, 's23'),
        ('C4', 'Adoption L4: AI PR % > 50%', 's24'),
        ('A5', 'usage_L2', 's5'),
        ('B5', 0.5, 's23'),
        ('C5', 'Adoption L2: AI user rate ≥ 50%', 's24'),
        ('A6', 'aut_L4', 's5'),
        ('B6', 0.3, 's23'),
        ('C6', 'Agent L4: autonomous ≥ 30%', 's24'),
        ('A7', 'aut_L5', 's5'),
        ('B7', 0.6, 's23'),
        ('C7', 'Agent L5: autonomous ≥ 60%', 's24'),
        ('A8', 'int_L5', 's5'),
        ('B8', 0.2, 's23'),
        ('C8', 'Agent L5: intervention ≤ 20%', 's24'),
    ],
}, {
    "name": '3. Monthly',
    "freeze": 'D4',
    "widths": {'A': 11.0, 'B': 15.0, 'C': 11.0},
    "heights": {2: 15.0, 3: 22.35},
    "merges": ['A2:C2', 'D2:I2', 'J2:P2', 'Q2:T2', 'U2:X2'],
    "data_rows": (4, 203),
    "columns": [
        ('A', None, 's6'),
        ('B', None, 's25'),
        ('C', '=IF($B{r}="","",YEAR(B{r})&"-Q"&ROUNDUP(MONTH(B{r})/3,0))', 's7'),
        ('D', None, 's6'),
        ('E', None, 's6'),
        ('F', None, 's6'),
        ('G', None, 's6'),
        ('H', None, 's6'),
        ('I', None, 's6'),
        ('J', None, 's6'),
        ('K', None, 's6'),
        ('L', None, 's6'),
        ('M', None, 's6'),
        ('N', None, 's6'),
        ('O', None, 's6'),
        ('P', None, 's6'),
        ('Q', None, 's6'),
        ('R', None, 's6'),
        ('S', None, 's26'),
        ('T', None, 's6'),
        ('U', None, 's6'),
        ('V', None, 's6'),
        ('W', None, 's6'),
        ('X', None, 's6'),
    ],
    "cells": [
        ('A1', 'MONTHLY RAW INPUT — enter raw numbers only (yellow cells). Percentages are in «5. Metrics».', 's22'),
        ('A2', 'KEY', 's27'),
        ('B2', None, 's12'),
        ('C2', None, 's12'),
        ('D2', 'A. ADOPTION (raw)', 's28'),
        ('E2', None, 's12'),
        ('F2', None, 's12'),
        ('G2', None, 's12'),
        ('H2', None, 's12'),
        ('I2', None, 's12'),
        ('J2', 'B. DELIVERY (raw)', 's28'),
        ('K2', None, 's12'),
        ('L2', None, 's12'),
        ('M2', None, 's12'),
        ('N2', None, 's12'),
        ('O2', None, 's12'),
        ('P2', None, 's12'),
        ('Q2', 'C. QUALITY (raw)', 's28'),
        ('R2', None, 's12'),
        ('S2', None, 's12'),
        ('T2', None, 's12'),
        ('U2', 'D. AGENT (raw)', 's28'),
        ('V2', None, 's12'),
        ('W2', None, 's12'),
        ('X2', None, 's12'),
        ('A3', 'ProjectID', 's13'),
        ('B3', 'Month (first day)', 's13'),
        ('C3', 'Quarter', 's13'),
        ('D3', 'Engineers using AI/week', 's13'),
        ('E3', 'Total engineers', 's13'),
        ('F3', 'AI-labeled PRs', 's13'),
        ('G3', 'Total PRs', 's13'),
        ('H3', 'Tasks assigned to agents', 's13'),
        ('I3', 'Total tasks', 's13'),
        ('J3', 'Lead time (h)', 's13'),
        ('K3', 'Deploy count', 's13'),
        ('L3', 'Weeks', 's13'),
        ('M3', 'Failed deploys', 's13'),
        ('N3', 'MTTR (h)', 's13'),
        ('O3', 'Cost baseline/unit', 's13'),
        ('P3', 'Cost actual/unit', 's13'),
        ('Q3', 'PR rework ≤14d', 's13'),
        ('R3', 'AI PRs reviewed', 's13'),
        ('S3', 'Coverage AI (%)', 's13'),
        ('T3', 'Vulns/secrets blocked', 's13'),
        ('U3', 'Agent tasks done OK', 's13'),
        ('V3', 'Agent tasks needing fixes', 's13'),
        ('W3', 'Agent end-to-end', 's13'),
        ('X3', 'Agent cycle (h)', 's13'),
    ],
}, {
    "name": '4. Quarterly',
    "freeze": 'C4',
    "widths": {'A': 10.0, 'B': 9.0, 'C': 12.0, 'AB': 20.0, 'AH': 13.0},
    "heights": {2: 15.0, 3: 32.85, 4: 32.85, 5: 43.35, 6: 32.85},
    "merges": ['A2:B2', 'AB2:AG2', 'C2:J2', 'K2:L2', 'M2:Q2', 'R2:X2', 'Y2:AA2'],
    "data_rows": (4, 53),
    "columns": [
        ('A', None, 's6'),
        ('B', None, 's6'),
        ('C', None, 's8'),
        ('D', None, 's8'),
        ('E', None, 's8'),
        ('F', None, 's8'),
        ('G', None, 's8'),
        ('H', None, 's8'),
        ('I', None, 's8'),
        ('J', None, 's8'),
        ('K', None, 's8'),
        ('L', None, 's8'),
        ('M', None, 's8'),
        ('N', None, 's8'),
        ('O', None, 's8'),
        ('P', None, 's8'),
        ('Q', None, 's8'),
        ('R', None, 's8'),
        ('S', None, 's8'),
        ('T', None, 's8'),
        ('U', None, 's8'),
        ('V', None, 's8'),
        ('W', None, 's8'),
        ('X', None, 's8'),
        ('Y', None, 's8'),
        ('Z', None, 's8'),
        ('AA', None, 's8'),
        ('AB', None, 's29'),
        ('AC', None, 's29'),
        ('AD', None, 's29'),
        ('AE', None, 's29'),
        ('AF', None, 's29'),
        ('AG', None, 's29'),
        ('AH', '=IF($A{r}="","",$A{r}&"|"&$B{r})', 's30'),
    ],
    "cells": [
        ('A1', "QUARTERLY SCORING — tick JUDGMENT flags only (orange cells). 'Measured' flags are derived.", 's22'),
        ('A2', 'KEY', 's27'),
        ('B2', None, 's12'),
        ('C2', 'E. GOVERNANCE — 8-item checklist', 's31'),
        ('D2', None, 's12'),
        ('E2', None, 's12'),
        ('F2', None, 's12'),
        ('G2', None, 's12'),
        ('H2', None, 's12'),
        ('I2', None, 's12'),
        ('J2', None, 's12'),
        ('K2', 'A', 's28'),
        ('L2', None, 's12'),
        ('M2', 'B. DELIVERY', 's28'),
        ('N2', None, 's12'),
        ('O2', None, 's12'),
        ('P2', None, 's12'),
        ('Q2', None, 's12'),
        ('R2', 'C. QUALITY', 's28'),
        ('S2', None, 's12'),
        ('T2', None, 's12'),
        ('U2', None, 's12'),
        ('V2', None, 's12'),
        ('W2', None, 's12'),
        ('X2', None, 's12'),
        ('Y2', 'D. AGENT', 's28'),
        ('Z2', None, 's12'),
        ('AA2', None, 's12'),
        ('AB2', 'EVIDENCE / ACTION', 's32'),
        ('AC2', None, 's12'),
        ('AD2', None, 's12'),
        ('AE2', None, 's12'),
        ('AF2', None, 's12'),
        ('AG2', None, 's12'),
        ('A3', 'ProjectID', 's13'),
        ('B3', 'Quarter', 's13'),
        ('C3', 'G1 AGENTS.md', 's13'),
        ('D3', 'G2 AI policy', 's13'),
        ('E3', 'G3 Required review', 's13'),
        ('F3', 'G4 Eval suite', 's13'),
        ('G3', 'G5 Shared library', 's13'),
        ('H3', 'G6 Security controls', 's13'),
        ('I3', 'G7 Traceability+logs', 's13'),
        ('J3', 'G8 Model governance', 's13'),
        ('K3', 'a2 dashboard', 's13'),
        ('L3', 'a4 near-universal', 's13'),
        ('M3', 'b4 DORA improving', 's13'),
        ('N3', 'b5 cost target, many workflows', 's13'),
        ('O3', 'b6 business outcomes', 's13'),
        ('P3', 'b7 top-quartile', 's13'),
        ('Q3', 'b8 client reporting', 's13'),
        ('R3', 'c3 basic CI scanning', 's13'),
        ('S3', 'c4 AI vs non-AI compared', 's13'),
        ('T3', 'c5 evals exist', 's13'),
        ('U3', 'c6 SAST/PII required', 's13'),
        ('V3', 'c7 defects ~0', 's13'),
        ('W3', 'c8 evals in CI', 's13'),
        ('X3', 'c9 prompt-leak/PII', 's13'),
        ('Y3', 'd3 defined task class', 's13'),
        ('Z3', 'd4 cycle time measured', 's13'),
        ('AA3', 'd5 multi-agent', 's13'),
        ('AB3', 'Evidence A', 's13'),
        ('AC3', 'Evidence B', 's13'),
        ('AD3', 'Evidence C', 's13'),
        ('AE3', 'Evidence D', 's13'),
        ('AF3', 'Evidence E', 's13'),
        ('AG3', 'Improvement action', 's13'),
    ],
    "validations": [('list', '"2026-Q1,2026-Q2,2026-Q3,2026-Q4"', 'B4:B53'), ('list', '"Yes,No"', 'C4:AA53')],
}, {
    "name": '5. Metrics',
    "freeze": 'D4',
    "widths": {'A': 11.0, 'B': 13.0, 'C': 11.0},
    "heights": {2: 22.35},
    "data_rows": (4, 203),
    "columns": [
        ('A', '=IF(\'3. Monthly\'!A{r}="","",\'3. Monthly\'!A{r})', 's7'),
        ('B', '=IF(\'3. Monthly\'!A{r}="","",\'3. Monthly\'!B{r})', 's33'),
        ('C', '=IF(\'3. Monthly\'!A{r}="","",\'3. Monthly\'!C{r})', 's7'),
        ('D', '=IFERROR(\'3. Monthly\'!D{r}/\'3. Monthly\'!E{r},"")', 's34'),
        ('E', '=IFERROR(\'3. Monthly\'!F{r}/\'3. Monthly\'!G{r},"")', 's34'),
        ('F', '=IFERROR(\'3. Monthly\'!H{r}/\'3. Monthly\'!I{r},"")', 's34'),
        ('G', '=IF(\'3. Monthly\'!J{r}="","",\'3. Monthly\'!J{r})', 's7'),
        ('H', '=IFERROR(\'3. Monthly\'!K{r}/\'3. Monthly\'!L{r},"")', 's7'),
        ('I', '=IFERROR(\'3. Monthly\'!M{r}/\'3. Monthly\'!K{r},"")', 's34'),
        ('J', '=IF(\'3. Monthly\'!N{r}="","",\'3. Monthly\'!N{r})', 's7'),
        ('K', '=IFERROR((\'3. Monthly\'!O{r}-\'3. Monthly\'!P{r})/\'3. Monthly\'!O{r},"")', 's34'),
        ('L', '=IFERROR(\'3. Monthly\'!Q{r}/\'3. Monthly\'!G{r},"")', 's34'),
        ('M', '=IFERROR(\'3. Monthly\'!R{r}/\'3. Monthly\'!F{r},"")', 's34'),
        ('N', '=IF(\'3. Monthly\'!S{r}="","",\'3. Monthly\'!S{r})', 's34'),
        ('O', '=IF(\'3. Monthly\'!T{r}="","",\'3. Monthly\'!T{r})', 's7'),
        ('P', '=IFERROR(\'3. Monthly\'!U{r}/\'3. Monthly\'!H{r},"")', 's34'),
        ('Q', '=IFERROR(\'3. Monthly\'!V{r}/\'3. Monthly\'!H{r},"")', 's34'),
        ('R', '=IFERROR(\'3. Monthly\'!W{r}/\'3. Monthly\'!H{r},"")', 's34'),
        ('S', '=IF(\'3. Monthly\'!X{r}="","",\'3. Monthly\'!X{r})', 's7'),
    ],
    "cells": [
        ('A1', 'METRICS (auto-computed from «3. Monthly») — do not type.', 's22'),
        ('A2', 'ProjectID', 's13'),
        ('B2', 'Month', 's13'),
        ('C2', 'Quarter', 's13'),
        ('D2', 'AI usage %', 's13'),
        ('E2', 'AI PR %', 's13'),
        ('F2', '%task agent', 's13'),
        ('G2', 'Lead time(h)', 's13'),
        ('H2', 'Deploys/week', 's13'),
        ('I2', 'CFR %', 's13'),
        ('J2', 'MTTR(h)', 's13'),
        ('K2', 'Cost improvement %', 's13'),
        ('L2', 'Rework %', 's13'),
        ('M2', '%PR-AI review', 's13'),
        ('N2', 'Coverage %', 's13'),
        ('O2', 'Vulns', 's13'),
        ('P2', 'Agent success %', 's13'),
        ('Q2', 'Human interv %', 's13'),
        ('R2', 'Autonomous %', 's13'),
        ('S2', 'Agent cycle(h)', 's13'),
    ],
}, {
    "name": '6. Levels',
    "freeze": 'D4',
    "widths": {'A': 9.0, 'C': 16.0, 'D': 9.0, 'U': 9.0},
    "heights": {3: 22.35, 4: 22.35, 5: 22.35, 6: 22.35},
    "data_rows": (4, 53),
    "columns": [
        ('A', "='4. Quarterly'!A{r}", 's7'),
        ('B', "='4. Quarterly'!B{r}", 's7'),
        ('C', '=IFERROR(VLOOKUP($A{r},\'2. Projects\'!$A$3:$B$20,2,0),"")', 's7'),
        ('D', '=IF($A{r}="","",IFERROR(AVERAGEIFS(\'5. Metrics\'!$D$4:$D$203,\'5. Metrics\'!$A$4:$A$203,$A{r},\'5. Metrics\'!$C$4:$C$203,$B{r}),""))', 's34'),
        ('E', '=IF($A{r}="","",IFERROR(AVERAGEIFS(\'5. Metrics\'!$E$4:$E$203,\'5. Metrics\'!$A$4:$A$203,$A{r},\'5. Metrics\'!$C$4:$C$203,$B{r}),""))', 's34'),
        ('F', '=IF($A{r}="","",IFERROR(AVERAGEIFS(\'5. Metrics\'!$F$4:$F$203,\'5. Metrics\'!$A$4:$A$203,$A{r},\'5. Metrics\'!$C$4:$C$203,$B{r}),""))', 's34'),
        ('G', '=IF($A{r}="","",IFERROR(AVERAGEIFS(\'5. Metrics\'!$I$4:$I$203,\'5. Metrics\'!$A$4:$A$203,$A{r},\'5. Metrics\'!$C$4:$C$203,$B{r}),""))', 's34'),
        ('H', '=IF($A{r}="","",IFERROR(AVERAGEIFS(\'5. Metrics\'!$L$4:$L$203,\'5. Metrics\'!$A$4:$A$203,$A{r},\'5. Metrics\'!$C$4:$C$203,$B{r}),""))', 's34'),
        ('I', '=IF($A{r}="","",IFERROR(AVERAGEIFS(\'5. Metrics\'!$M$4:$M$203,\'5. Metrics\'!$A$4:$A$203,$A{r},\'5. Metrics\'!$C$4:$C$203,$B{r}),""))', 's34'),
        ('J', '=IF($A{r}="","",IFERROR(AVERAGEIFS(\'5. Metrics\'!$N$4:$N$203,\'5. Metrics\'!$A$4:$A$203,$A{r},\'5. Metrics\'!$C$4:$C$203,$B{r}),""))', 's34'),
        ('K', '=IF($A{r}="","",IFERROR(AVERAGEIFS(\'5. Metrics\'!$P$4:$P$203,\'5. Metrics\'!$A$4:$A$203,$A{r},\'5. Metrics\'!$C$4:$C$203,$B{r}),""))', 's34'),
        ('L', '=IF($A{r}="","",IFERROR(AVERAGEIFS(\'5. Metrics\'!$Q$4:$Q$203,\'5. Metrics\'!$A$4:$A$203,$A{r},\'5. Metrics\'!$C$4:$C$203,$B{r}),""))', 's34'),
        ('M', '=IF($A{r}="","",IFERROR(AVERAGEIFS(\'5. Metrics\'!$R$4:$R$203,\'5. Metrics\'!$A$4:$A$203,$A{r},\'5. Metrics\'!$C$4:$C$203,$B{r}),""))', 's34'),
        ('N', '=IF($A{r}="","",IF(\'4. Quarterly\'!L{r}="Yes",5,IF(AND(ISNUMBER(E{r}),E{r}>\'10. Thresholds\'!$B$4,V{r}="Yes"),4,IF(AND(\'4. Quarterly\'!K{r}="Yes",ISNUMBER(E{r}),E{r}>=\'10. Thresholds\'!$B$3),3,IF(AND(U{r}="Yes",ISNUMBER(D{r}),D{r}>=\'10. Thresholds\'!$B$5),2,1)))))', 's35'),
        ('O', '=IF($A{r}="","",IF(AND(\'4. Quarterly\'!P{r}="Yes",\'4. Quarterly\'!Q{r}="Yes",\'4. Quarterly\'!M{r}="Yes",\'4. Quarterly\'!N{r}="Yes",\'4. Quarterly\'!O{r}="Yes",X{r}="Yes",Y{r}="Yes"),5,IF(AND(\'4. Quarterly\'!M{r}="Yes",\'4. Quarterly\'!N{r}="Yes",\'4. Quarterly\'!O{r}="Yes",X{r}="Yes",Y{r}="Yes"),4,IF(AND(X{r}="Yes",Y{r}="Yes"),3,IF(W{r}="Yes",2,1)))))', 's35'),
        ('P', '=IF($A{r}="","",IF(AND(\'4. Quarterly\'!V{r}="Yes",\'4. Quarterly\'!W{r}="Yes",\'4. Quarterly\'!X{r}="Yes",\'4. Quarterly\'!S{r}="Yes",\'4. Quarterly\'!T{r}="Yes",\'4. Quarterly\'!U{r}="Yes",\'4. Quarterly\'!E{r}="Yes",Z{r}="Yes",\'4. Quarterly\'!R{r}="Yes"),5,IF(AND(\'4. Quarterly\'!S{r}="Yes",\'4. Quarterly\'!T{r}="Yes",\'4. Quarterly\'!U{r}="Yes",\'4. Quarterly\'!E{r}="Yes",Z{r}="Yes",\'4. Quarterly\'!R{r}="Yes"),4,IF(AND(\'4. Quarterly\'!E{r}="Yes",Z{r}="Yes",\'4. Quarterly\'!R{r}="Yes"),3,IF(OR(Z{r}="Yes",\'4. Quarterly\'!R{r}="Yes",\'4. Quarterly\'!E{r}="Yes"),2,1)))))', 's35'),
        ('Q', '=IF($A{r}="","",IF(AA{r}<>"Yes",1,IF(AB{r}<>"Yes",2,IF(AND(\'4. Quarterly\'!AA{r}="Yes",\'4. Quarterly\'!Y{r}="Yes",\'4. Quarterly\'!Z{r}="Yes",ISNUMBER(M{r}),M{r}>=\'10. Thresholds\'!$B$7,ISNUMBER(L{r}),L{r}<=\'10. Thresholds\'!$B$8),5,IF(AND(\'4. Quarterly\'!Y{r}="Yes",\'4. Quarterly\'!Z{r}="Yes",ISNUMBER(M{r}),M{r}>=\'10. Thresholds\'!$B$6),4,3)))))', 's35'),
        ('R', '=IF($A{r}="","",IF(AND(\'4. Quarterly\'!C{r}="Yes",\'4. Quarterly\'!D{r}="Yes",\'4. Quarterly\'!E{r}="Yes",\'4. Quarterly\'!F{r}="Yes",\'4. Quarterly\'!G{r}="Yes",\'4. Quarterly\'!H{r}="Yes",\'4. Quarterly\'!I{r}="Yes",\'4. Quarterly\'!J{r}="Yes"),5,IF(AND(\'4. Quarterly\'!C{r}="Yes",\'4. Quarterly\'!D{r}="Yes",\'4. Quarterly\'!E{r}="Yes",\'4. Quarterly\'!F{r}="Yes",\'4. Quarterly\'!G{r}="Yes"),4,IF(AND(\'4. Quarterly\'!C{r}="Yes",\'4. Quarterly\'!D{r}="Yes",\'4. Quarterly\'!E{r}="Yes"),3,IF(COUNTIF(\'4. Quarterly\'!C{r}:J{r},"Yes")>=2,2,1)))))', 's35'),
        ('S', '=IF($A{r}="","",MIN(R{r},P{r},ROUND(AVERAGE(N{r},O{r},P{r},Q{r},R{r}),0)))', 's35'),
        ('T', '=IF($A{r}="","",$A{r}&"|"&$B{r})', 's7'),
        ('U', '=IF($A{r}="","No",IF(COUNTIFS(\'3. Monthly\'!$A$4:$A$203,$A{r},\'3. Monthly\'!$C$4:$C$203,$B{r},\'3. Monthly\'!$E$4:$E$203,">0")>0,"Yes","No"))', 's7'),
        ('V', '=IF($A{r}="","No",IF(COUNTIFS(\'3. Monthly\'!$A$4:$A$203,$A{r},\'3. Monthly\'!$C$4:$C$203,$B{r},\'3. Monthly\'!$I$4:$I$203,">0")>0,"Yes","No"))', 's7'),
        ('W', '=IF($A{r}="","No",IF(COUNTIFS(\'3. Monthly\'!$A$4:$A$203,$A{r},\'3. Monthly\'!$C$4:$C$203,$B{r},\'3. Monthly\'!$K$4:$K$203,">=0",\'3. Monthly\'!$L$4:$L$203,">0")>0,"Yes","No"))', 's7'),
        ('X', '=IF($A{r}="","No",IF(COUNTIFS(\'3. Monthly\'!$A$4:$A$203,$A{r},\'3. Monthly\'!$C$4:$C$203,$B{r},\'3. Monthly\'!$J$4:$J$203,">=0",\'3. Monthly\'!$K$4:$K$203,">=0",\'3. Monthly\'!$M$4:$M$203,">=0",\'3. Monthly\'!$N$4:$N$203,">=0",\'3. Monthly\'!$L$4:$L$203,">0")>0,"Yes","No"))', 's7'),
        ('Y', '=IF($A{r}="","No",IF(COUNTIFS(\'3. Monthly\'!$A$4:$A$203,$A{r},\'3. Monthly\'!$C$4:$C$203,$B{r},\'3. Monthly\'!$O$4:$O$203,">0")>0,"Yes","No"))', 's7'),
        ('Z', '=IF($A{r}="","No",IF(COUNTIFS(\'3. Monthly\'!$A$4:$A$203,$A{r},\'3. Monthly\'!$C$4:$C$203,$B{r},\'3. Monthly\'!$Q$4:$Q$203,">=0",\'3. Monthly\'!$G$4:$G$203,">0")>0,"Yes","No"))', 's7'),
        ('AA', '=IF($A{r}="","No",IF(COUNTIFS(\'3. Monthly\'!$A$4:$A$203,$A{r},\'3. Monthly\'!$C$4:$C$203,$B{r},\'3. Monthly\'!$H$4:$H$203,">0")>0,"Yes","No"))', 's7'),
        ('AB', '=IF($A{r}="","No",IF(COUNTIFS(\'3. Monthly\'!$A$4:$A$203,$A{r},\'3. Monthly\'!$C$4:$C$203,$B{r},\'3. Monthly\'!$U$4:$U$203,">=0",\'3. Monthly\'!$V$4:$V$203,">=0",\'3. Monthly\'!$H$4:$H$203,">0")>0,"Yes","No"))', 's7'),
    ],
    "cells": [
        ('A1', 'LEVEL MAPPING (auto) — looked up by key ProjectID+Quarter. Do not type.', 's22'),
        ('A3', 'ProjectID', 's13'),
        ('B3', 'Quarter', 's13'),
        ('C3', 'Project name', 's13'),
        ('D3', 'AI usage%', 's13'),
        ('E3', '%PR-AI', 's13'),
        ('F3', '%agent', 's13'),
        ('G3', 'CFR%', 's13'),
        ('H3', 'Rework%', 's13'),
        ('I3', '%AI review', 's13'),
        ('J3', 'Coverage%', 's13'),
        ('K3', 'Agent succ%', 's13'),
        ('L3', 'Human interv%', 's13'),
        ('M3', 'Autonomous%', 's13'),
        ('N3', 'A', 's13'),
        ('O3', 'B', 's13'),
        ('P3', 'C', 's13'),
        ('Q3', 'D', 's13'),
        ('R3', 'E', 's13'),
        ('S3', 'OVERALL', 's13'),
        ('T3', 'Key', 's13'),
        ('U3', 'a1', 's13'),
        ('V3', 'a3', 's13'),
        ('W3', 'b1', 's13'),
        ('X3', 'b2', 's13'),
        ('Y3', 'b3', 's13'),
        ('Z3', 'c2', 's13'),
        ('AA3', 'd1', 's13'),
        ('AB3', 'd2', 's13'),
    ],
    "color_scales": [
        ('N4:S53', [('num', 1.0), ('num', 3.0), ('num', 5.0)], ['FFF8696B', 'FFFFEB84', 'FF63BE7B']),
    ],
}, {
    "name": '7. SelfAssessment',
    "widths": {'A': 24.0, 'B': 70.0, 'C': 16.0, 'D': 40.0},
    "heights": {5: 23.85, 6: 23.85, 7: 23.85, 8: 23.85, 9: 23.85, 10: 23.85, 12: 22.35, 13: 35.1, 14: 35.1, 15: 35.1, 16: 23.85, 17: 35.1, 18: 35.1},
    "cells": [
        ('A1', 'BASELINE SELF-ASSESSMENT — kickoff + reviewed each quarter', 's22'),
        ('A2', "Each 'No' is an action to establish a baseline before measuring.", 's36'),
        ('A4', 'Topic', 's37'),
        ('B4', 'Self-assessment question', 's37'),
        ('C4', 'Yes/Partial/No', 's37'),
        ('D4', 'Notes', 's37'),
        ('A5', '1. Policy & Governance', 's38'),
        ('B5', 'Written AI policy (allowed/forbidden tools, data, models)? Everyone complies? Prototype separated from production?', 's39'),
        ('C5', None, 's40'),
        ('D5', None, 's39'),
        ('A6', '2. Context cho AI', 's38'),
        ('B6', 'AGENTS.md (stack, conventions, hard rules) versioned & updated when AI errs? AI connected to internal docs/codebase?', 's39'),
        ('C6', None, 's40'),
        ('D6', None, 's39'),
        ('A7', '3. Testing & Eval', 's38'),
        ('B7', 'Write tests/evals BEFORE generating code for important tasks? Pass/fail eval suite for agents? Tests run automatically in CI?', 's39'),
        ('C7', None, 's40'),
        ('D7', None, 's39'),
        ('A8', '4. Review & Humans', 's38'),
        ('B8', 'Every line of AI code human-reviewed before ship? Reviewers know AI-specific failures? Mandatory approval gate?', 's39'),
        ('C8', None, 's40'),
        ('D8', None, 's39'),
        ('A9', '5. Security & Audit', 's38'),
        ('B9', 'Scanning for secrets/PII & prompt-leak protection? AI-generated artifacts traceable + every agent run logged?', 's39'),
        ('C9', None, 's40'),
        ('D9', None, 's39'),
        ('A10', '6. Measurement & Outcomes', 's38'),
        ('B10', 'Baseline (DORA, time, cost) recorded before AI? Quality tracked alongside productivity? Tied to business outcomes?', 's39'),
        ('C10', None, 's40'),
        ('D10', None, 's39'),
        ('A11', None, 's39'),
        ('B11', None, 's39'),
        ('C11', None, 's39'),
        ('A12', 'Phase SDLC', 's37'),
        ('B12', 'Question', 's37'),
        ('C12', "What 'good' looks like", 's37'),
        ('A13', 'Requirements & Planning', 's38'),
        ('B13', 'AI helps generate user stories, find edge cases, build prototypes quickly?', 's39'),
        ('C13', 'From description → prototype in minutes; humans set scope.', 's39'),
        ('A14', 'Design & Architecture', 's38'),
        ('B14', 'Architecture by humans, AI implements per docs?', 's39'),
        ('C14', 'Humans own trade-offs; AI scaffolds per docs.', 's39'),
        ('A15', 'Implementation', 's38'),
        ('B15', 'AI generates code within spec and always reviewed?', 's39'),
        ('C15', 'AI does the repetitive part; humans do the hard 20%.', 's39'),
        ('A16', 'Testing & QA', 's38'),
        ('B16', 'AI generates tests/edge cases, checks output + trajectory?', 's39'),
        ('C16', "Evals encode 'correct' & run automatically in CI.", 's39'),
        ('A17', 'Review & Deployment', 's38'),
        ('B17', 'AI reviews the first pass before humans look?', 's39'),
        ('C17', 'AI is the first reviewer; humans decide design.', 's39'),
        ('A18', 'Maintenance', 's38'),
        ('B18', 'AI helps understand & refactor legacy safely?', 's39'),
        ('C18', "Code once 'too risky' now refactored under control.", 's39'),
    ],
    "validations": [('list', '"Yes,Partial,No"', 'C5:C10')],
}, {
    "name": '8. Dashboard-Project',
    "widths": {'A': 16.0, 'B': 10.0, 'C': 46.0},
    "heights": {1: 19.7, 12: 22.35},
    "data_rows": (21, 32),
    "columns": [
        ('B', '=IF($E$3="","",IFERROR(AVERAGEIFS(\'5. Metrics\'!$D$4:$D$203,\'5. Metrics\'!$A$4:$A$203,$E$3,\'5. Metrics\'!$B$4:$B$203,$A{r}),""))', 's41'),
        ('C', '=IF($E$3="","",IFERROR(AVERAGEIFS(\'5. Metrics\'!$E$4:$E$203,\'5. Metrics\'!$A$4:$A$203,$E$3,\'5. Metrics\'!$B$4:$B$203,$A{r}),""))', 's41'),
        ('D', '=IF($E$3="","",IFERROR(AVERAGEIFS(\'5. Metrics\'!$I$4:$I$203,\'5. Metrics\'!$A$4:$A$203,$E$3,\'5. Metrics\'!$B$4:$B$203,$A{r}),""))', 's41'),
        ('E', '=IF($E$3="","",IFERROR(AVERAGEIFS(\'5. Metrics\'!$L$4:$L$203,\'5. Metrics\'!$A$4:$A$203,$E$3,\'5. Metrics\'!$B$4:$B$203,$A{r}),""))', 's41'),
    ],
    "cells": [
        ('A1', 'PROJECT PROFILE', 's1'),
        ('A3', 'Select project:', 's5'),
        ('B3', 'Platform-Team', 's42'),
        ('D3', 'ProjectID:', 's24'),
        ('E3', '=IFERROR(INDEX(\'2. Projects\'!$A$3:$A$20,MATCH($B$3,\'2. Projects\'!$B$3:$B$20,0)),"")', 's24'),
        ('A4', 'Select quarter:', 's5'),
        ('B4', '2026-Q1', 's42'),
        ('D4', 'Key:', 's24'),
        ('E4', '=IF($E$3="","",$E$3&"|"&$B$4)', 's24'),
        ('A6', 'Dimension', 's13'),
        ('B6', 'Level', 's13'),
        ('C6', 'Evidence', 's13'),
        ('A7', 'A. Adoption', 's43'),
        ('B7', '=IFERROR(INDEX(\'6. Levels\'!$N:$N,MATCH($E$4,\'6. Levels\'!$T:$T,0)),"")', 's14'),
        ('C7', '=IFERROR(INDEX(\'4. Quarterly\'!$AB:$AB,MATCH($E$4,\'4. Quarterly\'!$AH:$AH,0)),"")', 's44'),
        ('A8', 'B. Delivery', 's43'),
        ('B8', '=IFERROR(INDEX(\'6. Levels\'!$O:$O,MATCH($E$4,\'6. Levels\'!$T:$T,0)),"")', 's14'),
        ('C8', '=IFERROR(INDEX(\'4. Quarterly\'!$AC:$AC,MATCH($E$4,\'4. Quarterly\'!$AH:$AH,0)),"")', 's44'),
        ('A9', 'C. Quality', 's43'),
        ('B9', '=IFERROR(INDEX(\'6. Levels\'!$P:$P,MATCH($E$4,\'6. Levels\'!$T:$T,0)),"")', 's14'),
        ('C9', '=IFERROR(INDEX(\'4. Quarterly\'!$AD:$AD,MATCH($E$4,\'4. Quarterly\'!$AH:$AH,0)),"")', 's44'),
        ('A10', 'D. Agent', 's43'),
        ('B10', '=IFERROR(INDEX(\'6. Levels\'!$Q:$Q,MATCH($E$4,\'6. Levels\'!$T:$T,0)),"")', 's14'),
        ('C10', '=IFERROR(INDEX(\'4. Quarterly\'!$AE:$AE,MATCH($E$4,\'4. Quarterly\'!$AH:$AH,0)),"")', 's44'),
        ('A11', 'E. Governance', 's43'),
        ('B11', '=IFERROR(INDEX(\'6. Levels\'!$R:$R,MATCH($E$4,\'6. Levels\'!$T:$T,0)),"")', 's14'),
        ('C11', '=IFERROR(INDEX(\'4. Quarterly\'!$AF:$AF,MATCH($E$4,\'4. Quarterly\'!$AH:$AH,0)),"")', 's44'),
        ('A12', 'OVERALL', 's45'),
        ('B12', '=IFERROR(INDEX(\'6. Levels\'!$S:$S,MATCH($E$4,\'6. Levels\'!$T:$T,0)),"")', 's46'),
        ('C12', '=IFERROR(INDEX(\'4. Quarterly\'!$AG:$AG,MATCH($E$4,\'4. Quarterly\'!$AH:$AH,0)),"")', 's44'),
        ('A19', 'MONTHLY TREND (selected project)', 's47'),
        ('A20', 'Month', 's13'),
        ('B20', 'AI usage %', 's13'),
        ('C20', 'AI PR %', 's13'),
        ('D20', 'CFR %', 's13'),
        ('E20', 'Rework %', 's13'),
        ('A21', ('DATE', 2026, 1, 1), 's48'),
        ('A22', ('DATE', 2026, 2, 1), 's48'),
        ('A23', ('DATE', 2026, 3, 1), 's48'),
        ('A24', ('DATE', 2026, 4, 1), 's48'),
        ('A25', ('DATE', 2026, 5, 1), 's48'),
        ('A26', ('DATE', 2026, 6, 1), 's48'),
        ('A27', ('DATE', 2026, 7, 1), 's48'),
        ('A28', ('DATE', 2026, 8, 1), 's48'),
        ('A29', ('DATE', 2026, 9, 1), 's48'),
        ('A30', ('DATE', 2026, 10, 1), 's48'),
        ('A31', ('DATE', 2026, 11, 1), 's48'),
        ('A32', ('DATE', 2026, 12, 1), 's48'),
    ],
    "validations": [('list', '"2026-Q1,2026-Q2,2026-Q3,2026-Q4"', 'B4')],
    "color_scales": [
        ('B7:B11', [('num', 1.0), ('num', 3.0), ('num', 5.0)], ['FFF8696B', 'FFFFEB84', 'FF63BE7B']),
    ],
}, {
    "name": '9. Dashboard-Portfolio',
    "widths": {'A': 22.0, 'B': 9.0, 'I': 6.0, 'J': 12.0},
    "heights": {1: 19.7},
    "data_rows": (6, 17),
    "columns": [
        ('B', '=IFERROR(INDEX(\'6. Levels\'!$N:$N,MATCH($J{r},\'6. Levels\'!$T:$T,0)),"")', 's14'),
        ('C', '=IFERROR(INDEX(\'6. Levels\'!$O:$O,MATCH($J{r},\'6. Levels\'!$T:$T,0)),"")', 's14'),
        ('D', '=IFERROR(INDEX(\'6. Levels\'!$P:$P,MATCH($J{r},\'6. Levels\'!$T:$T,0)),"")', 's14'),
        ('E', '=IFERROR(INDEX(\'6. Levels\'!$Q:$Q,MATCH($J{r},\'6. Levels\'!$T:$T,0)),"")', 's14'),
        ('F', '=IFERROR(INDEX(\'6. Levels\'!$R:$R,MATCH($J{r},\'6. Levels\'!$T:$T,0)),"")', 's14'),
        ('G', '=IFERROR(INDEX(\'6. Levels\'!$S:$S,MATCH($J{r},\'6. Levels\'!$T:$T,0)),"")', 's14'),
        ('J', '=IF($I{r}="","",$I{r}&"|"&$B$3)', 's24'),
    ],
    "cells": [
        ('A1', 'PORTFOLIO — all projects by quarter', 's1'),
        ('A3', 'Select quarter:', 's5'),
        ('B3', '2026-Q1', 's42'),
        ('A5', 'Project', 's13'),
        ('B5', 'A', 's13'),
        ('C5', 'B', 's13'),
        ('D5', 'C', 's13'),
        ('E5', 'D', 's13'),
        ('F5', 'E', 's13'),
        ('G5', 'OVERALL', 's13'),
        ('A6', '=IFERROR(\'2. Projects\'!$B$3,"")', 's49'),
        ('I6', '=IFERROR(\'2. Projects\'!$A$3,"")', 's24'),
        ('A7', '=IFERROR(\'2. Projects\'!$B$4,"")', 's49'),
        ('I7', '=IFERROR(\'2. Projects\'!$A$4,"")', 's24'),
        ('A8', '=IFERROR(\'2. Projects\'!$B$5,"")', 's49'),
        ('I8', '=IFERROR(\'2. Projects\'!$A$5,"")', 's24'),
        ('A9', '=IFERROR(\'2. Projects\'!$B$6,"")', 's49'),
        ('I9', '=IFERROR(\'2. Projects\'!$A$6,"")', 's24'),
        ('A10', '=IFERROR(\'2. Projects\'!$B$7,"")', 's49'),
        ('I10', '=IFERROR(\'2. Projects\'!$A$7,"")', 's24'),
        ('A11', '=IFERROR(\'2. Projects\'!$B$8,"")', 's49'),
        ('I11', '=IFERROR(\'2. Projects\'!$A$8,"")', 's24'),
        ('A12', '=IFERROR(\'2. Projects\'!$B$9,"")', 's49'),
        ('I12', '=IFERROR(\'2. Projects\'!$A$9,"")', 's24'),
        ('A13', '=IFERROR(\'2. Projects\'!$B$10,"")', 's49'),
        ('I13', '=IFERROR(\'2. Projects\'!$A$10,"")', 's24'),
        ('A14', '=IFERROR(\'2. Projects\'!$B$11,"")', 's49'),
        ('I14', '=IFERROR(\'2. Projects\'!$A$11,"")', 's24'),
        ('A15', '=IFERROR(\'2. Projects\'!$B$12,"")', 's49'),
        ('I15', '=IFERROR(\'2. Projects\'!$A$12,"")', 's24'),
        ('A16', '=IFERROR(\'2. Projects\'!$B$13,"")', 's49'),
        ('I16', '=IFERROR(\'2. Projects\'!$A$13,"")', 's24'),
        ('A17', '=IFERROR(\'2. Projects\'!$B$14,"")', 's49'),
        ('I17', '=IFERROR(\'2. Projects\'!$A$14,"")', 's24'),
    ],
    "validations": [('list', '"2026-Q1,2026-Q2,2026-Q3,2026-Q4"', 'B3')],
    "color_scales": [
        ('B6:G17', [('num', 1.0), ('num', 3.0), ('num', 5.0)], ['FFF8696B', 'FFFFEB84', 'FF63BE7B']),
    ],
}]
