import type { CountryFieldConfig } from '../../domain/entities/country-field-config.entity'

export const SINGAPORE_COUNTRY_FIELDS: Omit<CountryFieldConfig, 'id' | 'tenantId'>[] = [
  {
    countryCode: 'SG',
    fieldKey: 'nric_fin',
    label: 'NRIC/FIN',
    labelLocale: { en: 'NRIC/FIN' },
    fieldType: 'text',
    fieldGroup: 'identity',
    isRequired: true,
    sortOrder: 1,
    validation: { regex: '^[STFGM]\\d{7}[A-Z]$' },
    options: null,
  },
  {
    countryCode: 'SG',
    fieldKey: 'race',
    label: 'Race',
    labelLocale: { en: 'Race' },
    fieldType: 'select',
    fieldGroup: 'identity',
    isRequired: true,
    sortOrder: 2,
    validation: null,
    options: [
      { value: 'chinese', label: 'Chinese' },
      { value: 'malay', label: 'Malay' },
      { value: 'indian', label: 'Indian' },
      { value: 'eurasian', label: 'Eurasian' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    countryCode: 'SG',
    fieldKey: 'cpf_account_number',
    label: 'CPF Account Number',
    labelLocale: { en: 'CPF Account Number' },
    fieldType: 'text',
    fieldGroup: 'social_insurance',
    isRequired: false,
    sortOrder: 3,
    validation: null,
    options: null,
  },
  {
    countryCode: 'SG',
    fieldKey: 'work_pass_type',
    label: 'Work Pass Type',
    labelLocale: { en: 'Work Pass Type' },
    fieldType: 'select',
    fieldGroup: 'identity',
    isRequired: false,
    sortOrder: 4,
    validation: null,
    options: [
      { value: 'ep', label: 'Employment Pass' },
      { value: 'sp', label: 'S Pass' },
      { value: 'wp', label: 'Work Permit' },
      { value: 'dp', label: 'Dependant Pass' },
      { value: 'ltvp', label: 'Long Term Visit Pass' },
      { value: 'citizen', label: 'Citizen / PR' },
    ],
  },
  {
    countryCode: 'SG',
    fieldKey: 'work_pass_expiry',
    label: 'Work Pass Expiry Date',
    labelLocale: { en: 'Work Pass Expiry Date' },
    fieldType: 'date',
    fieldGroup: 'identity',
    isRequired: false,
    sortOrder: 5,
    validation: null,
    options: null,
  },
]
