import type { DocumentRequirement } from '../../domain/entities/document-requirement.entity'

export const VIETNAM_DOCUMENT_REQUIREMENTS: Omit<DocumentRequirement, 'id' | 'tenantId'>[] = [
  {
    countryCode: 'VN',
    employmentType: null,
    category: 'identity',
    title: 'Citizen ID Card (CCCD)',
    isRequired: true,
    deadlineDays: 7,
    sortOrder: 1,
  },
  {
    countryCode: 'VN',
    employmentType: null,
    category: 'identity',
    title: 'Household Registration (Ho Khau)',
    isRequired: false,
    deadlineDays: 30,
    sortOrder: 2,
  },
  {
    countryCode: 'VN',
    employmentType: null,
    category: 'tax',
    title: 'Tax Code Certificate',
    isRequired: true,
    deadlineDays: 30,
    sortOrder: 3,
  },
  {
    countryCode: 'VN',
    employmentType: null,
    category: 'insurance',
    title: 'Social Insurance Book',
    isRequired: true,
    deadlineDays: 30,
    sortOrder: 4,
  },
  {
    countryCode: 'VN',
    employmentType: null,
    category: 'health_check',
    title: 'Health Check Certificate',
    isRequired: true,
    deadlineDays: 14,
    sortOrder: 5,
  },
  {
    countryCode: 'VN',
    employmentType: null,
    category: 'certificate',
    title: 'Degree / Diploma',
    isRequired: false,
    deadlineDays: 30,
    sortOrder: 6,
  },
  {
    countryCode: 'VN',
    employmentType: null,
    category: 'identity',
    title: 'Portrait Photos (4x6)',
    isRequired: true,
    deadlineDays: 7,
    sortOrder: 7,
  },
  {
    countryCode: 'VN',
    employmentType: 'permanent',
    category: 'contract',
    title: 'Probation Contract',
    isRequired: true,
    deadlineDays: 3,
    sortOrder: 8,
  },
  {
    countryCode: 'VN',
    employmentType: 'permanent',
    category: 'contract',
    title: 'Labor Contract',
    isRequired: true,
    deadlineDays: null,
    sortOrder: 9,
  },
]
