import type { CountryFieldConfig } from '../../domain/entities/country-field-config.entity'

export const VIETNAM_COUNTRY_FIELDS: Omit<CountryFieldConfig, 'id'>[] = [
  {
    countryCode: 'VN',
    fieldKey: 'citizen_id',
    label: 'Citizen ID',
    labelLocale: { vi: 'Số CCCD', en: 'Citizen ID' },
    fieldType: 'text',
    fieldGroup: 'identity',
    isRequired: true,
    sortOrder: 1,
    validation: { regex: '^\\d{12}$' },
    options: null,
  },
  {
    countryCode: 'VN',
    fieldKey: 'legacy_citizen_id',
    label: 'Legacy Citizen ID',
    labelLocale: { vi: 'Số CMND', en: 'Legacy Citizen ID' },
    fieldType: 'text',
    fieldGroup: 'identity',
    isRequired: false,
    sortOrder: 2,
    validation: { regex: '^\\d{9}$' },
    options: null,
  },
  {
    countryCode: 'VN',
    fieldKey: 'citizen_id_issue_place',
    label: 'Citizen ID Issue Place',
    labelLocale: { vi: 'Nơi cấp CCCD', en: 'Citizen ID Issue Place' },
    fieldType: 'text',
    fieldGroup: 'identity',
    isRequired: false,
    sortOrder: 3,
    validation: null,
    options: null,
  },
  {
    countryCode: 'VN',
    fieldKey: 'registered_address',
    label: 'Permanent Registration Address',
    labelLocale: { vi: 'Địa chỉ hộ khẩu', en: 'Permanent Registration Address' },
    fieldType: 'text',
    fieldGroup: 'identity',
    isRequired: false,
    sortOrder: 4,
    validation: null,
    options: null,
  },
  {
    countryCode: 'VN',
    fieldKey: 'vehicle_plate',
    label: 'Vehicle Plate',
    labelLocale: { vi: 'Biển số xe', en: 'Vehicle Plate' },
    fieldType: 'text',
    fieldGroup: 'vehicle',
    isRequired: false,
    sortOrder: 5,
    validation: null,
    options: null,
  },
  {
    countryCode: 'VN',
    fieldKey: 'vehicle_type',
    label: 'Vehicle Type',
    labelLocale: { vi: 'Loại xe', en: 'Vehicle Type' },
    fieldType: 'select',
    fieldGroup: 'vehicle',
    isRequired: false,
    sortOrder: 6,
    validation: null,
    options: [
      { value: 'motorbike', label: 'Motorbike' },
      { value: 'car', label: 'Car' },
      { value: 'bicycle', label: 'Bicycle' },
    ],
  },
]
