export const MS_SYNC_BACKFILL_JOB = 'ms-sync-backfill-group'
export const MS_SYNC_BACKFILL_ROSTER_JOB = 'ms-sync-backfill-roster'
export const MS_SYNC_PUSH_TASK_JOB = 'ms-sync-push-task'
export const MS_SYNC_PUSH_PLAN_JOB = 'ms-sync-push-plan'
export const MS_SYNC_PUSH_BUCKET_JOB = 'ms-sync-push-bucket'
export const MS_SYNC_PUSH_ATTACHMENT_JOB = 'ms-sync-push-attachment'
export const MS_SYNC_PULL_ATTACHMENT_JOB = 'ms-sync-pull-attachment'
