/**
 * append-rls.ts — Post-generation script that appends RLS DDL to 0000_initial.sql.
 *
 * Run this immediately after `drizzle-kit generate`. It adds:
 *   1. ENABLE/FORCE ROW LEVEL SECURITY on every tenant-scoped agents.* table
 *   2. ENABLE/FORCE ROW LEVEL SECURITY on core.agent_delegation
 *   3. A tenant_isolation policy on each of those tables
 *
 * Drizzle ORM does not support RLS natively, so this script is the single
 * authoritative source for RLS DDL. It is idempotent: running it twice on the
 * same file appends the block again, but migrations are always regenerated from
 * scratch (delete + generate), so double-append cannot happen in normal usage.
 *
 * Usage:
 *   bun run packages/db/src/append-rls.ts
 */

import fs from 'node:fs'
import path from 'node:path'

const MIGRATIONS_DIR = path.join(__dirname, '../drizzle/migrations')

/**
 * Find the single .sql file in the migrations directory.
 * During the squash procedure there should be exactly one file.
 */
function findMigrationFile(): string {
  const files = fs
    .readdirSync(MIGRATIONS_DIR)
    .filter((f) => f.endsWith('.sql'))
    .map((f) => path.join(MIGRATIONS_DIR, f))

  if (files.length === 0) {
    console.error(`[rls] ERROR: No .sql files found in ${MIGRATIONS_DIR} — run db:generate first`)
    process.exit(1)
  }
  if (files.length > 1) {
    console.error(
      `[rls] ERROR: Multiple .sql files found — expected exactly one (squash procedure):`,
      files,
    )
    process.exit(1)
  }
  return files[0]!
}

// ─── Tables that need RLS ─────────────────────────────────────────────────────
// Every agents.* table with a tenant_id column, plus core.agent_delegation.
// Exclusions (no tenant_id or documented exception):
//   agent_pricing          — global catalog, no tenant_id
//   agent_tool_embedding   — platform-authored vectors, documented exception (plan 02.5 §3)
//   agent_readiness_check  — platform-level singleton, no tenant_id
//   agent_ga_readiness_state — platform-level singleton, no tenant_id
//   agent_cost_reconciliation — platform-level aggregate, no tenant_id
//   agent_scorer_registration — no tenant_id

const AGENTS_TABLES = [
  'agent_chat_session',
  'agent_chat_message',
  'agent_insight',
  'agent_prompt_store',
  'agent_narrative_store',
  'agent_session',
  'agent_stored_sub_agent',
  'agent_conversation',
  'agent_message',
  'agent_l3_preference',
  'agent_scratchpad',
  'agent_tool_invocation',
  'agent_turn_sampling_decision',
  'agent_cost_event',
  'agent_tenant_budget',
  'agent_user_budget',
  'agent_rate_limit_counter',
  'agent_active_turn',
  'agent_golden_trace',
  'agent_canary_run',
  'agent_canary_query',
  'agent_rollout_config',
  'agent_rollout_event',
  'agent_shadow_run',
  'agent_tool_result_cache',
  'agent_draft',
  'agent_iteration',
  'agent_schedule',
  'agent_schedule_run',
  'agent_runbook_dry_run',
  'agent_p1_incident_log',
] as const

// core schema tables that also need RLS
const CORE_TABLES = ['agent_delegation'] as const

// ─── DDL generator ────────────────────────────────────────────────────────────

function rlsDdl(schema: string, table: string): string {
  const fqn = `${schema}.${table}`
  const policyName = `${table}_tenant_isolation`
  return [
    `ALTER TABLE ${fqn} ENABLE ROW LEVEL SECURITY;`,
    `ALTER TABLE ${fqn} FORCE ROW LEVEL SECURITY;`,
    `CREATE POLICY ${policyName}`,
    `  ON ${fqn}`,
    `  USING (tenant_id = current_setting('app.tenant_id')::uuid)`,
    `  WITH CHECK (tenant_id = current_setting('app.tenant_id')::uuid);`,
  ].join('\n')
}

// ─── Main ─────────────────────────────────────────────────────────────────────

function main(): void {
  const migrationFile = findMigrationFile()

  const blocks: string[] = [
    '',
    '-- ─── RLS: Row Level Security on all tenant-scoped tables ──────────────────────',
    '-- Generated by packages/db/src/append-rls.ts — do not edit manually.',
    '',
  ]

  for (const table of AGENTS_TABLES) {
    blocks.push(`-- agents.${table}`)
    blocks.push(rlsDdl('agents', table))
    blocks.push('')
  }

  for (const table of CORE_TABLES) {
    blocks.push(`-- core.${table}`)
    blocks.push(rlsDdl('core', table))
    blocks.push('')
  }

  const rls = blocks.join('\n')

  fs.appendFileSync(migrationFile, rls, 'utf8')

  // Rename to 0000_initial.sql per CLAUDE.md convention (one file, one name)
  const initialPath = path.join(MIGRATIONS_DIR, '0000_initial.sql')
  if (migrationFile !== initialPath) {
    fs.renameSync(migrationFile, initialPath)
    // Also update the meta journal to reflect the rename
    const journalPath = path.join(MIGRATIONS_DIR, 'meta', '_journal.json')
    if (fs.existsSync(journalPath)) {
      const journal = JSON.parse(fs.readFileSync(journalPath, 'utf8')) as {
        entries: Array<{ tag: string; when: number; breakpoints: boolean }>
      }
      for (const entry of journal.entries) {
        const basename = path.basename(migrationFile, '.sql')
        if (entry.tag === basename) {
          entry.tag = '0000_initial'
        }
      }
      fs.writeFileSync(journalPath, JSON.stringify(journal, null, 2) + '\n', 'utf8')
    }
    // Rename the snapshot file too
    const snapshotBase = path.basename(migrationFile, '.sql')
    const oldSnapshot = path.join(MIGRATIONS_DIR, 'meta', `${snapshotBase}_snapshot.json`)
    const newSnapshot = path.join(MIGRATIONS_DIR, 'meta', '0000_initial_snapshot.json')
    if (fs.existsSync(oldSnapshot) && oldSnapshot !== newSnapshot) {
      fs.renameSync(oldSnapshot, newSnapshot)
    }
  }

  console.log(
    `[rls] Appended RLS DDL for ${AGENTS_TABLES.length} agents tables + ${CORE_TABLES.length} core tables to ${path.join(MIGRATIONS_DIR, '0000_initial.sql')}`,
  )
}

main()
