/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoWorkspaceRouteImport } from './routes/no-workspace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SuperadminRouteImport } from './routes/_superadmin'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as SuperadminAdminRouteImport } from './routes/_superadmin/admin'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedMembersRouteImport } from './routes/_authed/members'
import { Route as AuthedConnectorsRouteImport } from './routes/_authed/connectors'
import { Route as LoginProviderCallbackRouteImport } from './routes/login.$provider.callback'
import { Route as SuperadminAdminTenantsRouteImport } from './routes/_superadmin/admin/tenants'
import { Route as AuthedConnectorsCidConsentRouteImport } from './routes/_authed/connectors.$cid.consent'
import { Route as SuperadminAdminTenantsTenantIdSsoRouteImport } from './routes/_superadmin/admin/tenants.$tenantId.sso'
import { Route as SuperadminAdminTenantsTenantIdSsoDomainsRouteImport } from './routes/_superadmin/admin/tenants.$tenantId.sso.domains'

const NoWorkspaceRoute = NoWorkspaceRouteImport.update({
  id: '/no-workspace',
  path: '/no-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/_superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const SuperadminAdminRoute = SuperadminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => SuperadminRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembersRoute = AuthedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConnectorsRoute = AuthedConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AuthedRoute,
} as any)
const LoginProviderCallbackRoute = LoginProviderCallbackRouteImport.update({
  id: '/$provider/callback',
  path: '/$provider/callback',
  getParentRoute: () => LoginRoute,
} as any)
const SuperadminAdminTenantsRoute = SuperadminAdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => SuperadminAdminRoute,
} as any)
const AuthedConnectorsCidConsentRoute =
  AuthedConnectorsCidConsentRouteImport.update({
    id: '/$cid/consent',
    path: '/$cid/consent',
    getParentRoute: () => AuthedConnectorsRoute,
  } as any)
const SuperadminAdminTenantsTenantIdSsoRoute =
  SuperadminAdminTenantsTenantIdSsoRouteImport.update({
    id: '/$tenantId/sso',
    path: '/$tenantId/sso',
    getParentRoute: () => SuperadminAdminTenantsRoute,
  } as any)
const SuperadminAdminTenantsTenantIdSsoDomainsRoute =
  SuperadminAdminTenantsTenantIdSsoDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => SuperadminAdminTenantsTenantIdSsoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRouteWithChildren
  '/no-workspace': typeof NoWorkspaceRoute
  '/connectors': typeof AuthedConnectorsRouteWithChildren
  '/members': typeof AuthedMembersRoute
  '/profile': typeof AuthedProfileRoute
  '/admin': typeof SuperadminAdminRouteWithChildren
  '/admin/tenants': typeof SuperadminAdminTenantsRouteWithChildren
  '/login/$provider/callback': typeof LoginProviderCallbackRoute
  '/connectors/$cid/consent': typeof AuthedConnectorsCidConsentRoute
  '/admin/tenants/$tenantId/sso': typeof SuperadminAdminTenantsTenantIdSsoRouteWithChildren
  '/admin/tenants/$tenantId/sso/domains': typeof SuperadminAdminTenantsTenantIdSsoDomainsRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRouteWithChildren
  '/no-workspace': typeof NoWorkspaceRoute
  '/connectors': typeof AuthedConnectorsRouteWithChildren
  '/members': typeof AuthedMembersRoute
  '/profile': typeof AuthedProfileRoute
  '/admin': typeof SuperadminAdminRouteWithChildren
  '/admin/tenants': typeof SuperadminAdminTenantsRouteWithChildren
  '/login/$provider/callback': typeof LoginProviderCallbackRoute
  '/connectors/$cid/consent': typeof AuthedConnectorsCidConsentRoute
  '/admin/tenants/$tenantId/sso': typeof SuperadminAdminTenantsTenantIdSsoRouteWithChildren
  '/admin/tenants/$tenantId/sso/domains': typeof SuperadminAdminTenantsTenantIdSsoDomainsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_superadmin': typeof SuperadminRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/no-workspace': typeof NoWorkspaceRoute
  '/_authed/connectors': typeof AuthedConnectorsRouteWithChildren
  '/_authed/members': typeof AuthedMembersRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_superadmin/admin': typeof SuperadminAdminRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/_superadmin/admin/tenants': typeof SuperadminAdminTenantsRouteWithChildren
  '/login/$provider/callback': typeof LoginProviderCallbackRoute
  '/_authed/connectors/$cid/consent': typeof AuthedConnectorsCidConsentRoute
  '/_superadmin/admin/tenants/$tenantId/sso': typeof SuperadminAdminTenantsTenantIdSsoRouteWithChildren
  '/_superadmin/admin/tenants/$tenantId/sso/domains': typeof SuperadminAdminTenantsTenantIdSsoDomainsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/no-workspace'
    | '/connectors'
    | '/members'
    | '/profile'
    | '/admin'
    | '/admin/tenants'
    | '/login/$provider/callback'
    | '/connectors/$cid/consent'
    | '/admin/tenants/$tenantId/sso'
    | '/admin/tenants/$tenantId/sso/domains'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/no-workspace'
    | '/connectors'
    | '/members'
    | '/profile'
    | '/admin'
    | '/admin/tenants'
    | '/login/$provider/callback'
    | '/connectors/$cid/consent'
    | '/admin/tenants/$tenantId/sso'
    | '/admin/tenants/$tenantId/sso/domains'
  id:
    | '__root__'
    | '/_authed'
    | '/_superadmin'
    | '/login'
    | '/no-workspace'
    | '/_authed/connectors'
    | '/_authed/members'
    | '/_authed/profile'
    | '/_superadmin/admin'
    | '/_authed/'
    | '/_superadmin/admin/tenants'
    | '/login/$provider/callback'
    | '/_authed/connectors/$cid/consent'
    | '/_superadmin/admin/tenants/$tenantId/sso'
    | '/_superadmin/admin/tenants/$tenantId/sso/domains'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SuperadminRoute: typeof SuperadminRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  NoWorkspaceRoute: typeof NoWorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/no-workspace': {
      id: '/no-workspace'
      path: '/no-workspace'
      fullPath: '/no-workspace'
      preLoaderRoute: typeof NoWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_superadmin': {
      id: '/_superadmin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_superadmin/admin': {
      id: '/_superadmin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof SuperadminAdminRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/members': {
      id: '/_authed/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthedMembersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/connectors': {
      id: '/_authed/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof AuthedConnectorsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/login/$provider/callback': {
      id: '/login/$provider/callback'
      path: '/$provider/callback'
      fullPath: '/login/$provider/callback'
      preLoaderRoute: typeof LoginProviderCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_superadmin/admin/tenants': {
      id: '/_superadmin/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof SuperadminAdminTenantsRouteImport
      parentRoute: typeof SuperadminAdminRoute
    }
    '/_authed/connectors/$cid/consent': {
      id: '/_authed/connectors/$cid/consent'
      path: '/$cid/consent'
      fullPath: '/connectors/$cid/consent'
      preLoaderRoute: typeof AuthedConnectorsCidConsentRouteImport
      parentRoute: typeof AuthedConnectorsRoute
    }
    '/_superadmin/admin/tenants/$tenantId/sso': {
      id: '/_superadmin/admin/tenants/$tenantId/sso'
      path: '/$tenantId/sso'
      fullPath: '/admin/tenants/$tenantId/sso'
      preLoaderRoute: typeof SuperadminAdminTenantsTenantIdSsoRouteImport
      parentRoute: typeof SuperadminAdminTenantsRoute
    }
    '/_superadmin/admin/tenants/$tenantId/sso/domains': {
      id: '/_superadmin/admin/tenants/$tenantId/sso/domains'
      path: '/domains'
      fullPath: '/admin/tenants/$tenantId/sso/domains'
      preLoaderRoute: typeof SuperadminAdminTenantsTenantIdSsoDomainsRouteImport
      parentRoute: typeof SuperadminAdminTenantsTenantIdSsoRoute
    }
  }
}

interface AuthedConnectorsRouteChildren {
  AuthedConnectorsCidConsentRoute: typeof AuthedConnectorsCidConsentRoute
}

const AuthedConnectorsRouteChildren: AuthedConnectorsRouteChildren = {
  AuthedConnectorsCidConsentRoute: AuthedConnectorsCidConsentRoute,
}

const AuthedConnectorsRouteWithChildren =
  AuthedConnectorsRoute._addFileChildren(AuthedConnectorsRouteChildren)

interface AuthedRouteChildren {
  AuthedConnectorsRoute: typeof AuthedConnectorsRouteWithChildren
  AuthedMembersRoute: typeof AuthedMembersRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedConnectorsRoute: AuthedConnectorsRouteWithChildren,
  AuthedMembersRoute: AuthedMembersRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface SuperadminAdminTenantsTenantIdSsoRouteChildren {
  SuperadminAdminTenantsTenantIdSsoDomainsRoute: typeof SuperadminAdminTenantsTenantIdSsoDomainsRoute
}

const SuperadminAdminTenantsTenantIdSsoRouteChildren: SuperadminAdminTenantsTenantIdSsoRouteChildren =
  {
    SuperadminAdminTenantsTenantIdSsoDomainsRoute:
      SuperadminAdminTenantsTenantIdSsoDomainsRoute,
  }

const SuperadminAdminTenantsTenantIdSsoRouteWithChildren =
  SuperadminAdminTenantsTenantIdSsoRoute._addFileChildren(
    SuperadminAdminTenantsTenantIdSsoRouteChildren,
  )

interface SuperadminAdminTenantsRouteChildren {
  SuperadminAdminTenantsTenantIdSsoRoute: typeof SuperadminAdminTenantsTenantIdSsoRouteWithChildren
}

const SuperadminAdminTenantsRouteChildren: SuperadminAdminTenantsRouteChildren =
  {
    SuperadminAdminTenantsTenantIdSsoRoute:
      SuperadminAdminTenantsTenantIdSsoRouteWithChildren,
  }

const SuperadminAdminTenantsRouteWithChildren =
  SuperadminAdminTenantsRoute._addFileChildren(
    SuperadminAdminTenantsRouteChildren,
  )

interface SuperadminAdminRouteChildren {
  SuperadminAdminTenantsRoute: typeof SuperadminAdminTenantsRouteWithChildren
}

const SuperadminAdminRouteChildren: SuperadminAdminRouteChildren = {
  SuperadminAdminTenantsRoute: SuperadminAdminTenantsRouteWithChildren,
}

const SuperadminAdminRouteWithChildren = SuperadminAdminRoute._addFileChildren(
  SuperadminAdminRouteChildren,
)

interface SuperadminRouteChildren {
  SuperadminAdminRoute: typeof SuperadminAdminRouteWithChildren
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminAdminRoute: SuperadminAdminRouteWithChildren,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

interface LoginRouteChildren {
  LoginProviderCallbackRoute: typeof LoginProviderCallbackRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginProviderCallbackRoute: LoginProviderCallbackRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SuperadminRoute: SuperadminRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  NoWorkspaceRoute: NoWorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
