import type { Bucket, LeaveEntry, Plan, PlanMember, Task, User } from './types.js'

export const NAMED_USERS: readonly User[] = [
  {
    user_id: 'u001',
    name: 'Trần Văn Hùng',
    email: 'hung.tranvan@setafuture.onmicrosoft.com',
    project: 'SETA Internal',
    role: 'CTO',
    rbac_role: 'org.admin',
    skills: 'AWS,System Design,DevOps,Engineering Leadership',
  },
  {
    user_id: 'u002',
    name: 'Nguyễn Văn Nam',
    email: 'nam.nguyenvan@setafuture.onmicrosoft.com',
    project: 'SETA Internal',
    role: 'IT Engineer',
    rbac_role: 'planner.contributor',
    skills: 'AWS,Kubernetes,Terraform,Linux,Monitoring,Security',
  },
  {
    user_id: 'u003',
    name: 'Lê Thị Hoa',
    email: 'hoa.lethi@setafuture.onmicrosoft.com',
    project: 'SETA Internal',
    role: 'IT Engineer',
    rbac_role: 'planner.contributor',
    skills: 'AWS,Kubernetes,Linux,Docker',
  },
  {
    user_id: 'u004',
    name: 'Phạm Quốc Bảo',
    email: 'bao.phamquoc@setafuture.onmicrosoft.com',
    project: 'Client Atlas',
    role: 'Backend Developer',
    rbac_role: 'planner.contributor',
    skills: 'Node.js,PostgreSQL,Docker,Kafka',
  },
  {
    user_id: 'u005',
    name: 'Vũ Minh Tuấn',
    email: 'tuan.vuminh@setafuture.onmicrosoft.com',
    project: 'SETA Internal',
    role: 'Backend Developer',
    rbac_role: 'planner.contributor',
    skills: 'AWS,Docker,Linux,PostgreSQL',
  },
  {
    user_id: 'u007',
    name: 'Vũ Bích Ngọc',
    email: 'ngoc.vubich@setafuture.onmicrosoft.com',
    project: 'SETA Internal',
    role: 'IT Support',
    rbac_role: 'planner.viewer',
    skills: 'AWS,Linux,Docker',
  },
  {
    user_id: 'u008',
    name: 'Bùi Trung Hiếu',
    email: 'hieu.buitrung@setafuture.onmicrosoft.com',
    project: 'Client Beta',
    role: 'IT Engineer',
    rbac_role: 'planner.contributor',
    skills: 'AWS,Kubernetes,Terraform,Security',
  },
  {
    user_id: 'u009',
    name: 'Đỗ Mỹ Linh',
    email: 'linh.domy@setafuture.onmicrosoft.com',
    project: 'SETA Internal',
    role: 'PM',
    rbac_role: 'planner.contributor',
    skills: '',
  },
  {
    user_id: 'u010',
    name: 'Bùi Hoàng Long',
    email: 'long.buihoang@setafuture.onmicrosoft.com',
    project: 'SETA Internal',
    role: 'IT Engineer',
    rbac_role: 'planner.contributor',
    skills: 'AWS,Kubernetes,Linux,Docker',
  },
  {
    user_id: 'u011',
    name: 'Trần Hồng Anh',
    email: 'anh.tranhong@setafuture.onmicrosoft.com',
    project: 'SETA Internal',
    role: 'IT Engineer',
    rbac_role: 'planner.contributor',
    skills: 'Linux,Monitoring,Docker',
  },
  {
    user_id: 'u012',
    name: 'Lê Quang Vinh',
    email: 'vinh.lequang@setafuture.onmicrosoft.com',
    project: '',
    role: 'Junior Developer',
    rbac_role: 'planner.contributor',
    skills: 'JavaScript,HTML,CSS',
  },
  {
    user_id: 'u013',
    name: 'Đinh Thanh Mai',
    email: 'mai.dinhthanh@setafuture.onmicrosoft.com',
    project: 'SETA Internal',
    role: '',
    rbac_role: 'planner.viewer',
    skills: 'DevOps,AI',
  },
  {
    user_id: 'u014',
    name: 'Phạm Lan Anh',
    email: 'anh.phamlan@setafuture.onmicrosoft.com',
    project: 'Client Atlas',
    role: 'Data Scientist',
    rbac_role: 'planner.contributor',
    skills: 'ML,NLP,Spark,Kafka',
  },
  {
    user_id: 'u015',
    name: 'Lý Minh Hoàng',
    email: 'hoang.lyminh@setafuture.onmicrosoft.com',
    project: 'SETA Internal',
    role: 'Software Engineer',
    rbac_role: 'planner.contributor',
    skills: 'k8s,ts,postgres,OOP',
  },
]

export const NAMED_PLANS: readonly Plan[] = [
  {
    plan_id: 'p001',
    title: 'Infrastructure Review Q2 2026',
    description:
      'Quarterly infrastructure audit covering AWS spend, Kubernetes posture, and Terraform debt.',
    tags: 'infrastructure,cloud,review',
    owner: 'u001',
  },
  {
    plan_id: 'p002',
    title: 'Frontend Modernization',
    description: 'Move design system and shell to the new tokens-based stack.',
    tags: 'frontend,react',
    owner: 'u001',
  },
  {
    plan_id: 'p003',
    title: 'DevOps Standalone Project',
    description: 'Single-engineer infra spike covering Terraform bootstrap and CI hardening.',
    tags: 'infrastructure,devops',
    owner: 'u010',
  },
  {
    plan_id: 'p004',
    title: 'Backend Cleanup Sprint',
    description: '',
    tags: '',
    owner: 'u004',
  },
  {
    plan_id: 'p005',
    title: 'AI Platform R&D',
    description: 'Build internal AI experimentation platform with Spark + ML pipelines.',
    tags: 'ai,ml,spark',
    owner: 'u013',
  },
  {
    plan_id: 'p006',
    title: 'Orphan Plan',
    description: '',
    tags: '',
    owner: 'u013',
  },
]

export const NAMED_PLAN_MEMBERS: readonly PlanMember[] = [
  { plan_id: 'p001', member_id: 'u001' },
  { plan_id: 'p001', member_id: 'u002' },
  { plan_id: 'p001', member_id: 'u003' },
  { plan_id: 'p001', member_id: 'u004' },
  { plan_id: 'p001', member_id: 'u005' },
  { plan_id: 'p001', member_id: 'u007' },
  { plan_id: 'p001', member_id: 'u009' },
  { plan_id: 'p001', member_id: 'u011' },
  { plan_id: 'p001', member_id: 'u015' },
  { plan_id: 'p003', member_id: 'u010' },
  { plan_id: 'p004', member_id: 'u004' },
  { plan_id: 'p004', member_id: 'u012' },
  { plan_id: 'p005', member_id: 'u013' },
  { plan_id: 'p005', member_id: 'u014' },
]

export const NAMED_BUCKETS: readonly Bucket[] = [
  { bucket_id: 'b001', plan_id: 'p001', name: 'To Do' },
  { bucket_id: 'b002', plan_id: 'p001', name: 'In Progress' },
  { bucket_id: 'b003', plan_id: 'p002', name: 'To Do' },
  { bucket_id: 'b004', plan_id: 'p001', name: 'Done' },
  { bucket_id: 'b005', plan_id: 'p003', name: 'To Do' },
  { bucket_id: 'b006', plan_id: 'p003', name: 'Done' },
  { bucket_id: 'b007', plan_id: 'p004', name: 'To Do' },
  { bucket_id: 'b008', plan_id: 'p004', name: 'Done' },
  { bucket_id: 'b009', plan_id: 'p005', name: 'To Do' },
  { bucket_id: 'b010', plan_id: 'p005', name: 'Done' },
  { bucket_id: 'b011', plan_id: 'p006', name: 'To Do' },
  { bucket_id: 'b012', plan_id: 'p006', name: 'Done' },
]

const EMPTY_TASK_EXTRAS: Pick<Task, 'checklist' | 'comments' | 'attachments'> = {
  checklist: [],
  comments: [],
  attachments: [],
}

export const NAMED_TASKS: readonly Task[] = [
  {
    task_id: 't001',
    plan_id: 'p001',
    bucket_id: 'b001',
    assignee_ids: '',
    title: 'Review AWS infrastructure architecture and resource allocation',
    description:
      'Walk through the current AWS spend report and propose three architectural changes that reduce monthly cost without hurting reliability.',
    status: 'todo',
    priority: 1,
    due_date: '2026-06-02',
    tags: 'infrastructure,aws,cost,review',
    ...EMPTY_TASK_EXTRAS,
  },
  {
    task_id: 't002',
    plan_id: 'p001',
    bucket_id: 'b001',
    assignee_ids: 'u003',
    title: 'Audit Kubernetes cluster security and RBAC policies',
    description:
      'Inventory cluster roles, identify over-privileged service accounts, and write up findings against CIS benchmarks.',
    status: 'todo',
    priority: 3,
    due_date: '2026-06-15',
    tags: 'infrastructure,kubernetes,security,review',
    ...EMPTY_TASK_EXTRAS,
  },
  {
    task_id: 't003',
    plan_id: 'p001',
    bucket_id: 'b001',
    assignee_ids: '',
    title: 'Plan Q3 capacity model',
    description:
      'Model expected traffic for Q3 and draft a capacity proposal covering Kubernetes nodes and database read replicas.',
    status: 'todo',
    priority: 5,
    due_date: '',
    tags: 'infrastructure,planning',
    ...EMPTY_TASK_EXTRAS,
  },
  {
    task_id: 't004',
    plan_id: 'p001',
    bucket_id: 'b004',
    assignee_ids: 'u002',
    title: 'Migrate Terraform modules to v1.7',
    description: 'Bump providers, fix deprecations, and re-plan all environments.',
    status: 'done',
    priority: 5,
    due_date: '2026-04-30',
    tags: 'infrastructure,terraform',
    ...EMPTY_TASK_EXTRAS,
  },
  {
    task_id: 't005',
    plan_id: 'p001',
    bucket_id: 'b002',
    assignee_ids: 'u003',
    title: 'Set up monitoring dashboards for production services',
    description:
      'Bring up Grafana dashboards for the top five production services with SLO-aligned panels.',
    status: 'in progress',
    priority: 3,
    due_date: '2026-05-30',
    tags: 'infrastructure,monitoring',
    ...EMPTY_TASK_EXTRAS,
  },
  {
    task_id: 't006',
    plan_id: 'p002',
    bucket_id: 'b003',
    assignee_ids: '',
    title: 'Refactor design system tokens',
    description:
      'Move the design tokens into the new shared package and migrate the shell to consume them.',
    status: 'todo',
    priority: 5,
    due_date: '2026-06-10',
    tags: 'frontend,design-system',
    ...EMPTY_TASK_EXTRAS,
  },
  {
    task_id: 't007',
    plan_id: 'p001',
    bucket_id: 'b001',
    assignee_ids: '',
    title: 'Update operational runbook',
    description:
      'Document the steps to rotate IAM credentials and refresh Kubernetes secrets across the AWS production cluster.',
    status: 'todo',
    priority: 3,
    due_date: '2026-06-05',
    tags: 'documentation,operations',
    ...EMPTY_TASK_EXTRAS,
  },
  {
    task_id: 't008',
    plan_id: 'p001',
    bucket_id: 'b001',
    assignee_ids: '',
    title: 'Audit CDN cache configuration for SPA deploys',
    description:
      'Review CloudFront caching rules for the SPA bundle, identify mis-tagged assets, and align with the React build output.',
    status: 'todo',
    priority: 5,
    due_date: '2026-06-08',
    tags: 'infrastructure,frontend,review',
    ...EMPTY_TASK_EXTRAS,
  },
  {
    task_id: 't009',
    plan_id: 'p001',
    bucket_id: 'b001',
    assignee_ids: '',
    title: 'Patch CVE in nginx ingress',
    description:
      'High-severity CVE published last week — patch and redeploy ingress controllers across all clusters.',
    status: 'todo',
    priority: 1,
    due_date: '2026-05-10',
    tags: 'infrastructure,security',
    ...EMPTY_TASK_EXTRAS,
  },
  {
    task_id: 't010',
    plan_id: 'p003',
    bucket_id: 'b005',
    assignee_ids: '',
    title: 'Bootstrap Terraform state backend',
    description: 'Stand up S3 + DynamoDB state backend for the new Terraform workspaces.',
    status: 'todo',
    priority: 3,
    due_date: '2026-06-12',
    tags: 'infrastructure,terraform',
    ...EMPTY_TASK_EXTRAS,
  },
  {
    task_id: 't011',
    plan_id: 'p001',
    bucket_id: 'b001',
    assignee_ids: '',
    title: 'Rotate root credentials immediately',
    description: 'Suspected exposure — rotate root credentials across the AWS organization today.',
    status: 'todo',
    priority: 1,
    due_date: '2026-05-20',
    tags: 'infrastructure,security,urgent',
    ...EMPTY_TASK_EXTRAS,
  },
  {
    task_id: 't012',
    plan_id: 'p001',
    bucket_id: 'b001',
    assignee_ids: 'u001,u002,u003,u004,u005',
    title: 'Quarterly infra retro',
    description:
      'Run the quarterly retro session with the infrastructure crew and capture action items.',
    status: 'todo',
    priority: 5,
    due_date: '2026-06-30',
    tags: 'infrastructure,review',
    ...EMPTY_TASK_EXTRAS,
  },
  {
    task_id: 't013',
    plan_id: 'p001',
    bucket_id: 'b001',
    assignee_ids: '',
    title: 'Upgrade Kubernetes control plane',
    description:
      'Plan and execute a minor-version upgrade of all production Kubernetes control planes.',
    status: 'todo',
    priority: 3,
    due_date: '2026-06-08',
    tags: 'infrastructure,kubernetes',
    ...EMPTY_TASK_EXTRAS,
  },
  {
    task_id: 't014',
    plan_id: 'p001',
    bucket_id: 'b001',
    assignee_ids: '',
    title: 'Modernize legacy mainframe COBOL batch jobs',
    description:
      'Identify which legacy mainframe COBOL batch jobs can be retired or rewritten, and produce a phased migration plan.',
    status: 'todo',
    priority: 5,
    due_date: '2026-07-01',
    tags: 'infrastructure,legacy',
    ...EMPTY_TASK_EXTRAS,
  },
  {
    task_id: 't015',
    plan_id: 'p001',
    bucket_id: 'b001',
    assignee_ids: '',
    title: '',
    description: 'Check AWS production cluster cost report and identify optimization candidates.',
    status: 'todo',
    priority: 5,
    due_date: '2026-06-20',
    tags: '',
    ...EMPTY_TASK_EXTRAS,
  },
  {
    task_id: 't016',
    plan_id: 'p001',
    bucket_id: 'b001',
    assignee_ids: '',
    title:
      'Investigate and document the root cause of the intermittent 502 errors observed during the morning peak traffic window in the production payment gateway and propose a remediation plan covering load balancing strategy',
    description: 'Long-running investigation tracked across several oncall rotations.',
    status: 'todo',
    priority: 5,
    due_date: '2026-07-15',
    tags: 'infrastructure,reliability',
    ...EMPTY_TASK_EXTRAS,
  },
  {
    task_id: 't017',
    plan_id: 'p001',
    bucket_id: 'b001',
    assignee_ids: '',
    title: 'Setup k8s monitoring stack',
    description: 'Stand up Prometheus + Grafana + Loki across the new Kubernetes clusters.',
    status: 'todo',
    priority: 3,
    due_date: '2026-06-18',
    tags: 'kubernetes,monitoring',
    ...EMPTY_TASK_EXTRAS,
  },
  {
    task_id: 't018',
    plan_id: 'p005',
    bucket_id: 'b009',
    assignee_ids: '',
    title: 'Set up Spark cluster for ML pipelines',
    description:
      "Provision Spark for the ML team's NLP pipelines; coordinate with u014 on cluster sizing.",
    status: 'todo',
    priority: 3,
    due_date: '2026-06-30',
    tags: 'ai,spark,ml,nlp',
    ...EMPTY_TASK_EXTRAS,
  },
  {
    task_id: 't019',
    plan_id: 'p006',
    bucket_id: 'b011',
    assignee_ids: '',
    title: 'Define DevOps roadmap',
    description: 'Draft a 12-month DevOps roadmap covering CI, observability, and IaC.',
    status: 'todo',
    priority: 5,
    due_date: '2026-06-25',
    tags: '',
    ...EMPTY_TASK_EXTRAS,
  },
  {
    task_id: 't020',
    plan_id: 'p004',
    bucket_id: 'b007',
    assignee_ids: '',
    title: 'Reduce build flakiness',
    description:
      'Reduce CI build flakiness in the backend repos; root-cause the intermittent test failures.',
    status: 'todo',
    priority: 5,
    due_date: '2026-06-22',
    tags: '',
    ...EMPTY_TASK_EXTRAS,
  },
]

export const NAMED_LEAVES: readonly LeaveEntry[] = [
  {
    leave_id: 'lv001',
    employee_id: 'u002',
    start_date: '2026-05-25',
    end_date: '2026-06-10',
    type: 'annual',
    status: 'approved',
  },
  {
    leave_id: 'lv002',
    employee_id: 'u005',
    start_date: '2026-06-20',
    end_date: '2026-06-25',
    type: 'annual',
    status: 'approved',
  },
  {
    leave_id: 'lv003',
    employee_id: 'u003',
    start_date: '2026-07-01',
    end_date: '2026-07-10',
    type: 'sick',
    status: 'pending',
  },
  {
    leave_id: 'lv004',
    employee_id: 'u001',
    start_date: '2026-05-20',
    end_date: '2026-05-20',
    type: 'personal',
    status: 'approved',
  },
  {
    leave_id: 'lv005',
    employee_id: 'u003',
    start_date: '2026-06-02',
    end_date: '2026-06-02',
    type: 'personal',
    status: 'approved',
  },
  {
    leave_id: 'lv006',
    employee_id: 'u011',
    start_date: '2026-05-20',
    end_date: '2026-05-22',
    type: 'sick',
    status: 'approved',
  },
  {
    leave_id: 'lv007',
    employee_id: 'u002',
    start_date: '2026-05-28',
    end_date: '2026-06-02',
    type: 'personal',
    status: 'pending',
  },
  {
    leave_id: 'lv008',
    employee_id: 'u005',
    start_date: '2026-05-22',
    end_date: '2026-05-23',
    type: 'sick',
    status: 'pending',
  },
  {
    leave_id: 'lv009',
    employee_id: 'u014',
    start_date: '2026-06-15',
    end_date: '2026-06-25',
    type: 'annual',
    status: 'approved',
  },
  {
    leave_id: 'lv010',
    employee_id: 'u012',
    start_date: '2026-05-10',
    end_date: '2026-05-15',
    type: 'sick',
    status: 'approved',
  },
  {
    leave_id: 'lv011',
    employee_id: 'u013',
    start_date: '2026-07-01',
    end_date: '2026-07-05',
    type: 'personal',
    status: 'rejected',
  },
]
