import { describe, expect, it } from 'vitest'
import { buildKey } from '@future/storage'
import { buildAttachmentKeyPrefix } from './attachment-key'

describe('buildAttachmentKeyPrefix', () => {
  it('matches the start of a key generated by buildKey for the same tenant and task', () => {
    const tenantId = 'tenant-abc'
    const taskId = 'task-xyz'

    const key = buildKey({
      tenantId,
      category: 'documents',
      module: 'planner',
      entityId: taskId,
      fileName: 'test.pdf',
    })

    const prefix = buildAttachmentKeyPrefix(tenantId, taskId)

    expect(key.startsWith(prefix)).toBe(true)
  })

  it('returns the expected prefix format', () => {
    expect(buildAttachmentKeyPrefix('t1', 'task1')).toBe('t1/documents/planner/task1/')
  })
})
