export enum SpanType {
  TURN = 'TURN',
  ROUTER_PLAN = 'ROUTER_PLAN',
  SUB_AGENT_PLAN = 'SUB_AGENT_PLAN',
  SUB_AGENT_TOOL_CALL = 'SUB_AGENT_TOOL_CALL',
  SUB_AGENT_SYNTHESIS = 'SUB_AGENT_SYNTHESIS',
  PHASE_2 = 'PHASE_2',
  SYNTHESIZER = 'SYNTHESIZER',
  GATEWAY_STEP = 'GATEWAY_STEP',
  ITERATION = 'ITERATION', // dormant until plan 12; define now
  MEMORY = 'MEMORY',
  FINAL = 'FINAL',
}

export enum EntityType {
  ROUTER = 'ROUTER',
  SUB_AGENT = 'SUB_AGENT',
  TOOL = 'TOOL',
  SYNTHESIZER = 'SYNTHESIZER',
  GATEWAY = 'GATEWAY',
  PROCESSOR = 'PROCESSOR',
  MEMORY = 'MEMORY',
  DELEGATION = 'DELEGATION',
}
