-- ===== candidates (every status + source present; salary text -> scaled min/max) =====
insert into ta.candidate
 (candidate_code, full_name, email, phone, applied_position, role_id,
  salary_expectation_min_scaled, salary_expectation_max_scaled, status, source)
select v.code, v.name, v.email, v.phone, v.position,
       (select role_id from core.role where role_code = v.role),
       v.smin, v.smax, v.status, v.source
from (values
 ('CAND-1001','Nguyễn Quốc Hùng',  'nguyen.quoc.hung@hackathon.com',  '0912-345-001','Senior Backend Developer','BE',1.80,2.50,'Passed','LinkedIn'),
 ('CAND-1002','Trần Thị Thu Hương', 'tran.thu.huong@hackathon.com',    '0912-345-002','Senior Backend Developer','BE',2.00,2.80,'In-pool','TopCV'),
 ('CAND-1003','Lê Minh Tuấn',       'le.minh.tuan@hackathon.com',      '0912-345-003','Mobile Developer (React Native)','Mobile',1.20,1.80,'Passed','LinkedIn'),
 ('CAND-1004','Phạm Ngọc Linh',     'pham.ngoc.linh@hackathon.com',    '0912-345-004','QA Automation Engineer','QA',1.00,1.50,'Rejected','Email'),
 ('CAND-1005','Hoàng Đức Thịnh',    'hoang.duc.thinh@hackathon.com',   '0912-345-005','Data Engineer','DevOps',2.00,3.00,'In-pool','LinkedIn'),
 ('CAND-1006','Huỳnh Thị Mỹ Duyên','huynh.my.duyen@hackathon.com',    '0912-345-006','DevOps Engineer','DevOps',1.80,2.50,'Failed','TopCV'),
 ('CAND-1007','Phan Thanh Sơn',     'phan.thanh.son@hackathon.com',    '0912-345-007','Senior Frontend Developer','FE',1.50,2.20,'Passed','FB'),
 ('CAND-1008','Vũ Thị Khánh Linh',  'vu.khanh.linh@hackathon.com',    '0912-345-008','AI/ML Engineer','ML',2.20,3.50,'In-pool','LinkedIn'),
 ('CAND-1009','Võ Văn Dương',       'vo.van.duong@hackathon.com',      '0912-345-009','Senior Backend Developer','BE',2.00,2.80,'Rejected','Email'),
 ('CAND-1010','Đặng Thị Bích Trâm', 'dang.bich.tram@hackathon.com',   '0912-345-010','Mobile Developer (React Native)','Mobile',1.00,1.60,'Failed','TopCV')
) as v(code, name, email, phone, position, role, smin, smax, status, source);

-- ===== candidate skills (cv_skills CSV normalized; CAND-1010 maps to non-Mobile skills) =====
insert into ta.candidate_skill (candidate_id, skill_id)
select c.candidate_id, s.skill_id
from (values
 ('CAND-1001','python'),('CAND-1001','fastapi'),('CAND-1001','postgres'),('CAND-1001','docker'),
 ('CAND-1002','java'),('CAND-1002','postgres'),('CAND-1002','spark'),
 ('CAND-1003','reactnative'),('CAND-1003','react'),('CAND-1003','postgres'),
 ('CAND-1004','selenium'),('CAND-1004','python'),('CAND-1004','cicd'),
 ('CAND-1005','python'),('CAND-1005','spark'),('CAND-1005','postgres'),
 ('CAND-1006','k8s'),('CAND-1006','terraform'),('CAND-1006','aws'),('CAND-1006','docker'),
 ('CAND-1007','react'),('CAND-1007','communication'),
 ('CAND-1008','python'),('CAND-1008','mlops'),
 ('CAND-1009','go'),('CAND-1009','postgres'),('CAND-1009','k8s'),
 ('CAND-1010','java'),('CAND-1010','go'),('CAND-1010','docker')
) as v(cand, skill)
join ta.candidate c on c.candidate_code = v.cand
join core.skill s on s.skill_code = v.skill;

-- ===== screening criteria (one set per position) =====
insert into ta.screening_criteria (criteria_code, position, role_id)
select v.code, v.position, (select role_id from core.role where role_code = v.role)
from (values
 ('SCR-BE-001','Senior Backend Developer','BE'),
 ('SCR-MOB-001','Mobile Developer (React Native)','Mobile'),
 ('SCR-QA-001','QA Automation Engineer','QA'),
 ('SCR-DE-001','Data Engineer','DevOps'),
 ('SCR-DO-001','DevOps Engineer','DevOps'),
 ('SCR-AI-001','AI/ML Engineer','ML'),
 ('SCR-FE-001','Senior Frontend Developer','FE')
) as v(code, position, role);

-- ===== screening criteria skills (must_have + nice_to_have, mapped to core.skill) =====
insert into ta.screening_criteria_skill (criteria_id, skill_id, skill_type)
select sc.screening_criteria_id, s.skill_id, v.skill_type
from (values
 ('SCR-BE-001','python','must_have'),('SCR-BE-001','postgres','must_have'),
 ('SCR-BE-001','docker','nice_to_have'),('SCR-BE-001','spark','nice_to_have'),
 ('SCR-MOB-001','reactnative','must_have'),('SCR-MOB-001','react','must_have'),
 ('SCR-MOB-001','postgres','must_have'),('SCR-MOB-001','cicd','nice_to_have'),
 ('SCR-QA-001','selenium','must_have'),('SCR-QA-001','python','must_have'),
 ('SCR-QA-001','cicd','nice_to_have'),('SCR-QA-001','docker','nice_to_have'),
 ('SCR-DE-001','python','must_have'),('SCR-DE-001','postgres','must_have'),
 ('SCR-DE-001','spark','nice_to_have'),('SCR-DE-001','aws','nice_to_have'),
 ('SCR-DO-001','docker','must_have'),('SCR-DO-001','cicd','must_have'),('SCR-DO-001','aws','must_have'),
 ('SCR-DO-001','k8s','nice_to_have'),('SCR-DO-001','terraform','nice_to_have'),
 ('SCR-AI-001','python','must_have'),('SCR-AI-001','mlops','must_have'),
 ('SCR-AI-001','aws','nice_to_have'),
 ('SCR-FE-001','react','must_have'),('SCR-FE-001','communication','must_have'),
 ('SCR-FE-001','spark','nice_to_have')
) as v(crit, skill, skill_type)
join ta.screening_criteria sc on sc.criteria_code = v.crit
join core.skill s on s.skill_code = v.skill;

-- ===== outreach templates (LinkedIn / Email / TopCV; OUT-005 & OUT-008 are Vietnamese) =====
insert into ta.outreach_template (template_code, channel, template_content) values
 ('OUT-001','LinkedIn','Hi {name}, I came across your profile and was impressed by your experience in {skill}. We''re looking for a {position} to join our team. Would you be open to a quick chat?'),
 ('OUT-002','Email','Subject: Exciting {position} opportunity at {company}

Hi {name},

We noticed your background in {skill} and believe you''d be a great fit for our {position} role. Are you available for a 15-min call this week?'),
 ('OUT-003','LinkedIn','Hey {name}! We''re scaling our engineering team and your {skill} expertise caught our attention. Interested in learning more about a {position} role with us?'),
 ('OUT-004','Email','Subject: Re-connect: {position} role

Hi {name},

We previously connected regarding a role at our company. We now have a new {position} opening that aligns well with your {skill} background. Would love to reconnect!'),
 ('OUT-005','TopCV','Chào {name}, chúng tôi đang tìm kiếm {position} với kinh nghiệm {skill}. Profile của bạn rất phù hợp. Bạn có muốn tìm hiểu thêm về cơ hội này không?'),
 ('OUT-006','LinkedIn','Hi {name}, I noticed you''ve been doing great work in {skill}. Our team is growing and we have an exciting {position} opening. Happy to share more details if you''re interested!'),
 ('OUT-007','Email','Subject: {position} - We think you''d be a great fit

Hi {name},

Your experience with {skill} stood out to us. We have a {position} role that could be a great next step in your career. Let me know if you''d like to discuss further.'),
 ('OUT-008','TopCV','Xin chào {name}, công ty chúng tôi đang mở vị trí {position}. Với kinh nghiệm {skill} của bạn, chúng tôi tin rằng đây là cơ hội phù hợp. Hãy liên hệ nếu bạn quan tâm!');

-- ===== BEGIN ENHANCED DATA =====
-- ── 5c. ta.candidate ───────────────────────────────────────────
INSERT INTO ta.candidate
  (candidate_code, full_name, email, phone,
   applied_position, salary_expectation_min_scaled, salary_expectation_max_scaled,
   status, source)
VALUES
  ('CAND-1001', 'Candidate A', 'cand_1001@mock.com', '09x-xxx-x001', 'Senior Backend Developer', 1.8, 2.5, 'In-pool', 'LinkedIn'),
  ('CAND-1002', 'Candidate B', 'cand_1002@mock.com', '09x-xxx-x002', 'Senior Backend Developer', 2.2, 3.0, 'Passed', 'LinkedIn'),
  ('CAND-1003', 'Candidate C', 'cand_1003@mock.com', '09x-xxx-x003', 'Senior Backend Developer', 1.6, 2.2, 'In-pool', 'TopCV'),
  ('CAND-1004', 'Candidate D', 'cand_1004@mock.com', '09x-xxx-x004', 'Senior Backend Developer', 1.4, 2.0, 'In-pool', 'TopCV'),
  ('CAND-1005', 'Candidate E', 'cand_1005@mock.com', '09x-xxx-x005', 'Senior Backend Developer', 2.0, 2.8, 'In-pool', 'LinkedIn'),
  ('CAND-1006', 'Candidate F', 'cand_1006@mock.com', '09x-xxx-x006', 'Senior Backend Developer', 1.8, 2.5, 'In-pool', 'Email'),
  ('CAND-1007', 'Candidate G', 'cand_1007@mock.com', '09x-xxx-x007', 'Senior Backend Developer', 1.7, 2.3, 'Rejected', 'LinkedIn'),
  ('CAND-1008', 'Candidate H', 'cand_1008@mock.com', '09x-xxx-x008', 'Senior Backend Developer', 1.2, 1.8, 'In-pool', 'LinkedIn'),
  ('CAND-1009', 'Candidate I', 'cand_1009@mock.com', '09x-xxx-x009', 'Senior Backend Developer', 1.5, 2.0, 'In-pool', 'Email'),
  ('CAND-1010', 'Candidate J', 'cand_1010@mock.com', '09x-xxx-x010', 'Senior Backend Developer', 1.6, 2.2, 'In-pool', 'LinkedIn'),
  ('CAND-1011', 'Candidate K', 'cand_1011@mock.com', '09x-xxx-x011', 'Senior Backend Developer', 1.7, 2.4, 'In-pool', 'LinkedIn'),
  ('CAND-1012', 'Candidate L', 'cand_1012@mock.com', '09x-xxx-x012', 'Senior Backend Developer', 1.3, 1.8, 'In-pool', 'LinkedIn'),
  ('CAND-1013', 'Candidate M', 'cand_1013@mock.com', '09x-xxx-x013', 'Senior Backend Developer', 1.2, 1.7, 'Rejected', 'Email'),
  ('CAND-1014', 'Candidate N', 'cand_1014@mock.com', '09x-xxx-x014', 'Senior Backend Developer', 0.7, 1.0, 'Rejected', 'FB'),
  ('CAND-1015', 'Candidate O', 'cand_1015@mock.com', '09x-xxx-x015', 'Senior Backend Developer', 2.0, 2.8, 'Rejected', 'LinkedIn'),
  ('CAND-1016', 'Candidate P', 'cand_1016@mock.com', '09x-xxx-x016', 'AI/ML Engineer', 2.2, 3.2, 'In-pool', 'LinkedIn'),
  ('CAND-1017', 'Candidate Q', 'cand_1017@mock.com', '09x-xxx-x017', 'AI/ML Engineer', NULL, NULL, 'In-pool', 'LinkedIn'),
  ('CAND-1018', 'Candidate R', 'cand_1018@mock.com', '09x-xxx-x018', 'Data Engineer', NULL, NULL, 'In-pool', 'LinkedIn'),
  ('CAND-1019', 'Candidate S', 'cand_1019@mock.com', '09x-xxx-x019', 'Data Engineer', NULL, NULL, 'In-pool', 'LinkedIn'),
  ('CAND-1020', 'Candidate T', 'cand_1020@mock.com', '09x-xxx-x020', 'PM', NULL, NULL, 'In-pool', 'LinkedIn'),
  ('CAND-1023', 'Candidate W', 'cand_1023@mock.com', '09x-xxx-1023', 'Data Scientist/AI', 2.2, 3.0, 'Passed', 'LinkedIn'),
  ('CAND-1024', 'Candidate X', 'cand_1024@mock.com', '09x-xxx-1024', 'DevOps Engineer', 2.5, 3.2, 'In-pool', 'TopCV'),
  ('CAND-1025', 'Candidate Y', 'cand_1025@mock.com', '09x-xxx-1025', 'Fullstack (ReactJS+Python)', 1.8, 2.6, 'Passed', 'LinkedIn'),
  ('CAND-1026', 'Candidate Z', 'cand_1026@mock.com', '09x-xxx-1026', 'Scrum Master', 1.8, 2.4, 'Failed', 'Email'),
  ('CAND-1027', 'Candidate AA', 'cand_1027@mock.com', '09x-xxx-1027', 'Auto QA', 1.3, 1.8, 'Rejected', 'FB'),
  ('CAND-1028', 'Candidate AB', 'cand_1028@mock.com', '09x-xxx-1028', 'Python Developer', 1.5, 2.2, 'Passed', 'LinkedIn'),
  ('CAND-1029', 'Candidate AC', 'cand_1029@mock.com', '09x-xxx-1029', '.NET Developer', 2.2, 2.8, 'In-pool', 'TopCV'),
  ('CAND-1030', 'Candidate AD', 'cand_1030@mock.com', '09x-xxx-1030', 'QA Analyst', 1.2, 1.7, 'Passed', 'Email'),
  ('CAND-1031', 'Candidate AE', 'cand_1031@mock.com', '09x-xxx-1031', 'AI Agent Engineer', 2.5, 3.3, 'Passed', 'LinkedIn'),
  ('CAND-1032', 'Candidate AF', 'cand_1032@mock.com', '09x-xxx-1032', 'Flutter Developer', 1.4, 2.0, 'Failed', 'FB'),
  ('CAND-1033', 'Candidate AG', 'cand_1033@mock.com', '09x-xxx-1033', 'Data Engineer', 2.4, 3.2, 'Passed', 'TopCV'),
  ('CAND-1034', 'Candidate AH', 'cand_1034@mock.com', '09x-xxx-1034', 'Infra Engineer', 2.2, 3.0, 'Rejected', 'Email'),
  ('CAND-1035', 'Candidate AI', 'cand_1035@mock.com', '09x-xxx-1035', 'IT Helpdesk', 0.8, 1.2, 'In-pool', 'FB'),
  ('CAND-1036', 'Candidate AJ', 'cand_1036@mock.com', '09x-xxx-1036', 'Fullstack Developer', 1.8, 2.6, 'Passed', 'LinkedIn'),
  ('CAND-1037', 'Candidate AK', 'cand_1037@mock.com', '09x-xxx-1037', 'Data Scientist/AI', 2.8, 3.6, 'Passed', 'LinkedIn'),
  ('CAND-1038', 'Candidate AL', 'cand_1038@mock.com', '09x-xxx-1038', 'DevOps Engineer', 2.3, 3.0, 'In-pool', 'TopCV'),
  ('CAND-1039', 'Candidate AM', 'cand_1039@mock.com', '09x-xxx-1039', 'QA Analyst', 1.3, 1.7, 'Rejected', 'Email'),
  ('CAND-1040', 'Candidate AN', 'cand_1040@mock.com', '09x-xxx-1040', 'Python Developer', 1.8, 2.4, 'Passed', 'LinkedIn'),
  ('CAND-1041', 'Candidate AO', 'cand_1041@mock.com', '09x-xxx-1041', 'Scrum Master', 2.2, 3.0, 'Passed', 'TopCV'),
  ('CAND-1042', 'Candidate AP', 'cand_1042@mock.com', '09x-xxx-1042', 'IT Helpdesk', 0.9, 1.3, 'Failed', 'FB'),
  ('CAND-1043', 'Candidate AQ', 'cand_1043@mock.com', '09x-xxx-1043', 'Auto QA', 1.5, 2.1, 'Passed', 'LinkedIn'),
  ('CAND-1044', 'Candidate AR', 'cand_1044@mock.com', '09x-xxx-1044', 'AI (Python Backend)', 2.5, 3.3, 'In-pool', 'Email'),
  ('CAND-1045', 'Candidate AS', 'cand_1045@mock.com', '09x-xxx-1045', 'Fullstack Developer', 2.2, 3.0, 'Passed', 'LinkedIn'),
  ('CAND-1046', 'Candidate AT', 'cand_1046@mock.com', '09x-xxx-1046', 'Data Engineer', 2.3, 3.0, 'Passed', 'TopCV'),
  ('CAND-1047', 'Candidate AU', 'cand_1047@mock.com', '09x-xxx-1047', '.NET Developer', 2.4, 3.2, 'In-pool', 'Email'),
  ('CAND-1048', 'Candidate AV', 'cand_1048@mock.com', '09x-xxx-1048', 'Flutter Developer', 1.5, 2.1, 'Rejected', 'FB'),
  ('CAND-1049', 'Candidate AW', 'cand_1049@mock.com', '09x-xxx-1049', 'AI Agent Engineer', 2.8, 3.6, 'Passed', 'LinkedIn'),
  ('CAND-1050', 'Candidate AX', 'cand_1050@mock.com', '09x-xxx-1050', 'QA Analyst', 1.3, 1.8, 'Failed', 'TopCV'),
  ('CAND-1051', 'Candidate AY', 'cand_1051@mock.com', '09x-xxx-1051', 'DevOps Engineer', 2.6, 3.4, 'Passed', 'LinkedIn'),
  ('CAND-1052', 'Candidate AZ', 'cand_1052@mock.com', '09x-xxx-1052', 'PQA', 1.8, 2.5, 'In-pool', 'Email'),
  ('CAND-1053', 'Candidate BA', 'cand_1053@mock.com', '09x-xxx-1053', 'Python Developer', 1.8, 2.5, 'Passed', 'LinkedIn'),
  ('CAND-1054', 'Candidate BB', 'cand_1054@mock.com', '09x-xxx-1054', 'Data Scientist/AI', 2.4, 3.2, 'Passed', 'LinkedIn'),
  ('CAND-1055', 'Candidate BC', 'cand_1055@mock.com', '09x-xxx-1055', 'Data Scientist/AI', 2.8, 3.5, 'Passed', 'TopCV'),
  ('CAND-1056', 'Candidate BD', 'cand_1056@mock.com', '09x-xxx-1056', 'Data Scientist/AI', 2.2, 2.9, 'In-pool', 'Email'),
  ('CAND-1057', 'Candidate BE', 'cand_1057@mock.com', '09x-xxx-1057', 'Data Scientist/AI', 1.8, 2.3, 'Failed', 'FB'),
  ('CAND-1058', 'Candidate BF', 'cand_1058@mock.com', '09x-xxx-1058', 'Data Scientist/AI', 3.2, 4.0, 'Passed', 'LinkedIn'),
  ('CAND-1067', 'Candidate BO', 'cand_1067@mock.com', '09x-xxx-1067', 'Fullstack (ReactJS+Python)', 2.0, 2.7, 'Passed', 'LinkedIn'),
  ('CAND-1068', 'Candidate BP', 'cand_1068@mock.com', '09x-xxx-1068', 'AI Lead', 4.0, 5.0, 'Passed', 'LinkedIn'),
  ('CAND-1069', 'Candidate BQ', 'cand_1069@mock.com', '09x-xxx-1069', 'Infra Engineer', 2.4, 3.2, 'In-pool', 'TopCV'),
  ('CAND-1070', 'Candidate BR', 'cand_1070@mock.com', '09x-xxx-1070', 'IT Helpdesk', 0.9, 1.2, 'Passed', 'FB'),
  ('CAND-1071', 'Candidate BS', 'cand_1071@mock.com', '09x-xxx-1071', 'Scrum Master', 2.2, 2.9, 'Rejected', 'Email'),
  ('CAND-1072', 'Candidate BT', 'cand_1072@mock.com', '09x-xxx-1072', 'PQA', 1.8, 2.4, 'In-pool', 'TopCV'),
  ('CAND-1073', 'Candidate BU', 'cand_1073@mock.com', '09x-xxx-1073', 'Auto QA', 1.8, 2.5, 'Passed', 'LinkedIn'),
  ('CAND-1074', 'Candidate BV', 'cand_1074@mock.com', '09x-xxx-1074', '.NET Developer', 2.7, 3.5, 'Passed', 'TopCV'),
  ('CAND-1075', 'Candidate BW', 'cand_1075@mock.com', '09x-xxx-1075', 'Fullstack Developer', 1.9, 2.6, 'In-pool', 'Email'),
  ('CAND-1076', 'Candidate BX', 'cand_1076@mock.com', '09x-xxx-1076', 'AI (Python Backend)', 2.6, 3.4, 'Passed', 'LinkedIn'),
  ('CAND-1077', 'Candidate BY', 'cand_1077@mock.com', '09x-xxx-1077', 'Data Engineer', 2.5, 3.2, 'Passed', 'LinkedIn'),
  ('CAND-1078', 'Candidate BZ', 'cand_1078@mock.com', '09x-xxx-1078', 'Flutter Developer', 1.5, 2.2, 'Failed', 'FB'),
  ('CAND-1079', 'Candidate CA', 'cand_1079@mock.com', '09x-xxx-1079', 'QA Analyst', 1.3, 1.8, 'Passed', 'TopCV'),
  ('CAND-1080', 'Candidate CB', 'cand_1080@mock.com', '09x-xxx-1080', 'DevOps Engineer', 2.8, 3.6, 'Passed', 'LinkedIn'),
  ('CAND-1081', 'Candidate CC', 'cand_1081@mock.com', '09x-xxx-1081', 'Python Developer', 1.8, 2.5, 'Passed', 'LinkedIn'),
  ('CAND-1082', 'Candidate CD', 'cand_1082@mock.com', '09x-xxx-1082', 'Data Scientist/AI', 2.5, 3.2, 'Passed', 'TopCV'),
  ('CAND-1083', 'Candidate CE', 'cand_1083@mock.com', '09x-xxx-1083', 'Fullstack (ReactJS+Python)', 2.2, 3.0, 'In-pool', 'Email'),
  ('CAND-1084', 'Candidate CF', 'cand_1084@mock.com', '09x-xxx-1084', 'IT Helpdesk', 0.9, 1.2, 'Passed', 'FB'),
  ('CAND-1085', 'Candidate CG', 'cand_1085@mock.com', '09x-xxx-1085', 'AI Lead', 4.2, 5.2, 'Passed', 'LinkedIn'),
  ('CAND-1086', 'Candidate CH', 'cand_1086@mock.com', '09x-xxx-1086', 'Auto QA', 1.5, 2.1, 'Failed', 'TopCV'),
  ('CAND-1087', 'Candidate CI', 'cand_1087@mock.com', '09x-xxx-1087', 'Scrum Master', 2.3, 3.0, 'Passed', 'LinkedIn'),
  ('CAND-1088', 'Candidate CJ', 'cand_1088@mock.com', '09x-xxx-1088', 'Infra Engineer', 2.4, 3.1, 'In-pool', 'Email'),
  ('CAND-1089', 'Candidate CK', 'cand_1089@mock.com', '09x-xxx-1089', 'QA Analyst', 1.3, 1.8, 'Rejected', 'FB'),
  ('CAND-1090', 'Candidate CL', 'cand_1090@mock.com', '09x-xxx-1090', 'Data Engineer', 2.8, 3.5, 'Passed', 'LinkedIn'),
  ('CAND-1091', 'Candidate CM', 'cand_1091@mock.com', '09x-xxx-1091', '.NET Developer', 2.6, 3.4, 'Passed', 'LinkedIn'),
  ('CAND-1092', 'Candidate CN', 'cand_1092@mock.com', '09x-xxx-1092', 'Python Developer', 1.7, 2.3, 'In-pool', 'TopCV'),
  ('CAND-1093', 'Candidate CO', 'cand_1093@mock.com', '09x-xxx-1093', 'AI Agent Engineer', 3.0, 3.8, 'Passed', 'LinkedIn'),
  ('CAND-1094', 'Candidate CP', 'cand_1094@mock.com', '09x-xxx-1094', 'Fullstack Developer', 2.2, 2.9, 'Passed', 'Email'),
  ('CAND-1095', 'Candidate CQ', 'cand_1095@mock.com', '09x-xxx-1095', 'IT Helpdesk', 0.85, 1.2, 'Passed', 'FB'),
  ('CAND-1096', 'Candidate CR', 'cand_1096@mock.com', '09x-xxx-1096', 'DevOps Engineer', 2.7, 3.5, 'Passed', 'LinkedIn'),
  ('CAND-1097', 'Candidate CS', 'cand_1097@mock.com', '09x-xxx-1097', 'Flutter Developer', 1.6, 2.2, 'Failed', 'TopCV'),
  ('CAND-1098', 'Candidate CT', 'cand_1098@mock.com', '09x-xxx-1098', 'PQA', 1.9, 2.5, 'In-pool', 'Email'),
  ('CAND-1099', 'Candidate CU', 'cand_1099@mock.com', '09x-xxx-1099', 'Data Engineer', 2.6, 3.3, 'Passed', 'LinkedIn'),
  ('CAND-1100', 'Candidate CV', 'cand_1100@mock.com', '09x-xxx-1100', 'QA Analyst', 1.3, 1.8, 'Rejected', 'FB')
ON CONFLICT (candidate_code) DO NOTHING;

-- ── 5d. ta.candidate_skill ─────────────────────────────────────
INSERT INTO core.skill (skill_code, name, skill_category_id)
SELECT v.code, v.name, c.skill_category_id
FROM (VALUES
  ('agile', 'Agile', 'technical'),
  ('ai_architecture', 'AI Architecture', 'technical'),
  ('airflow', 'Airflow', 'technical'),
  ('ansible', 'Ansible', 'technical'),
  ('api', 'API', 'technical'),
  ('api_testing', 'API Testing', 'technical'),
  ('aws', 'AWS', 'technical'),
  ('aws_lambda', 'AWS Lambda', 'technical'),
  ('azure', 'Azure', 'technical'),
  ('c', 'C#', 'technical'),
  ('celery', 'Celery', 'technical'),
  ('ci_cd', 'CI/CD', 'technical'),
  ('coaching', 'Coaching', 'technical'),
  ('cuda', 'CUDA', 'technical'),
  ('dart', 'Dart', 'technical'),
  ('deep_learning', 'Deep Learning', 'technical'),
  ('django', 'Django', 'technical'),
  ('django_rest', 'Django REST', 'technical'),
  ('docker', 'Docker', 'technical'),
  ('documentation', 'Documentation', 'technical'),
  ('elasticsearch', 'ElasticSearch', 'technical'),
  ('elasticsearch', 'Elasticsearch', 'technical'),
  ('etl', 'ETL', 'technical'),
  ('excel', 'Excel', 'technical'),
  ('fastapi', 'FastAPI', 'technical'),
  ('firebase', 'Firebase', 'technical'),
  ('flask', 'Flask', 'technical'),
  ('flutter', 'Flutter', 'technical'),
  ('gcp', 'GCP', 'technical'),
  ('go', 'Go', 'technical'),
  ('grpc', 'gRPC', 'technical'),
  ('huggingface', 'HuggingFace', 'technical'),
  ('java', 'Java', 'technical'),
  ('jenkins', 'Jenkins', 'technical'),
  ('jira', 'Jira', 'technical'),
  ('kafka', 'Kafka', 'technical'),
  ('kubernetes', 'Kubernetes', 'technical'),
  ('langchain', 'LangChain', 'technical'),
  ('leadership', 'Leadership', 'technical'),
  ('linux', 'Linux', 'technical'),
  ('llm', 'LLM', 'technical'),
  ('llm_api', 'LLM API', 'technical'),
  ('machine_learning', 'Machine Learning', 'technical'),
  ('manual_testing', 'Manual Testing', 'technical'),
  ('mlflow', 'MLflow', 'technical'),
  ('mongodb', 'MongoDB', 'technical'),
  ('monitoring', 'Monitoring', 'technical'),
  ('mysql', 'MySQL', 'technical'),
  ('net_core', '.NET Core', 'technical'),
  ('networking', 'Networking', 'technical'),
  ('nginx', 'Nginx', 'technical'),
  ('nlp', 'NLP', 'technical'),
  ('node_js', 'Node.js', 'technical'),
  ('nodejs', 'NodeJS', 'technical'),
  ('oracle_db', 'Oracle DB', 'technical'),
  ('pandas', 'Pandas', 'technical'),
  ('pandas', 'pandas', 'technical'),
  ('playwright', 'Playwright', 'technical'),
  ('postgresql', 'PostgreSQL', 'technical'),
  ('postman', 'Postman', 'technical'),
  ('power_bi', 'Power BI', 'technical'),
  ('process_audit', 'Process Audit', 'technical'),
  ('prompt_engineering', 'Prompt Engineering', 'technical'),
  ('pytest', 'pytest', 'technical'),
  ('python', 'Python', 'technical'),
  ('pytorch', 'PyTorch', 'technical'),
  ('rabbitmq', 'RabbitMQ', 'technical'),
  ('react', 'React', 'technical'),
  ('reactjs', 'ReactJS', 'technical'),
  ('redis', 'Redis', 'technical'),
  ('rest_api', 'REST API', 'technical'),
  ('risk_management', 'Risk Management', 'technical'),
  ('ruby_on_rails', 'Ruby on Rails', 'technical'),
  ('scikit_learn', 'Scikit-learn', 'technical'),
  ('scikit_learn', 'scikit-learn', 'technical'),
  ('scrum', 'Scrum', 'technical'),
  ('selenium', 'Selenium', 'technical'),
  ('sidekiq', 'Sidekiq', 'technical'),
  ('spark', 'Spark', 'technical'),
  ('spring_boot', 'Spring Boot', 'technical'),
  ('sql', 'SQL', 'technical'),
  ('sql_server', 'SQL Server', 'technical'),
  ('sqlalchemy', 'SQLAlchemy', 'technical'),
  ('stakeholder_management', 'Stakeholder Management', 'technical'),
  ('system_design', 'System Design', 'technical'),
  ('tableau', 'Tableau', 'technical'),
  ('tensorflow', 'TensorFlow', 'technical'),
  ('terraform', 'Terraform', 'technical'),
  ('troubleshooting', 'Troubleshooting', 'technical'),
  ('typescript', 'TypeScript', 'technical'),
  ('vector_db', 'Vector DB', 'technical'),
  ('windows', 'Windows', 'technical')
) AS v(code, name, cat)
JOIN core.skill_category c ON c.category_code = v.cat
ON CONFLICT (skill_code) DO NOTHING;

INSERT INTO ta.candidate_skill (candidate_id, skill_id)
SELECT
  (SELECT candidate_id FROM ta.candidate WHERE candidate_code = v.cand),
  (SELECT skill_id     FROM core.skill    WHERE skill_code    = v.skill)
FROM (VALUES
  ('CAND-1001', 'python'),
  ('CAND-1001', 'fastapi'),
  ('CAND-1001', 'postgresql'),
  ('CAND-1001', 'redis'),
  ('CAND-1001', 'docker'),
  ('CAND-1001', 'kafka'),
  ('CAND-1001', 'rabbitmq'),
  ('CAND-1001', 'aws'),
  ('CAND-1002', 'python'),
  ('CAND-1002', 'django'),
  ('CAND-1002', 'fastapi'),
  ('CAND-1002', 'postgresql'),
  ('CAND-1002', 'mysql'),
  ('CAND-1002', 'celery'),
  ('CAND-1002', 'redis'),
  ('CAND-1002', 'kafka'),
  ('CAND-1002', 'docker'),
  ('CAND-1002', 'kubernetes'),
  ('CAND-1003', 'python'),
  ('CAND-1003', 'flask'),
  ('CAND-1003', 'fastapi'),
  ('CAND-1003', 'postgresql'),
  ('CAND-1003', 'sqlalchemy'),
  ('CAND-1003', 'docker'),
  ('CAND-1003', 'jenkins'),
  ('CAND-1003', 'elasticsearch'),
  ('CAND-1004', 'python'),
  ('CAND-1004', 'fastapi'),
  ('CAND-1004', 'mysql'),
  ('CAND-1004', 'docker'),
  ('CAND-1004', 'rest_api'),
  ('CAND-1004', 'sqlalchemy'),
  ('CAND-1004', 'nginx'),
  ('CAND-1005', 'python'),
  ('CAND-1005', 'go'),
  ('CAND-1005', 'fastapi'),
  ('CAND-1005', 'postgresql'),
  ('CAND-1005', 'redis'),
  ('CAND-1005', 'kafka'),
  ('CAND-1005', 'kubernetes'),
  ('CAND-1005', 'gcp'),
  ('CAND-1005', 'grpc'),
  ('CAND-1006', 'java'),
  ('CAND-1006', 'spring_boot'),
  ('CAND-1006', 'mysql'),
  ('CAND-1006', 'oracle_db'),
  ('CAND-1006', 'kafka'),
  ('CAND-1006', 'docker'),
  ('CAND-1006', 'jenkins'),
  ('CAND-1007', 'node_js'),
  ('CAND-1007', 'typescript'),
  ('CAND-1007', 'mongodb'),
  ('CAND-1007', 'redis'),
  ('CAND-1007', 'docker'),
  ('CAND-1007', 'kubernetes'),
  ('CAND-1007', 'aws_lambda'),
  ('CAND-1008', 'python'),
  ('CAND-1008', 'django'),
  ('CAND-1008', 'postgresql'),
  ('CAND-1008', 'mysql'),
  ('CAND-1008', 'docker'),
  ('CAND-1008', 'rest_api'),
  ('CAND-1009', 'python'),
  ('CAND-1009', 'fastapi'),
  ('CAND-1009', 'docker'),
  ('CAND-1009', 'kubernetes'),
  ('CAND-1009', 'ansible'),
  ('CAND-1009', 'terraform'),
  ('CAND-1009', 'postgresql'),
  ('CAND-1009', 'redis'),
  ('CAND-1010', 'python'),
  ('CAND-1010', 'ruby_on_rails'),
  ('CAND-1010', 'postgresql'),
  ('CAND-1010', 'redis'),
  ('CAND-1010', 'sidekiq'),
  ('CAND-1010', 'docker'),
  ('CAND-1010', 'elasticsearch'),
  ('CAND-1011', 'python'),
  ('CAND-1011', 'fastapi'),
  ('CAND-1011', 'node_js'),
  ('CAND-1011', 'react'),
  ('CAND-1011', 'postgresql'),
  ('CAND-1011', 'kafka'),
  ('CAND-1011', 'docker'),
  ('CAND-1012', 'python'),
  ('CAND-1012', 'django_rest'),
  ('CAND-1012', 'postgresql'),
  ('CAND-1012', 'celery'),
  ('CAND-1012', 'rabbitmq'),
  ('CAND-1012', 'docker'),
  ('CAND-1013', 'python'),
  ('CAND-1013', 'selenium'),
  ('CAND-1013', 'playwright'),
  ('CAND-1013', 'pytest'),
  ('CAND-1013', 'jenkins'),
  ('CAND-1013', 'docker'),
  ('CAND-1013', 'postman'),
  ('CAND-1014', 'python'),
  ('CAND-1014', 'flask'),
  ('CAND-1014', 'mysql'),
  ('CAND-1014', 'rest_api'),
  ('CAND-1015', 'python'),
  ('CAND-1015', 'pandas'),
  ('CAND-1015', 'scikit_learn'),
  ('CAND-1015', 'sql'),
  ('CAND-1015', 'tableau'),
  ('CAND-1015', 'power_bi'),
  ('CAND-1015', 'excel'),
  ('CAND-1016', 'python'),
  ('CAND-1016', 'pytorch'),
  ('CAND-1016', 'tensorflow'),
  ('CAND-1016', 'huggingface'),
  ('CAND-1016', 'mlflow'),
  ('CAND-1016', 'docker'),
  ('CAND-1016', 'fastapi'),
  ('CAND-1016', 'cuda'),
  ('CAND-1023', 'python'),
  ('CAND-1023', 'machine_learning'),
  ('CAND-1023', 'sql'),
  ('CAND-1023', 'pandas'),
  ('CAND-1024', 'docker'),
  ('CAND-1024', 'kubernetes'),
  ('CAND-1024', 'ci_cd'),
  ('CAND-1024', 'aws'),
  ('CAND-1025', 'reactjs'),
  ('CAND-1025', 'typescript'),
  ('CAND-1025', 'python'),
  ('CAND-1025', 'fastapi'),
  ('CAND-1026', 'agile'),
  ('CAND-1026', 'scrum'),
  ('CAND-1026', 'jira'),
  ('CAND-1026', 'stakeholder_management'),
  ('CAND-1027', 'selenium'),
  ('CAND-1027', 'api_testing'),
  ('CAND-1027', 'sql'),
  ('CAND-1027', 'jira'),
  ('CAND-1028', 'python'),
  ('CAND-1028', 'fastapi'),
  ('CAND-1028', 'postgresql'),
  ('CAND-1028', 'docker'),
  ('CAND-1029', 'c'),
  ('CAND-1029', 'net_core'),
  ('CAND-1029', 'sql_server'),
  ('CAND-1029', 'rest_api'),
  ('CAND-1030', 'manual_testing'),
  ('CAND-1030', 'jira'),
  ('CAND-1030', 'api_testing'),
  ('CAND-1031', 'python'),
  ('CAND-1031', 'langchain'),
  ('CAND-1031', 'prompt_engineering'),
  ('CAND-1031', 'api'),
  ('CAND-1032', 'flutter'),
  ('CAND-1032', 'dart'),
  ('CAND-1032', 'firebase'),
  ('CAND-1033', 'python'),
  ('CAND-1033', 'sql'),
  ('CAND-1033', 'airflow'),
  ('CAND-1033', 'etl'),
  ('CAND-1034', 'linux'),
  ('CAND-1034', 'docker'),
  ('CAND-1034', 'aws'),
  ('CAND-1034', 'monitoring'),
  ('CAND-1035', 'troubleshooting'),
  ('CAND-1035', 'windows'),
  ('CAND-1035', 'networking'),
  ('CAND-1036', 'reactjs'),
  ('CAND-1036', 'nodejs'),
  ('CAND-1036', 'mysql'),
  ('CAND-1036', 'rest_api'),
  ('CAND-1037', 'python'),
  ('CAND-1037', 'tensorflow'),
  ('CAND-1037', 'nlp'),
  ('CAND-1037', 'sql'),
  ('CAND-1038', 'aws'),
  ('CAND-1038', 'docker'),
  ('CAND-1038', 'kubernetes'),
  ('CAND-1038', 'linux'),
  ('CAND-1039', 'manual_testing'),
  ('CAND-1039', 'jira'),
  ('CAND-1039', 'sql'),
  ('CAND-1040', 'python'),
  ('CAND-1040', 'django'),
  ('CAND-1040', 'postgresql'),
  ('CAND-1040', 'docker'),
  ('CAND-1041', 'agile'),
  ('CAND-1041', 'scrum'),
  ('CAND-1041', 'jira'),
  ('CAND-1041', 'coaching'),
  ('CAND-1042', 'windows'),
  ('CAND-1042', 'troubleshooting'),
  ('CAND-1042', 'networking'),
  ('CAND-1043', 'selenium'),
  ('CAND-1043', 'api_testing'),
  ('CAND-1043', 'sql'),
  ('CAND-1043', 'playwright'),
  ('CAND-1044', 'python'),
  ('CAND-1044', 'fastapi'),
  ('CAND-1044', 'postgresql'),
  ('CAND-1044', 'llm_api'),
  ('CAND-1045', 'reactjs'),
  ('CAND-1045', 'nodejs'),
  ('CAND-1045', 'mongodb'),
  ('CAND-1045', 'rest_api'),
  ('CAND-1046', 'python'),
  ('CAND-1046', 'sql'),
  ('CAND-1046', 'etl'),
  ('CAND-1046', 'airflow'),
  ('CAND-1047', 'c'),
  ('CAND-1047', 'net_core'),
  ('CAND-1047', 'sql_server'),
  ('CAND-1047', 'azure'),
  ('CAND-1048', 'flutter'),
  ('CAND-1048', 'dart'),
  ('CAND-1048', 'firebase'),
  ('CAND-1049', 'python'),
  ('CAND-1049', 'langchain'),
  ('CAND-1049', 'prompt_engineering'),
  ('CAND-1049', 'vector_db'),
  ('CAND-1050', 'manual_testing'),
  ('CAND-1050', 'api_testing'),
  ('CAND-1050', 'jira'),
  ('CAND-1051', 'aws'),
  ('CAND-1051', 'docker'),
  ('CAND-1051', 'kubernetes'),
  ('CAND-1051', 'linux'),
  ('CAND-1052', 'process_audit'),
  ('CAND-1052', 'documentation'),
  ('CAND-1052', 'risk_management'),
  ('CAND-1053', 'python'),
  ('CAND-1053', 'fastapi'),
  ('CAND-1053', 'postgresql'),
  ('CAND-1053', 'docker'),
  ('CAND-1054', 'python'),
  ('CAND-1054', 'machine_learning'),
  ('CAND-1054', 'sql'),
  ('CAND-1054', 'pandas'),
  ('CAND-1054', 'scikit_learn'),
  ('CAND-1055', 'python'),
  ('CAND-1055', 'nlp'),
  ('CAND-1055', 'machine_learning'),
  ('CAND-1055', 'sql'),
  ('CAND-1055', 'tensorflow'),
  ('CAND-1056', 'python'),
  ('CAND-1056', 'machine_learning'),
  ('CAND-1056', 'pandas'),
  ('CAND-1056', 'sql'),
  ('CAND-1057', 'python'),
  ('CAND-1057', 'sql'),
  ('CAND-1057', 'tableau'),
  ('CAND-1057', 'pandas'),
  ('CAND-1058', 'python'),
  ('CAND-1058', 'deep_learning'),
  ('CAND-1058', 'nlp'),
  ('CAND-1058', 'sql'),
  ('CAND-1058', 'tensorflow'),
  ('CAND-1067', 'reactjs'),
  ('CAND-1067', 'python'),
  ('CAND-1067', 'fastapi'),
  ('CAND-1067', 'postgresql'),
  ('CAND-1068', 'python'),
  ('CAND-1068', 'llm'),
  ('CAND-1068', 'system_design'),
  ('CAND-1068', 'leadership'),
  ('CAND-1069', 'linux'),
  ('CAND-1069', 'aws'),
  ('CAND-1069', 'docker'),
  ('CAND-1069', 'monitoring'),
  ('CAND-1070', 'troubleshooting'),
  ('CAND-1070', 'windows'),
  ('CAND-1070', 'networking'),
  ('CAND-1071', 'agile'),
  ('CAND-1071', 'scrum'),
  ('CAND-1071', 'jira'),
  ('CAND-1071', 'stakeholder_management'),
  ('CAND-1072', 'process_audit'),
  ('CAND-1072', 'documentation'),
  ('CAND-1072', 'risk_management'),
  ('CAND-1073', 'selenium'),
  ('CAND-1073', 'playwright'),
  ('CAND-1073', 'api_testing'),
  ('CAND-1073', 'sql'),
  ('CAND-1074', 'c'),
  ('CAND-1074', 'net_core'),
  ('CAND-1074', 'sql_server'),
  ('CAND-1074', 'azure'),
  ('CAND-1074', 'rest_api'),
  ('CAND-1075', 'reactjs'),
  ('CAND-1075', 'nodejs'),
  ('CAND-1075', 'mongodb'),
  ('CAND-1075', 'rest_api'),
  ('CAND-1076', 'python'),
  ('CAND-1076', 'fastapi'),
  ('CAND-1076', 'postgresql'),
  ('CAND-1076', 'llm_api'),
  ('CAND-1077', 'python'),
  ('CAND-1077', 'sql'),
  ('CAND-1077', 'airflow'),
  ('CAND-1077', 'spark'),
  ('CAND-1078', 'flutter'),
  ('CAND-1078', 'dart'),
  ('CAND-1078', 'firebase'),
  ('CAND-1078', 'rest_api'),
  ('CAND-1079', 'manual_testing'),
  ('CAND-1079', 'sql'),
  ('CAND-1079', 'api_testing'),
  ('CAND-1079', 'jira'),
  ('CAND-1080', 'aws'),
  ('CAND-1080', 'docker'),
  ('CAND-1080', 'kubernetes'),
  ('CAND-1080', 'terraform'),
  ('CAND-1081', 'python'),
  ('CAND-1081', 'fastapi'),
  ('CAND-1081', 'postgresql'),
  ('CAND-1081', 'docker'),
  ('CAND-1082', 'python'),
  ('CAND-1082', 'machine_learning'),
  ('CAND-1082', 'sql'),
  ('CAND-1082', 'tensorflow'),
  ('CAND-1083', 'reactjs'),
  ('CAND-1083', 'python'),
  ('CAND-1083', 'fastapi'),
  ('CAND-1083', 'postgresql'),
  ('CAND-1084', 'troubleshooting'),
  ('CAND-1084', 'windows'),
  ('CAND-1084', 'networking'),
  ('CAND-1085', 'python'),
  ('CAND-1085', 'llm'),
  ('CAND-1085', 'ai_architecture'),
  ('CAND-1085', 'leadership'),
  ('CAND-1086', 'selenium'),
  ('CAND-1086', 'playwright'),
  ('CAND-1086', 'api_testing'),
  ('CAND-1087', 'scrum'),
  ('CAND-1087', 'agile'),
  ('CAND-1087', 'jira'),
  ('CAND-1087', 'stakeholder_management'),
  ('CAND-1088', 'linux'),
  ('CAND-1088', 'aws'),
  ('CAND-1088', 'docker'),
  ('CAND-1088', 'monitoring'),
  ('CAND-1089', 'manual_testing'),
  ('CAND-1089', 'sql'),
  ('CAND-1089', 'jira'),
  ('CAND-1089', 'api_testing'),
  ('CAND-1090', 'python'),
  ('CAND-1090', 'sql'),
  ('CAND-1090', 'spark'),
  ('CAND-1090', 'airflow'),
  ('CAND-1091', 'c'),
  ('CAND-1091', 'net_core'),
  ('CAND-1091', 'sql_server'),
  ('CAND-1091', 'azure'),
  ('CAND-1092', 'python'),
  ('CAND-1092', 'django'),
  ('CAND-1092', 'postgresql'),
  ('CAND-1092', 'docker'),
  ('CAND-1093', 'python'),
  ('CAND-1093', 'langchain'),
  ('CAND-1093', 'llm'),
  ('CAND-1093', 'prompt_engineering'),
  ('CAND-1094', 'reactjs'),
  ('CAND-1094', 'nodejs'),
  ('CAND-1094', 'mongodb'),
  ('CAND-1094', 'rest_api'),
  ('CAND-1095', 'windows'),
  ('CAND-1095', 'troubleshooting'),
  ('CAND-1095', 'networking'),
  ('CAND-1096', 'aws'),
  ('CAND-1096', 'docker'),
  ('CAND-1096', 'kubernetes'),
  ('CAND-1096', 'terraform'),
  ('CAND-1097', 'flutter'),
  ('CAND-1097', 'dart'),
  ('CAND-1097', 'firebase'),
  ('CAND-1097', 'rest_api'),
  ('CAND-1098', 'process_audit'),
  ('CAND-1098', 'documentation'),
  ('CAND-1098', 'risk_management'),
  ('CAND-1099', 'python'),
  ('CAND-1099', 'sql'),
  ('CAND-1099', 'spark'),
  ('CAND-1099', 'airflow'),
  ('CAND-1100', 'manual_testing'),
  ('CAND-1100', 'api_testing'),
  ('CAND-1100', 'sql'),
  ('CAND-1100', 'jira')
) AS v(cand, skill)
WHERE (SELECT candidate_id FROM ta.candidate WHERE candidate_code = v.cand) IS NOT NULL
  AND (SELECT skill_id     FROM core.skill    WHERE skill_code    = v.skill) IS NOT NULL
ON CONFLICT (candidate_id, skill_id) DO NOTHING;

-- ── 5e. ta.screening_criteria & screening_criteria_skill ────────
INSERT INTO ta.screening_criteria (criteria_code, position)
VALUES
  ('SCR-BE-002', 'Backend Developer'),
  ('SCR-DS-001', 'Data Scientist'),
  ('SCR-DS-002', 'Data Scientist'),
  ('SCR-PM-001', 'Project Manager'),
  ('SCR-SM-001', 'Scrum Master'),
  ('SCR-FS-001', 'Fullstack (ReactJS+Python)'),
  ('SCR-PY-001', 'Python Developer'),
  ('SCR-DN-001', '.NET Developer'),
  ('SCR-FL-001', 'Flutter Developer'),
  ('SCR-QA-002', 'QA Analyst'),
  ('SCR-AQ-002', 'Auto QA'),
  ('SCR-AI-002', 'AI Agent Engineer'),
  ('SCR-AIL-001', 'AI Lead'),
  ('SCR-INF-001', 'Infra Engineer'),
  ('SCR-HD-001', 'IT Helpdesk'),
  ('SCR-PQA-001', 'PQA'),
  ('CR-DE-002', 'Data Engineer'),
  ('SCR-DEVOPS-002', 'DevOps Engineer'),
  ('SCR-FE-002', 'Frontend Developer'),
  ('SCR-BA-001', 'Business Analyst'),
  ('SCR-MOB-002', 'Mobile Developer (React Native)')
ON CONFLICT (criteria_code) DO NOTHING;

-- ── 5f. ta.outreach_template ───────────────────────────────────
INSERT INTO ta.outreach_template (template_code, channel, template_content)
VALUES
  ('OUT-001', 'LinkedIn', 'Hi {name}, I came across your profile and was genuinely impressed by the work you did on {project} at {past_company}. We''re building a {position} team at {company} and I think you''d be a strong fit. Would you be open to a 15-min chat this week?'),
  ('OUT-002', 'Email', 'Subject: {jd_title} Opportunity at {company} – Your {skill} Background Caught Our Attention

Hi {name},

Your experience at {past_company}—specifically your work on {project}—is exactly the kind of hands-on expertise we''re looking for in our {position} opening.

Are you available for a quick 15-min call this week or next?

Best,
{recruiter_name}
{company}'),
  ('OUT-003', 'LinkedIn', 'Hey {name}! We spoke earlier about a {position} role and I wanted to reconnect. We now have a new opening that''s an even stronger match for your background in {skill} and your projects like {project}. Would love to reconnect if you''re open to exploring!'),
  ('OUT-004', 'Email', 'Subject: Re-connect – {position} Role at {company}

Hi {name},

I hope you''re doing well. We''ve opened a new {position} position that''s a stronger fit than when we last spoke. Given your background in {skill} at {past_company}, I think this timing could work well for both sides.

Would you be open to a quick chat?

Warm regards,
{recruiter_name}'),
  ('OUT-005', 'TopCV', 'Chào {name},

Mình là {recruiter_name} từ {company}. Mình đọc profile của bạn và rất ấn tượng với dự án {project} mà bạn đã làm tại {past_company}. Hiện tại chúng mình đang tìm {position} với stack {skill}—khá trùng với background của bạn.

Bạn có rảnh 15 phút để trao đổi sơ không?'),
  ('OUT-006', 'LinkedIn', 'Chào {name}! Chúng ta đã từng trao đổi về vị trí {position}. Hiện mình có một cơ hội mới phù hợp hơn với kinh nghiệm {skill} và công việc bạn đã làm tại {past_company}. Bạn có muốn kết nối lại không?'),
  ('OUT-007', 'Email', 'Subject: Your work on {project} – {position} opportunity

Hi {name},

I noticed your work on {project} at {past_company}—that''s exactly the scale and technical challenge our team is working on. We''re hiring a {position} and your profile stood out because of your hands-on experience with {skill}.

Happy to share the JD. Does a quick call work for you?'),
  ('OUT-008', 'Email', 'Subject: Shortlist Summary – {jd_title}

Hi {hiring_manager},

Please find attached the agent-generated shortlist for {jd_title}.

Top candidates:
1. {candidate_1} – Fit Score: {score_1} – {summary_1}
2. {candidate_2} – Fit Score: {score_2} – {summary_2}
3. {candidate_3} – Fit Score: {score_3} – {summary_3}

Outreach messages have been drafted and are awaiting your approval before sending.

[Agent-generated. TA Review Required]'),
  ('OUT-009', 'LinkedIn', 'Hi {name}, your profile—especially your experience with {skill} at {past_company}—caught my attention. We''re scaling our engineering team at {company} and have a {position} role that could be a great fit. No pressure at all, just wanted to plant a seed. Happy to share more if you''re curious!'),
  ('OUT-010', 'TopCV', 'Xin chào {name},

{company} đang tuyển {position} với mức lương cạnh tranh, làm việc {work_mode}. Background của bạn tại {past_company} với kinh nghiệm về {skill} rất phù hợp.

Bạn có thể chia sẻ kỳ vọng lương hiện tại để mình xem thử không?')
ON CONFLICT (template_code) DO NOTHING;

-- ===== END ENHANCED DATA =====
