-- add a new skill not held by any existing employee -> used as coverage-gap edge
insert into core.skill (skill_code, name, skill_category_id)
select 'llm_serving', 'LLM Serving & Inference',
       (select skill_category_id from core.skill_category where category_code = 'technical')
where not exists (select 1 from core.skill where skill_code = 'llm_serving');

-- ===== project required skills (6 active core projects -> core.skill) =====
-- PRJ-005 deliberately requires 'llm_serving' (a new skill no active employee holds)
-- -> coverage-gap edge.
insert into lnd.project_required_skill (project_id, skill_id, min_proficiency_id, is_critical)
select p.project_id, s.skill_id,
       (select proficiency_level_id from core.proficiency_level where prof_code = v.prof),
       v.crit
from (values
 ('PRJ-001','python','Advanced',  true),
 ('PRJ-001','fastapi','Intermediate', true),
 ('PRJ-001','postgres','Intermediate', false),
 ('PRJ-001','docker','Intermediate', false),
 ('PRJ-002','java','Advanced',    true),
 ('PRJ-002','k8s','Intermediate', true),
 ('PRJ-002','aws','Intermediate', false),
 ('PRJ-003','react','Advanced',   true),
 ('PRJ-003','postgres','Intermediate', false),
 ('PRJ-003','docker','Intermediate', false),
 ('PRJ-004','python','Advanced',  true),
 ('PRJ-004','mlops','Advanced',   true),
 ('PRJ-004','spark','Intermediate', false),
 ('PRJ-005','fastapi','Advanced', true),
 ('PRJ-005','k8s','Advanced',     true),
 ('PRJ-005','cka','Advanced',     true),
 ('PRJ-005','cicd','Intermediate', false),
 ('PRJ-006','terraform','Intermediate', true),
 ('PRJ-006','aws','Advanced',     true),
 ('PRJ-006','llm_serving','Advanced', true),
 ('PRJ-006','cicd','Intermediate', false)
) as v(proj, skill, prof, crit)
join core.project p on p.project_code = v.proj
join core.skill   s on s.skill_code   = v.skill;

-- ===== BOD training goals (7 strategic goals) =====
insert into lnd.bod_training_goal (goal_code, goal_description, target_quarter)
values
 ('GOAL-2025-08','Chuẩn bị kỹ năng phỏng vấn & lãnh đạo kỹ thuật cho nhân sự được chọn, bao gồm các lĩnh vực web/backend/DB/system-design/hạ tầng/cloud.','Q3_2025'),
 ('GOAL-2025-09','Bù đắp khoảng cách kỹ năng kỹ thuật theo yêu cầu dự án hiện tại, tập trung vào kiểm thử nền tảng và framework automation phù hợp với yêu cầu khách hàng.','Q3_2025'),
 ('GOAL-2025-11','Xây dựng năng lực DevOps thế hệ mới, có khả năng hỗ trợ các dự án AI nặng và lưu lượng cao sử dụng công nghệ LLM-serving hiện đại.','Q4_2025'),
 ('GOAL-2026-01','Phát triển đội ngũ lãnh đạo kế thừa với năng lực dẫn dắt nhóm và kỹ năng giao tiếp vững mạnh để hỗ trợ tăng trưởng tổ chức.','Q1_2026'),
 ('GOAL-2026-04','Đào tạo kỹ sư đạt trình độ ứng dụng AI và đạt chứng chỉ chuyên nghiệp về công cụ và kiến trúc AI.','Q2_2026'),
 ('GOAL-2026-07','Nâng cấp kỹ năng ít nhất 60% đội phát triển về cloud-native (Kubernetes, CI/CD, IaC) để hỗ trợ triển khai dự án theo hướng cloud-first.','Q3_2026'),
 ('GOAL-2026-10','Xây dựng năng lực phát triển AI Agent nội bộ để các nhóm tự prototype và triển khai quy trình làm việc AI một cách độc lập.','Q4_2026');

-- ===== training-need survey: wave SUR_2025_Q4 (subset of employees) =====
insert into lnd.training_need_survey
 (survey_response_code, survey_wave, employee_id, training_topic, priority, delivery_mode_hint)
select 'SUR-2025Q4-'||v.emp, 'SUR_2025_Q4',
       (select employee_id from core.employee where emp_code = v.emp),
       v.topic, v.prio, v.mode
from (values
 ('EMP-0003','Thiết kế hệ thống và kiến trúc nâng cao','High',NULL),
 ('EMP-0004','Microservices và điều phối container','High','internal'),
 ('EMP-0005','Cơ bản về Machine Learning','Medium','online'),
 ('EMP-0007','Luyện thi chứng chỉ CKA','Medium','online'),
 ('EMP-0008','Thực hành MLOps và công cụ liên quan','High','internal'),
 ('EMP-0010','Phát triển Backend với NodeJS','High','internal'),
 ('EMP-0011','Triển khai Cloud trên AWS','Medium','online'),
 ('EMP-0014','Phát triển với ngôn ngữ Go','High','internal'),
 ('EMP-0015','Pipeline kỹ thuật dữ liệu','Medium','internal'),
 ('EMP-0016','Thiết kế hệ thống và kiến trúc','Medium','internal'),
 ('EMP-0018','Lãnh đạo nhóm và lập kế hoạch chiến lược','High',NULL),
 ('EMP-0020','Kubernetes và điều phối container','High','internal')
) as v(emp, topic, prio, mode);

-- ===== training-need survey: wave SUR_2026_Q1 (overlapping + new respondents) =====
insert into lnd.training_need_survey
 (survey_response_code, survey_wave, employee_id, training_topic, priority, delivery_mode_hint)
select 'SUR-2026Q1-'||v.emp, 'SUR_2026_Q1',
       (select employee_id from core.employee where emp_code = v.emp),
       v.topic, v.prio, v.mode
from (values
 ('EMP-0003','Kỹ năng lãnh đạo','High',NULL),
 ('EMP-0004','DevOps và công nghệ backend hiện đại','High','internal'),
 ('EMP-0005','Xây dựng agent cá nhân nâng cao quy trình làm việc','Medium','self-learning'),
 ('EMP-0007','Kỹ năng phỏng vấn','High',NULL),
 ('EMP-0009','Tự học qua khóa học bên ngoài','Low','self-learning'),
 ('EMP-0011','Kỹ năng lập kế hoạch','Medium',NULL),
 ('EMP-0012','Kiểm thử Tự động','Low','internal'),
 ('EMP-0016','Kỹ năng lập kế hoạch và kiến thức Agentic AI','High','internal'),
 ('EMP-0021','Dịch vụ Cloud','Medium','online'),
 ('EMP-0024','Kỹ năng giao tiếp tiếng Anh','Medium','online'),
 ('EMP-0027','Kiểm thử tự động từ cơ bản','Medium','internal'),
 ('EMP-0031','AI, tiếng Anh, Cloud','High','online')
) as v(emp, topic, prio, mode);

-- minimal gap stub so happy-path gap assertions are green; Task 5 adds the bulk
insert into lnd.employee_skill_gap (employee_id, skill_id, gap_source, priority)
select (select employee_id from core.employee where emp_code = 'EMP-0003'),
       (select skill_id from core.skill where skill_code = 'docker'),
       'Project','High';

-- ===== bulk employee skill gaps (missing-skill mirror of core.employee_skill) =====
-- 'docker' (Containerization) is planted as the HIGH-FREQUENCY gap across many
-- employees so v_skill_gap_frequency ranks it top.
insert into lnd.employee_skill_gap (employee_id, skill_id, gap_source, priority, note)
select e.employee_id,
       (select skill_id from core.skill where skill_code = 'docker'),
       'Market','Medium','Containerization gap — high org-wide frequency'
from core.employee e
where e.emp_code in (
  'EMP-0004','EMP-0005','EMP-0008','EMP-0010','EMP-0011','EMP-0014','EMP-0015',
  'EMP-0020','EMP-0021','EMP-0024','EMP-0027','EMP-0031')
on conflict (employee_id, skill_id) do nothing;

-- project-driven and role-driven gaps (varied source + priority)
insert into lnd.employee_skill_gap (employee_id, skill_id, gap_source, priority, note)
select (select employee_id from core.employee where emp_code = v.emp),
       (select skill_id from core.skill where skill_code = v.skill),
       v.src, v.prio, v.note
from (values
 ('EMP-0005','mlops','Project','High','Data Scientist needs MLOps for PRJ-004'),
 ('EMP-0008','mlops','Project','High','ML role gap'),
 ('EMP-0011','aws','Project','Medium','Cloud services gap'),
 ('EMP-0014','go','Role','Medium','Backend depth'),
 ('EMP-0015','spark','Project','Medium','ETL/data pipeline gap'),
 ('EMP-0020','cicd','Project','High','Automation/CI gap'),
 ('EMP-0021','k8s','Project','High','Container orchestration for PRJ-002'),
 ('EMP-0024','english','Market','Low','Communication upskill'),
 ('EMP-0027','selenium','Role','Medium','Automation testing gap'),
 ('EMP-0031','cka','Market','High','Certification target for cloud-native goal')
) as v(emp, skill, src, prio, note)
on conflict (employee_id, skill_id) do nothing;

-- ===== BEGIN ENHANCED DATA =====
-- ── 4a. lnd.bod_training_goal ──────────────────────────────────
INSERT INTO lnd.bod_training_goal (goal_code, goal_description, target_quarter)
VALUES
  ('GOAL-2025-08', 'Prepare selected employees with interview skills for technical leadership roles, covering leadership responsibilities, problem-solving approaches, team communication, and technical experience across web/backend/DB/system design/infra/cloud domains.', 'Q3_2025'),
  ('GOAL-2025-09', 'Address technical skill gaps required by current project demands, focusing on platform-specific testing experience and automation test framework knowledge to align with client requirements.', 'Q3_2025'),
  ('GOAL-2025-11', 'Build next-generation DevOps capability capable of supporting AI-heavy projects with high traffic, using modern LLM-serving technology stacks.', 'Q4_2025'),
  ('GOAL-2026-01', 'Develop next-generation leadership pipeline with team-leading capability and strong communication skills to support organizational growth.', 'Q1_2026'),
  ('GOAL-2026-04', 'Train engineering staff to achieve AI application proficiency and earn professional certifications in AI tools and architecture.', 'Q2_2026'),
  ('GOAL-2026-07', 'Upskill at least 60% of development team in cloud-native technologies (Kubernetes, CI/CD, IaC) to support cloud-first project delivery.', 'Q3_2026'),
  ('GOAL-2026-10', 'Establish internal AI agent development competency so teams can prototype and deploy AI-powered workflows independently.', 'Q4_2026')
ON CONFLICT (goal_code) DO NOTHING;

-- ── 4b. lnd.training_need_survey ───────────────────────────────
INSERT INTO lnd.training_need_survey
  (survey_response_code, survey_wave, employee_id, training_topic, priority)
SELECT
  v.code, v.wave,
  (SELECT employee_id FROM core.employee WHERE emp_code = v.emp),
  v.topic, v.priority
FROM (VALUES
  ('SUR-SUR_2025_Q4-EMP-001', 'SUR_2025_Q4', 'EMP-001', 'Advanced system design and architecture', 'High'),
  ('SUR-SUR_2025_Q4-EMP-007', 'SUR_2025_Q4', 'EMP-007', 'CI/CD and DevOps fundamentals', 'Medium'),
  ('SUR-SUR_2025_Q4-EMP-010', 'SUR_2025_Q4', 'EMP-010', 'Microservices and container orchestration', 'High'),
  ('SUR-SUR_2025_Q4-EMP-013', 'SUR_2025_Q4', 'EMP-013', 'Machine Learning fundamentals - online course', 'Medium'),
  ('SUR-SUR_2025_Q4-EMP-016', 'SUR_2025_Q4', 'EMP-016', 'Advanced ReactJS and state management', 'Medium'),
  ('SUR-SUR_2025_Q4-EMP-018', 'SUR_2025_Q4', 'EMP-018', 'Backend development with NodeJS - internal', 'High'),
  ('SUR-SUR_2025_Q4-EMP-021', 'SUR_2025_Q4', 'EMP-021', 'Spring Boot advanced topics - internal', 'High'),
  ('SUR-SUR_2025_Q4-EMP-024', 'SUR_2025_Q4', 'EMP-024', 'Go language development - internal', 'High'),
  ('SUR-SUR_2025_Q4-EMP-028', 'SUR_2025_Q4', 'EMP-028', 'Cloud deployment on AWS - online', 'Medium'),
  ('SUR-SUR_2025_Q4-EMP-031', 'SUR_2025_Q4', 'EMP-031', 'AI and Cloud fundamentals', 'High'),
  ('SUR-SUR_2025_Q4-EMP-036', 'SUR_2025_Q4', 'EMP-036', 'Kubernetes and container orchestration', 'High'),
  ('SUR-SUR_2025_Q4-EMP-037', 'SUR_2025_Q4', 'EMP-037', 'CKA certification prep - online', 'Medium'),
  ('SUR-SUR_2025_Q4-EMP-041', 'SUR_2025_Q4', 'EMP-041', 'LLM application development', 'High'),
  ('SUR-SUR_2025_Q4-EMP-044', 'SUR_2025_Q4', 'EMP-044', 'MLOps practices and tooling', 'High'),
  ('SUR-SUR_2025_Q4-EMP-047', 'SUR_2025_Q4', 'EMP-047', 'Java performance tuning - internal', 'Medium'),
  ('SUR-SUR_2025_Q4-EMP-048', 'SUR_2025_Q4', 'EMP-048', 'AWS solutions architect - online', 'High'),
  ('SUR-SUR_2025_Q4-EMP-060', 'SUR_2025_Q4', 'EMP-060', 'Team leadership and strategic planning', 'High'),
  ('SUR-SUR_2025_Q4-EMP-061', 'SUR_2025_Q4', 'EMP-061', 'ML integration with data pipelines', 'Medium'),
  ('SUR-SUR_2025_Q4-EMP-062', 'SUR_2025_Q4', 'EMP-062', 'Model deployment and MLOps', 'High'),
  ('SUR-SUR_2025_Q4-EMP-066', 'SUR_2025_Q4', 'EMP-066', 'Azure DevOps - online course', 'Medium'),
  ('SUR-SUR_2025_Q4-EMP-076', 'SUR_2025_Q4', 'EMP-076', 'AI and ML foundations - online', 'High'),
  ('SUR-SUR_2025_Q4-EMP-077', 'SUR_2025_Q4', 'EMP-077', 'Data engineering pipelines - internal', 'Medium'),
  ('SUR-SUR_2025_Q4-EMP-081', 'SUR_2025_Q4', 'EMP-081', 'AWS data services - online', 'High'),
  ('SUR-SUR_2025_Q4-EMP-086', 'SUR_2025_Q4', 'EMP-086', 'DevOps foundations - internal', 'High'),
  ('SUR-SUR_2025_Q4-EMP-089', 'SUR_2025_Q4', 'EMP-089', 'Advanced Playwright and AI testing', 'High'),
  ('SUR-SUR_2025_Q4-EMP-090', 'SUR_2025_Q4', 'EMP-090', 'DevOps and cloud - internal', 'Medium'),
  ('SUR-SUR_2025_Q4-EMP-092', 'SUR_2025_Q4', 'EMP-092', 'Cloud certification prep - online', 'High'),
  ('SUR-SUR_2025_Q4-EMP-093', 'SUR_2025_Q4', 'EMP-093', 'Leadership and team management', 'Medium'),
  ('SUR-SUR_2025_Q4-EMP-094', 'SUR_2025_Q4', 'EMP-094', 'System design and architecture', 'Medium'),
  ('SUR-SUR_2025_Q4-EMP-098', 'SUR_2025_Q4', 'EMP-098', 'AI agents and LLM workflows - internal', 'High'),
  ('SUR-SUR_2025_Q4-EMP-103', 'SUR_2025_Q4', 'EMP-103', 'Frontend performance and testing - internal', 'Medium'),
  ('SUR-SUR_2025_Q4-EMP-106', 'SUR_2025_Q4', 'EMP-106', 'Technology strategy and roadmap planning', 'Medium'),
  ('SUR-SUR_2025_Q4-EMP-117', 'SUR_2025_Q4', 'EMP-117', 'Security and threat detection - online', 'High'),
  ('SUR-SUR_2025_Q4-EMP-119', 'SUR_2025_Q4', 'EMP-119', 'Advanced ML and deep learning - online', 'High'),
  ('SUR-SUR_2025_Q4-EMP-124', 'SUR_2025_Q4', 'EMP-124', 'Product and project management skills', 'Medium'),
  ('SUR-SUR_2025_Q4-EMP-127', 'SUR_2025_Q4', 'EMP-127', 'LLM fine-tuning and GenAI - online', 'High'),
  ('SUR-SUR_2025_Q4-EMP-131', 'SUR_2025_Q4', 'EMP-131', 'Advanced PM and stakeholder management', 'High'),
  ('SUR-SUR_2025_Q4-EMP-135', 'SUR_2025_Q4', 'EMP-135', 'Technical leadership and architecture review', 'High'),
  ('SUR-SUR_2025_Q4-EMP-137', 'SUR_2025_Q4', 'EMP-137', 'AI adoption strategy and roadmap', 'High'),
  ('SUR-SUR_2025_Q4-EMP-159', 'SUR_2025_Q4', 'EMP-159', 'AI-assisted project management tools', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-001', 'SUR_2026_Q1', 'EMP-001', 'Leadership skills', 'High'),
  ('SUR-SUR_2026_Q1-EMP-002', 'SUR_2026_Q1', 'EMP-002', 'Soft skills, online learning', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-003', 'SUR_2026_Q1', 'EMP-003', 'Japanese language - self-learning', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-005', 'SUR_2026_Q1', 'EMP-005', 'Build personal agent to enhance workflow', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-007', 'SUR_2026_Q1', 'EMP-007', 'Interview skills', 'High'),
  ('SUR-SUR_2026_Q1-EMP-008', 'SUR_2026_Q1', 'EMP-008', 'AI-related skills', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-009', 'SUR_2026_Q1', 'EMP-009', 'Self-learning external courses', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-010', 'SUR_2026_Q1', 'EMP-010', 'DevOps', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-011', 'SUR_2026_Q1', 'EMP-011', 'Planning skills', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-012', 'SUR_2026_Q1', 'EMP-012', 'Automation Testing', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-013', 'SUR_2026_Q1', 'EMP-013', 'AI Agent, MLOps, Security - internal training', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-014', 'SUR_2026_Q1', 'EMP-014', 'Python development - internal training', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-015', 'SUR_2026_Q1', 'EMP-015', 'Data Scientist skills - online course', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-016', 'SUR_2026_Q1', 'EMP-016', 'Planning Skills, Agentic AI knowledge', 'High'),
  ('SUR-SUR_2026_Q1-EMP-018', 'SUR_2026_Q1', 'EMP-018', 'Python backend (internal), AWS/GCP (online), Japanese (online)', 'High'),
  ('SUR-SUR_2026_Q1-EMP-020', 'SUR_2026_Q1', 'EMP-020', 'Technical skills with project practice opportunity', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-021', 'SUR_2026_Q1', 'EMP-021', 'DevOps, modern backend technologies', 'High'),
  ('SUR-SUR_2026_Q1-EMP-025', 'SUR_2026_Q1', 'EMP-025', 'Communication and leadership skills', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-027', 'SUR_2026_Q1', 'EMP-027', 'Automation testing from basics', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-030', 'SUR_2026_Q1', 'EMP-030', 'Advanced React', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-031', 'SUR_2026_Q1', 'EMP-031', 'AI, English, Cloud', 'High'),
  ('SUR-SUR_2026_Q1-EMP-035', 'SUR_2026_Q1', 'EMP-035', 'Soft skills, client communication, problem-solving', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-037', 'SUR_2026_Q1', 'EMP-037', 'CKA certification - online, DevOps - online', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-039', 'SUR_2026_Q1', 'EMP-039', 'Internal DevOps training course', 'High'),
  ('SUR-SUR_2026_Q1-EMP-040', 'SUR_2026_Q1', 'EMP-040', 'English communication', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-042', 'SUR_2026_Q1', 'EMP-042', 'Communication skills', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-043', 'SUR_2026_Q1', 'EMP-043', 'Automation skill - Python', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-045', 'SUR_2026_Q1', 'EMP-045', 'Python/Golang internal; communication/leadership internal', 'High'),
  ('SUR-SUR_2026_Q1-EMP-046', 'SUR_2026_Q1', 'EMP-046', 'Mobile App Automation Testing', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-047', 'SUR_2026_Q1', 'EMP-047', 'C++ development', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-048', 'SUR_2026_Q1', 'EMP-048', 'AWS Cloud Architecture and Cloud Security - internal training', 'High'),
  ('SUR-SUR_2026_Q1-EMP-049', 'SUR_2026_Q1', 'EMP-049', 'AI integration into systems - internal training', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-051', 'SUR_2026_Q1', 'EMP-051', 'Cloud services', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-053', 'SUR_2026_Q1', 'EMP-053', 'CI/CD pipeline', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-054', 'SUR_2026_Q1', 'EMP-054', 'Communication, leadership, PM skills', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-056', 'SUR_2026_Q1', 'EMP-056', 'Java development - online course', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-058', 'SUR_2026_Q1', 'EMP-058', 'Communication skills', 'High'),
  ('SUR-SUR_2026_Q1-EMP-061', 'SUR_2026_Q1', 'EMP-061', 'GenAI, LLM skills - online course', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-062', 'SUR_2026_Q1', 'EMP-062', 'Management skills', 'High'),
  ('SUR-SUR_2026_Q1-EMP-063', 'SUR_2026_Q1', 'EMP-063', 'Automation Testing for beginners', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-064', 'SUR_2026_Q1', 'EMP-064', 'Backend/AI skills - internal training', 'High'),
  ('SUR-SUR_2026_Q1-EMP-065', 'SUR_2026_Q1', 'EMP-065', 'AI agent - online course', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-066', 'SUR_2026_Q1', 'EMP-066', 'Infrastructure & Cloud, Management skills', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-068', 'SUR_2026_Q1', 'EMP-068', 'Python, Java', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-069', 'SUR_2026_Q1', 'EMP-069', 'Cloud, Domain knowledge, Architecture - online', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-070', 'SUR_2026_Q1', 'EMP-070', 'New language skills (e.g., Chinese/Korean)', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-073', 'SUR_2026_Q1', 'EMP-073', 'NodeJS, Python, leadership, communication - online', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-074', 'SUR_2026_Q1', 'EMP-074', 'Cross-functional project participation as learner', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-075', 'SUR_2026_Q1', 'EMP-075', 'Python development, DevOps', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-079', 'SUR_2026_Q1', 'EMP-079', 'Online course with self-study materials', 'High'),
  ('SUR-SUR_2026_Q1-EMP-080', 'SUR_2026_Q1', 'EMP-080', 'Not sure yet', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-082', 'SUR_2026_Q1', 'EMP-082', 'Omniverse development - internal training', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-084', 'SUR_2026_Q1', 'EMP-084', 'Planning skills', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-085', 'SUR_2026_Q1', 'EMP-085', 'Scrum Master certification', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-086', 'SUR_2026_Q1', 'EMP-086', 'DevOps', 'High'),
  ('SUR-SUR_2026_Q1-EMP-089', 'SUR_2026_Q1', 'EMP-089', 'Automation Testing (Playwright) + AI Testing', 'High'),
  ('SUR-SUR_2026_Q1-EMP-090', 'SUR_2026_Q1', 'EMP-090', 'DevOps - internal training', 'High'),
  ('SUR-SUR_2026_Q1-EMP-091', 'SUR_2026_Q1', 'EMP-091', 'Python, foreign language', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-092', 'SUR_2026_Q1', 'EMP-092', 'Cloud Services (AWS, GCP) - online, Cloud certification', 'High'),
  ('SUR-SUR_2026_Q1-EMP-094', 'SUR_2026_Q1', 'EMP-094', 'English - internal; Safe and effective AI usage - internal/online', 'High'),
  ('SUR-SUR_2026_Q1-EMP-095', 'SUR_2026_Q1', 'EMP-095', 'Python + AI skills', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-096', 'SUR_2026_Q1', 'EMP-096', 'Effective AI usage in testing', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-099', 'SUR_2026_Q1', 'EMP-099', 'Online course', 'High'),
  ('SUR-SUR_2026_Q1-EMP-101', 'SUR_2026_Q1', 'EMP-101', 'Self-learning', 'High'),
  ('SUR-SUR_2026_Q1-EMP-102', 'SUR_2026_Q1', 'EMP-102', 'Leadership and people management', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-105', 'SUR_2026_Q1', 'EMP-105', 'Java development, Software architecture - internal training', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-108', 'SUR_2026_Q1', 'EMP-108', 'Automation testing', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-109', 'SUR_2026_Q1', 'EMP-109', 'Data engineering/Backend development - internal training', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-110', 'SUR_2026_Q1', 'EMP-110', 'Japanese language class - offline', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-111', 'SUR_2026_Q1', 'EMP-111', 'Data Engineering skills - online', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-113', 'SUR_2026_Q1', 'EMP-113', 'DevOps - internal; Python + React - online', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-116', 'SUR_2026_Q1', 'EMP-116', 'English - online course', 'High'),
  ('SUR-SUR_2026_Q1-EMP-118', 'SUR_2026_Q1', 'EMP-118', 'ISTQB certification', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-119', 'SUR_2026_Q1', 'EMP-119', 'Self-learning online', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-120', 'SUR_2026_Q1', 'EMP-120', 'Motion design - online course', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-121', 'SUR_2026_Q1', 'EMP-121', 'ISTQB certification', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-124', 'SUR_2026_Q1', 'EMP-124', 'PMP certification - international', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-125', 'SUR_2026_Q1', 'EMP-125', 'Management skills', 'High'),
  ('SUR-SUR_2026_Q1-EMP-128', 'SUR_2026_Q1', 'EMP-128', 'DevOps', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-129', 'SUR_2026_Q1', 'EMP-129', 'Go development', 'High'),
  ('SUR-SUR_2026_Q1-EMP-130', 'SUR_2026_Q1', 'EMP-130', 'Domain knowledge - Product Mindset', 'High'),
  ('SUR-SUR_2026_Q1-EMP-132', 'SUR_2026_Q1', 'EMP-132', 'Tech Lead and leadership skills', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-133', 'SUR_2026_Q1', 'EMP-133', 'AWS advanced cases sharing - internal', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-134', 'SUR_2026_Q1', 'EMP-134', 'AI for developers - online; Time management, prioritization - online', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-138', 'SUR_2026_Q1', 'EMP-138', 'Automation testing - online course', 'High'),
  ('SUR-SUR_2026_Q1-EMP-139', 'SUR_2026_Q1', 'EMP-139', 'Soft skills - online course', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-143', 'SUR_2026_Q1', 'EMP-143', 'AI skills', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-144', 'SUR_2026_Q1', 'EMP-144', 'Backend JS - online course', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-147', 'SUR_2026_Q1', 'EMP-147', 'PM and BA skills', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-149', 'SUR_2026_Q1', 'EMP-149', 'Planning skills', 'High'),
  ('SUR-SUR_2026_Q1-EMP-151', 'SUR_2026_Q1', 'EMP-151', 'English skills', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-153', 'SUR_2026_Q1', 'EMP-153', 'Python, ReactJS - online or internal', 'High'),
  ('SUR-SUR_2026_Q1-EMP-155', 'SUR_2026_Q1', 'EMP-155', 'Frontend development', 'High'),
  ('SUR-SUR_2026_Q1-EMP-158', 'SUR_2026_Q1', 'EMP-158', '3D design, UI motion', 'High'),
  ('SUR-SUR_2026_Q1-EMP-159', 'SUR_2026_Q1', 'EMP-159', 'AI-powered workflow management', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-160', 'SUR_2026_Q1', 'EMP-160', 'System Design fundamentals', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-163', 'SUR_2026_Q1', 'EMP-163', 'Design - internal training or online course', 'High'),
  ('SUR-SUR_2026_Q1-EMP-164', 'SUR_2026_Q1', 'EMP-164', 'Coding Skills - TypeScript, JavaScript - internal', 'High'),
  ('SUR-SUR_2026_Q1-EMP-165', 'SUR_2026_Q1', 'EMP-165', 'UX analysis, product skills', 'Low'),
  ('SUR-SUR_2026_Q1-EMP-166', 'SUR_2026_Q1', 'EMP-166', 'Data analysis, Stress management, Project management - mixed', 'Medium'),
  ('SUR-SUR_2026_Q1-EMP-167', 'SUR_2026_Q1', 'EMP-167', 'Leadership skills - online or internal; Total reward knowledge', 'Low')
) AS v(code, wave, emp, topic, priority)
ON CONFLICT (survey_response_code) DO NOTHING;

-- ── 4c. lnd.employee_skill_gap ─────────────────────────────────
-- ensure gap skill codes exist
INSERT INTO core.skill (skill_code, name, skill_category_id)
SELECT v.code, v.name, c.skill_category_id
FROM (VALUES
  ('2d_artist', '2D Artist', 'technical'),
  ('accessibility_design', 'Accessibility Design', 'technical'),
  ('agile_scrum', 'Agile/Scrum', 'technical'),
  ('ai', 'AI', 'technical'),
  ('ai_agent', 'AI Agent', 'technical'),
  ('ai_agents', 'AI Agents', 'technical'),
  ('ai_for_developers', 'AI for Developers', 'technical'),
  ('ai_ml_engineering', 'AI/ML Engineering', 'technical'),
  ('ai_tools', 'AI Tools', 'technical'),
  ('ai_tools_copilot_usage', 'AI Tools & Copilot Usage', 'technical'),
  ('ai_training_model', 'AI Training Model', 'technical'),
  ('api_testing', 'API Testing', 'technical'),
  ('auto_test', 'Auto Test', 'technical'),
  ('automation', 'Automation', 'technical'),
  ('automation_cypress_javascript', 'Automation (Cypress/JavaScript)', 'technical'),
  ('automation_testing', 'Automation Testing', 'technical'),
  ('automation_testing_playwright', 'Automation Testing (Playwright)', 'technical'),
  ('automation_testing_selenium_playwright', 'Automation Testing (Selenium/Playwright)', 'technical'),
  ('aws', 'AWS', 'technical'),
  ('azure_cloud', 'Azure Cloud', 'technical'),
  ('azure_devops', 'Azure DevOps', 'technical'),
  ('ba', 'BA', 'technical'),
  ('backend', 'Backend', 'technical'),
  ('backend_development', 'Backend Development', 'technical'),
  ('backend_net', 'Backend (.NET)', 'technical'),
  ('business_management', 'Business Management', 'technical'),
  ('ci_cd', 'CI/CD', 'technical'),
  ('ci_cd_integration', 'CI/CD Integration', 'technical'),
  ('ci_cd_pipeline', 'CI/CD Pipeline', 'technical'),
  ('ci_cd_pipeline_design', 'CI/CD pipeline design', 'technical'),
  ('cloud', 'Cloud', 'technical'),
  ('cloud_deployment', 'Cloud Deployment', 'technical'),
  ('cloud_security', 'Cloud Security', 'technical'),
  ('cloud_services', 'Cloud Services', 'technical'),
  ('computer_vision_model_training', 'Computer Vision Model Training', 'technical'),
  ('container_orchestration', 'Container Orchestration', 'technical'),
  ('container_security', 'Container Security', 'technical'),
  ('containerization', 'Containerization', 'technical'),
  ('cypress', 'Cypress', 'technical'),
  ('data_analysis', 'Data Analysis', 'technical'),
  ('data_engineering', 'Data Engineering', 'technical'),
  ('data_engineering_pipeline', 'Data Engineering Pipeline', 'technical'),
  ('data_science', 'Data Science', 'technical'),
  ('data_visualization', 'Data Visualization', 'technical'),
  ('deep_learning', 'Deep Learning', 'technical'),
  ('devops', 'DevOps', 'technical'),
  ('devops_aws', 'DevOps (AWS', 'technical'),
  ('devops_infrastructure', 'DevOps & Infrastructure', 'technical'),
  ('devsecops', 'DevSecOps', 'technical'),
  ('documentation', 'Documentation', 'technical'),
  ('embedded_development', 'Embedded Development', 'technical'),
  ('etl_data_pipeline', 'ETL/Data Pipeline', 'technical'),
  ('figma', 'Figma', 'technical'),
  ('frontend', 'Frontend', 'technical'),
  ('frontend_angular', 'Frontend Angular', 'technical'),
  ('frontend_html_css', 'Frontend HTML/CSS', 'technical'),
  ('gitops', 'GitOps', 'technical'),
  ('golang', 'Golang', 'technical'),
  ('grpc', 'gRPC', 'technical'),
  ('infrastructure_as_code', 'Infrastructure as Code', 'technical'),
  ('it_outsourcing_embedded_system', 'IT Outsourcing & Embedded System', 'technical'),
  ('java', 'Java', 'technical'),
  ('k8s', 'K8s)', 'technical'),
  ('k8s_orchestration', 'K8s orchestration', 'technical'),
  ('kubernetes', 'Kubernetes', 'technical'),
  ('llm_genai', 'LLM/GenAI', 'technical'),
  ('llms', 'LLMs', 'technical'),
  ('manager', 'Manager', 'technical'),
  ('manual_qa', 'Manual QA', 'technical'),
  ('manual_testing', 'Manual Testing', 'technical'),
  ('marketing', 'Marketing', 'technical'),
  ('mathematical_analysis', 'Mathematical Analysis', 'technical'),
  ('microservices', 'Microservices', 'technical'),
  ('ml_ai', 'ML/AI', 'technical'),
  ('ml_integration', 'ML Integration', 'technical'),
  ('mlops', 'MLOps', 'technical'),
  ('model_deployment', 'Model Deployment', 'technical'),
  ('monitoring', 'Monitoring', 'technical'),
  ('monitoring_observability', 'Monitoring/Observability', 'technical'),
  ('nodejs_backend', 'NodeJS Backend', 'technical'),
  ('observability_stack', 'Observability Stack', 'technical'),
  ('performance_testing', 'Performance Testing', 'technical'),
  ('performance_tuning', 'Performance Tuning', 'technical'),
  ('planning', 'Planning', 'technical'),
  ('playwright', 'Playwright', 'technical'),
  ('prototyping', 'Prototyping', 'technical'),
  ('python', 'Python', 'technical'),
  ('reinforcement_learning', 'Reinforcement Learning', 'technical'),
  ('robot_framework', 'Robot Framework', 'technical'),
  ('script_writing', 'Script Writing', 'technical'),
  ('security', 'Security', 'technical'),
  ('security_testing', 'Security Testing', 'technical'),
  ('sql_testing', 'SQL Testing', 'technical'),
  ('sre_practices', 'SRE practices', 'technical'),
  ('strategic_planning', 'Strategic Planning', 'technical'),
  ('system_architecture', 'System Architecture', 'technical'),
  ('system_design', 'System Design', 'technical'),
  ('team_management', 'Team Management', 'technical'),
  ('technical_depth', 'Technical Depth', 'technical'),
  ('technical_leadership', 'Technical Leadership', 'technical'),
  ('terraform', 'Terraform', 'technical'),
  ('test_framework_design', 'Test Framework Design', 'technical'),
  ('test_reporting', 'Test Reporting', 'technical'),
  ('tester', 'Tester', 'technical'),
  ('testing', 'Testing', 'technical'),
  ('threat_hunting', 'Threat Hunting', 'technical'),
  ('time_management', 'Time Management', 'technical'),
  ('ui_ux', 'UI/UX', 'technical'),
  ('ui_ux_design', 'UI/UX Design', 'technical'),
  ('user_research', 'User Research', 'technical'),
  ('version_control_git', 'Version Control (Git)', 'technical'),
  ('web_development', 'Web Development', 'technical')
) AS v(code, name, cat)
JOIN core.skill_category c ON c.category_code = v.cat
ON CONFLICT (skill_code) DO NOTHING;

INSERT INTO lnd.employee_skill_gap
  (employee_id, skill_id, gap_source, priority)
SELECT
  (SELECT employee_id FROM core.employee WHERE emp_code = v.emp),
  (SELECT skill_id    FROM core.skill    WHERE skill_code = v.skill),
  'Project', 'High'
FROM (VALUES
  ('EMP-001', 'cloud'),
  ('EMP-001', 'automation'),
  ('EMP-001', 'version_control_git'),
  ('EMP-001', 'containerization'),
  ('EMP-002', 'data_analysis'),
  ('EMP-002', 'version_control_git'),
  ('EMP-002', 'containerization'),
  ('EMP-003', 'automation_testing'),
  ('EMP-003', 'api_testing'),
  ('EMP-003', 'performance_testing'),
  ('EMP-003', 'system_architecture'),
  ('EMP-004', 'agile_scrum'),
  ('EMP-004', 'strategic_planning'),
  ('EMP-004', 'ai_tools_copilot_usage'),
  ('EMP-004', 'technical_leadership'),
  ('EMP-005', 'etl_data_pipeline'),
  ('EMP-005', 'data_visualization'),
  ('EMP-005', 'ml_integration'),
  ('EMP-006', 'automation_testing'),
  ('EMP-006', 'api_testing'),
  ('EMP-007', 'automation_testing'),
  ('EMP-007', 'ui_ux'),
  ('EMP-007', 'version_control_git'),
  ('EMP-007', 'containerization'),
  ('EMP-008', 'version_control_git'),
  ('EMP-008', 'containerization'),
  ('EMP-009', 'ai_tools_copilot_usage'),
  ('EMP-010', 'cloud_services'),
  ('EMP-010', 'system_architecture'),
  ('EMP-011', 'cloud_services'),
  ('EMP-011', 'technical_depth'),
  ('EMP-012', 'version_control_git'),
  ('EMP-012', 'containerization'),
  ('EMP-012', 'cloud_services'),
  ('EMP-013', 'deep_learning'),
  ('EMP-013', 'reinforcement_learning'),
  ('EMP-013', 'version_control_git'),
  ('EMP-014', 'cloud_services'),
  ('EMP-014', 'technical_depth'),
  ('EMP-015', 'etl_data_pipeline'),
  ('EMP-015', 'data_visualization'),
  ('EMP-015', 'ml_integration'),
  ('EMP-016', 'automation_testing'),
  ('EMP-016', 'ui_ux'),
  ('EMP-016', 'system_design'),
  ('EMP-017', 'automation_testing'),
  ('EMP-017', 'performance_testing'),
  ('EMP-017', 'security_testing'),
  ('EMP-018', 'ui_ux_design'),
  ('EMP-018', 'figma'),
  ('EMP-018', 'version_control_git'),
  ('EMP-019', 'agile_scrum'),
  ('EMP-019', 'strategic_planning'),
  ('EMP-019', 'ai_tools_copilot_usage'),
  ('EMP-020', 'automation_testing'),
  ('EMP-020', 'api_testing'),
  ('EMP-021', 'cloud_services'),
  ('EMP-021', 'technical_depth'),
  ('EMP-022', 'mlops'),
  ('EMP-022', 'llm_genai'),
  ('EMP-022', 'model_deployment'),
  ('EMP-023', 'containerization'),
  ('EMP-023', 'testing'),
  ('EMP-023', 'ai_tools_copilot_usage'),
  ('EMP-024', 'devops'),
  ('EMP-024', 'version_control_git'),
  ('EMP-025', 'manual_qa'),
  ('EMP-025', 'sql_testing'),
  ('EMP-025', 'api_testing'),
  ('EMP-025', 'performance_testing'),
  ('EMP-026', 'devops'),
  ('EMP-026', 'containerization'),
  ('EMP-027', 'automation_testing'),
  ('EMP-027', 'api_testing'),
  ('EMP-027', 'performance_testing'),
  ('EMP-027', 'ai_tools'),
  ('EMP-028', 'devops'),
  ('EMP-028', 'automation_testing'),
  ('EMP-028', 'ui_ux'),
  ('EMP-028', 'cloud_services'),
  ('EMP-029', 'agile_scrum'),
  ('EMP-029', 'strategic_planning'),
  ('EMP-030', 'automation_testing'),
  ('EMP-030', 'containerization'),
  ('EMP-031', 'testing'),
  ('EMP-031', 'system_design'),
  ('EMP-031', 'ai_tools_copilot_usage'),
  ('EMP-032', 'frontend'),
  ('EMP-032', 'containerization'),
  ('EMP-033', 'automation_testing'),
  ('EMP-033', 'api_testing'),
  ('EMP-033', 'performance_testing'),
  ('EMP-034', 'cloud_services'),
  ('EMP-034', 'technical_depth'),
  ('EMP-035', 'ai_ml_engineering'),
  ('EMP-035', 'containerization'),
  ('EMP-036', 'container_orchestration'),
  ('EMP-036', 'monitoring_observability'),
  ('EMP-037', 'devsecops'),
  ('EMP-037', 'technical_depth'),
  ('EMP-038', 'cloud_services'),
  ('EMP-038', 'technical_depth'),
  ('EMP-039', 'backend_net'),
  ('EMP-039', 'containerization'),
  ('EMP-040', 'cloud_services'),
  ('EMP-040', 'ai_tools_copilot_usage'),
  ('EMP-041', 'mlops'),
  ('EMP-041', 'llm_genai'),
  ('EMP-042', 'cloud_services'),
  ('EMP-042', 'system_architecture'),
  ('EMP-043', 'automation_cypress_javascript'),
  ('EMP-043', 'security_testing'),
  ('EMP-044', 'data_engineering'),
  ('EMP-044', 'mlops'),
  ('EMP-044', 'llm_genai'),
  ('EMP-045', 'frontend_angular'),
  ('EMP-045', 'cloud_services'),
  ('EMP-046', 'manual_testing'),
  ('EMP-046', 'automation_testing'),
  ('EMP-046', 'api_testing'),
  ('EMP-047', 'agile_scrum'),
  ('EMP-047', 'strategic_planning'),
  ('EMP-048', 'cloud_services'),
  ('EMP-048', 'ai_tools_copilot_usage'),
  ('EMP-049', 'cloud_services'),
  ('EMP-049', 'system_architecture'),
  ('EMP-050', 'cloud_services'),
  ('EMP-050', 'ai_tools_copilot_usage'),
  ('EMP-051', 'automation_testing'),
  ('EMP-051', 'api_testing'),
  ('EMP-052', 'data_analysis'),
  ('EMP-052', 'data_science'),
  ('EMP-052', 'containerization'),
  ('EMP-053', 'automation_testing'),
  ('EMP-053', 'api_testing'),
  ('EMP-053', 'performance_testing'),
  ('EMP-054', 'nodejs_backend'),
  ('EMP-054', 'containerization'),
  ('EMP-055', 'cloud_services'),
  ('EMP-055', 'technical_depth'),
  ('EMP-056', 'cloud_services'),
  ('EMP-056', 'technical_depth'),
  ('EMP-057', 'devops'),
  ('EMP-057', 'containerization'),
  ('EMP-058', 'devops'),
  ('EMP-058', 'data_engineering'),
  ('EMP-058', 'ai'),
  ('EMP-058', 'containerization'),
  ('EMP-059', 'devops'),
  ('EMP-059', 'containerization'),
  ('EMP-060', 'devops_infrastructure'),
  ('EMP-060', 'data_engineering'),
  ('EMP-060', 'agile_scrum'),
  ('EMP-061', 'data_visualization'),
  ('EMP-061', 'ml_integration'),
  ('EMP-062', 'devops'),
  ('EMP-062', 'data_analysis'),
  ('EMP-062', 'mlops'),
  ('EMP-062', 'model_deployment'),
  ('EMP-063', 'automation_testing'),
  ('EMP-063', 'performance_testing'),
  ('EMP-063', 'security_testing'),
  ('EMP-064', 'cloud_services'),
  ('EMP-064', 'system_architecture'),
  ('EMP-065', 'cloud_services'),
  ('EMP-065', 'technical_depth'),
  ('EMP-066', 'aws'),
  ('EMP-066', 'azure_devops'),
  ('EMP-066', 'containerization'),
  ('EMP-067', 'ai_tools_copilot_usage'),
  ('EMP-067', 'containerization'),
  ('EMP-068', 'devops'),
  ('EMP-068', 'ui_ux'),
  ('EMP-068', 'containerization'),
  ('EMP-069', 'automation_testing'),
  ('EMP-069', 'containerization'),
  ('EMP-070', 'cloud_services'),
  ('EMP-070', 'technical_depth'),
  ('EMP-071', 'cloud_services'),
  ('EMP-071', 'ai_tools_copilot_usage'),
  ('EMP-072', 'api_testing'),
  ('EMP-072', 'performance_testing'),
  ('EMP-073', 'containerization'),
  ('EMP-074', 'cloud_services'),
  ('EMP-074', 'ai_tools_copilot_usage'),
  ('EMP-075', 'cloud_services'),
  ('EMP-075', 'technical_depth'),
  ('EMP-076', 'ml_ai'),
  ('EMP-076', 'data_visualization'),
  ('EMP-077', 'etl_data_pipeline'),
  ('EMP-077', 'ml_integration'),
  ('EMP-078', 'system_design'),
  ('EMP-078', 'containerization'),
  ('EMP-079', 'containerization'),
  ('EMP-080', 'cloud_services'),
  ('EMP-080', 'technical_depth'),
  ('EMP-081', 'devops'),
  ('EMP-081', 'etl_data_pipeline'),
  ('EMP-081', 'data_visualization'),
  ('EMP-082', 'cloud_services'),
  ('EMP-082', 'technical_depth'),
  ('EMP-083', 'python'),
  ('EMP-083', 'java'),
  ('EMP-083', 'containerization'),
  ('EMP-084', 'cloud_services'),
  ('EMP-084', 'ai_tools_copilot_usage'),
  ('EMP-085', 'devops'),
  ('EMP-085', 'containerization'),
  ('EMP-086', 'containerization'),
  ('EMP-087', 'cloud_services'),
  ('EMP-087', 'technical_depth'),
  ('EMP-088', 'cloud_services'),
  ('EMP-088', 'system_architecture'),
  ('EMP-089', 'automation_testing'),
  ('EMP-089', 'api_testing'),
  ('EMP-089', 'performance_testing'),
  ('EMP-089', 'ai_tools'),
  ('EMP-090', 'devops'),
  ('EMP-090', 'etl_data_pipeline'),
  ('EMP-090', 'data_visualization'),
  ('EMP-091', 'cloud_services'),
  ('EMP-092', 'devops'),
  ('EMP-092', 'containerization'),
  ('EMP-093', 'agile_scrum'),
  ('EMP-093', 'strategic_planning'),
  ('EMP-094', 'ci_cd'),
  ('EMP-094', 'performance_testing'),
  ('EMP-094', 'security_testing'),
  ('EMP-095', 'devops'),
  ('EMP-095', 'containerization'),
  ('EMP-096', 'automation_testing'),
  ('EMP-096', 'api_testing'),
  ('EMP-096', 'performance_testing'),
  ('EMP-097', 'devops'),
  ('EMP-097', 'containerization'),
  ('EMP-098', 'devops'),
  ('EMP-098', 'ai_agents'),
  ('EMP-098', 'llms'),
  ('EMP-098', 'testing'),
  ('EMP-098', 'system_architecture'),
  ('EMP-099', 'automation_testing'),
  ('EMP-099', 'api_testing'),
  ('EMP-099', 'performance_testing'),
  ('EMP-100', 'devops_aws'),
  ('EMP-100', 'terraform'),
  ('EMP-100', 'k8s'),
  ('EMP-100', 'api_testing'),
  ('EMP-100', 'performance_testing'),
  ('EMP-101', 'frontend'),
  ('EMP-101', 'backend'),
  ('EMP-101', 'devops'),
  ('EMP-101', 'containerization'),
  ('EMP-102', 'ai_tools_copilot_usage'),
  ('EMP-103', 'automation_testing'),
  ('EMP-103', 'containerization'),
  ('EMP-104', 'marketing'),
  ('EMP-104', 'frontend_html_css'),
  ('EMP-104', 'user_research'),
  ('EMP-104', 'prototyping'),
  ('EMP-105', 'devops'),
  ('EMP-105', 'containerization'),
  ('EMP-106', 'business_management'),
  ('EMP-106', 'agile_scrum'),
  ('EMP-106', 'strategic_planning'),
  ('EMP-107', 'testing'),
  ('EMP-107', 'containerization'),
  ('EMP-108', 'documentation'),
  ('EMP-108', 'containerization'),
  ('EMP-109', 'python'),
  ('EMP-109', 'containerization'),
  ('EMP-110', 'manual_testing'),
  ('EMP-110', 'containerization'),
  ('EMP-111', 'cloud_services'),
  ('EMP-111', 'system_architecture'),
  ('EMP-112', 'devops'),
  ('EMP-112', 'containerization'),
  ('EMP-113', 'cloud_services'),
  ('EMP-113', 'technical_depth'),
  ('EMP-114', 'cloud_services'),
  ('EMP-114', 'ai_tools_copilot_usage'),
  ('EMP-115', 'cloud_services'),
  ('EMP-115', 'testing'),
  ('EMP-115', 'ai_tools_copilot_usage'),
  ('EMP-116', 'cloud_services'),
  ('EMP-116', 'ai_tools_copilot_usage'),
  ('EMP-117', 'security'),
  ('EMP-117', 'threat_hunting'),
  ('EMP-117', 'container_orchestration'),
  ('EMP-117', 'monitoring'),
  ('EMP-118', 'backend_development'),
  ('EMP-118', 'api_testing'),
  ('EMP-118', 'performance_testing'),
  ('EMP-119', 'mlops'),
  ('EMP-119', 'data_analysis'),
  ('EMP-119', 'etl_data_pipeline'),
  ('EMP-119', 'system_architecture'),
  ('EMP-120', 'user_research'),
  ('EMP-120', 'prototyping'),
  ('EMP-120', 'accessibility_design'),
  ('EMP-121', 'automation_testing'),
  ('EMP-121', 'api_testing'),
  ('EMP-121', 'performance_testing'),
  ('EMP-122', 'ui_ux'),
  ('EMP-122', 'testing'),
  ('EMP-122', 'containerization'),
  ('EMP-123', 'cloud_services'),
  ('EMP-123', 'system_architecture'),
  ('EMP-124', 'ui_ux'),
  ('EMP-124', 'auto_test'),
  ('EMP-124', 'devops'),
  ('EMP-124', 'agile_scrum'),
  ('EMP-124', 'strategic_planning'),
  ('EMP-125', 'ui_ux'),
  ('EMP-125', 'backend'),
  ('EMP-125', 'data_engineering'),
  ('EMP-125', 'containerization'),
  ('EMP-126', 'devops'),
  ('EMP-126', 'containerization'),
  ('EMP-127', 'devops'),
  ('EMP-127', 'llm_genai'),
  ('EMP-127', 'model_deployment'),
  ('EMP-128', 'ba'),
  ('EMP-128', 'tester'),
  ('EMP-128', 'containerization'),
  ('EMP-129', 'devops'),
  ('EMP-129', 'cloud'),
  ('EMP-129', 'containerization'),
  ('EMP-130', 'robot_framework'),
  ('EMP-130', 'containerization'),
  ('EMP-131', 'devops'),
  ('EMP-131', 'manager'),
  ('EMP-131', 'ui_ux_design'),
  ('EMP-131', 'agile_scrum'),
  ('EMP-131', 'strategic_planning'),
  ('EMP-132', 'devops'),
  ('EMP-132', 'data_engineering'),
  ('EMP-132', 'containerization'),
  ('EMP-133', 'devops'),
  ('EMP-133', 'ba'),
  ('EMP-133', 'containerization'),
  ('EMP-134', 'ai_for_developers'),
  ('EMP-134', 'time_management'),
  ('EMP-134', 'planning'),
  ('EMP-135', 'agile_scrum'),
  ('EMP-135', 'strategic_planning'),
  ('EMP-136', 'ui_ux'),
  ('EMP-136', 'data_analysis'),
  ('EMP-136', 'agile_scrum'),
  ('EMP-136', 'strategic_planning'),
  ('EMP-137', 'it_outsourcing_embedded_system'),
  ('EMP-137', 'agile_scrum'),
  ('EMP-138', 'backend_development'),
  ('EMP-138', 'automation_testing'),
  ('EMP-138', 'api_testing'),
  ('EMP-139', 'cloud_services'),
  ('EMP-139', 'system_architecture'),
  ('EMP-140', 'testing'),
  ('EMP-140', 'system_design'),
  ('EMP-141', 'devops'),
  ('EMP-141', 'containerization'),
  ('EMP-142', 'automation_testing'),
  ('EMP-142', 'api_testing'),
  ('EMP-142', 'performance_testing'),
  ('EMP-143', 'automation_testing'),
  ('EMP-143', 'containerization'),
  ('EMP-144', 'web_development'),
  ('EMP-144', 'containerization'),
  ('EMP-145', 'azure_cloud'),
  ('EMP-145', 'automation_testing'),
  ('EMP-145', 'containerization'),
  ('EMP-146', 'ui_ux'),
  ('EMP-146', 'ai'),
  ('EMP-146', 'data_analysis'),
  ('EMP-146', 'containerization'),
  ('EMP-147', 'cloud_services'),
  ('EMP-148', 'devops'),
  ('EMP-148', 'automation_testing'),
  ('EMP-148', 'api_testing'),
  ('EMP-149', 'devops'),
  ('EMP-149', 'automation_testing'),
  ('EMP-149', 'ui_ux'),
  ('EMP-149', 'ai_agent'),
  ('EMP-149', 'containerization'),
  ('EMP-150', 'devops'),
  ('EMP-150', 'containerization'),
  ('EMP-151', 'data_analysis'),
  ('EMP-151', 'data_science'),
  ('EMP-151', 'data_engineering_pipeline'),
  ('EMP-151', 'cloud_services'),
  ('EMP-152', 'embedded_development'),
  ('EMP-152', 'devops'),
  ('EMP-152', 'containerization'),
  ('EMP-153', 'devops'),
  ('EMP-153', 'ui_ux'),
  ('EMP-153', 'containerization'),
  ('EMP-154', 'ai_training_model'),
  ('EMP-154', 'containerization'),
  ('EMP-155', 'ui_ux'),
  ('EMP-155', 'frontend'),
  ('EMP-155', 'containerization'),
  ('EMP-156', 'computer_vision_model_training'),
  ('EMP-156', 'containerization'),
  ('EMP-157', 'devops'),
  ('EMP-157', 'data_engineering'),
  ('EMP-157', 'containerization'),
  ('EMP-158', '2d_artist'),
  ('EMP-158', 'user_research'),
  ('EMP-158', 'prototyping'),
  ('EMP-159', 'ui_ux'),
  ('EMP-159', 'team_management'),
  ('EMP-159', 'agile_scrum'),
  ('EMP-160', 'cloud_services'),
  ('EMP-160', 'technical_depth'),
  ('EMP-161', 'cloud_services'),
  ('EMP-161', 'technical_depth'),
  ('EMP-162', 'mlops'),
  ('EMP-162', 'technical_depth'),
  ('EMP-162', 'mathematical_analysis'),
  ('EMP-163', 'golang'),
  ('EMP-163', 'grpc'),
  ('EMP-163', 'version_control_git'),
  ('EMP-163', 'cloud_services'),
  ('EMP-164', 'golang'),
  ('EMP-164', 'microservices'),
  ('EMP-164', 'container_orchestration'),
  ('EMP-165', 'golang'),
  ('EMP-165', 'kubernetes'),
  ('EMP-165', 'system_architecture'),
  ('EMP-165', 'cloud_services'),
  ('EMP-166', 'golang'),
  ('EMP-166', 'grpc'),
  ('EMP-166', 'version_control_git'),
  ('EMP-166', 'cloud_services'),
  ('EMP-167', 'golang'),
  ('EMP-167', 'microservices'),
  ('EMP-167', 'container_orchestration'),
  ('EMP-168', 'golang'),
  ('EMP-168', 'kubernetes'),
  ('EMP-168', 'system_architecture'),
  ('EMP-168', 'cloud_services'),
  ('EMP-169', 'golang'),
  ('EMP-169', 'grpc'),
  ('EMP-169', 'version_control_git'),
  ('EMP-169', 'cloud_services'),
  ('EMP-170', 'golang'),
  ('EMP-170', 'microservices'),
  ('EMP-170', 'container_orchestration'),
  ('EMP-171', 'golang'),
  ('EMP-171', 'kubernetes'),
  ('EMP-171', 'system_architecture'),
  ('EMP-171', 'cloud_services'),
  ('EMP-172', 'golang'),
  ('EMP-172', 'grpc'),
  ('EMP-172', 'version_control_git'),
  ('EMP-172', 'cloud_services'),
  ('EMP-173', 'golang'),
  ('EMP-173', 'microservices'),
  ('EMP-173', 'container_orchestration'),
  ('EMP-174', 'golang'),
  ('EMP-174', 'kubernetes'),
  ('EMP-174', 'system_architecture'),
  ('EMP-174', 'cloud_services'),
  ('EMP-175', 'golang'),
  ('EMP-175', 'grpc'),
  ('EMP-175', 'version_control_git'),
  ('EMP-175', 'cloud_services'),
  ('EMP-176', 'golang'),
  ('EMP-176', 'microservices'),
  ('EMP-176', 'container_orchestration'),
  ('EMP-177', 'kubernetes'),
  ('EMP-177', 'ci_cd'),
  ('EMP-177', 'monitoring_observability'),
  ('EMP-177', 'cloud_security'),
  ('EMP-178', 'k8s_orchestration'),
  ('EMP-178', 'gitops'),
  ('EMP-178', 'container_security'),
  ('EMP-179', 'ci_cd_pipeline_design'),
  ('EMP-179', 'infrastructure_as_code'),
  ('EMP-179', 'cloud_deployment'),
  ('EMP-180', 'performance_tuning'),
  ('EMP-180', 'sre_practices'),
  ('EMP-180', 'observability_stack'),
  ('EMP-181', 'automation_testing_playwright'),
  ('EMP-181', 'api_testing'),
  ('EMP-181', 'performance_testing'),
  ('EMP-182', 'automation_testing'),
  ('EMP-182', 'ci_cd_integration'),
  ('EMP-182', 'test_framework_design'),
  ('EMP-183', 'automation_testing'),
  ('EMP-183', 'script_writing'),
  ('EMP-183', 'api_testing'),
  ('EMP-183', 'performance_testing'),
  ('EMP-184', 'playwright'),
  ('EMP-184', 'cypress'),
  ('EMP-184', 'performance_testing'),
  ('EMP-184', 'security_testing'),
  ('EMP-185', 'automation_testing_selenium_playwright'),
  ('EMP-185', 'ci_cd_pipeline'),
  ('EMP-185', 'test_reporting'),
  ('EMP-186', 'automation_testing_playwright'),
  ('EMP-186', 'api_testing'),
  ('EMP-186', 'performance_testing'),
  ('EMP-187', 'automation_testing'),
  ('EMP-187', 'ci_cd_integration'),
  ('EMP-187', 'test_framework_design'),
  ('EMP-188', 'automation_testing'),
  ('EMP-188', 'script_writing'),
  ('EMP-188', 'api_testing'),
  ('EMP-188', 'performance_testing'),
  ('EMP-189', 'playwright'),
  ('EMP-189', 'cypress'),
  ('EMP-189', 'performance_testing'),
  ('EMP-189', 'security_testing'),
  ('EMP-190', 'automation_testing_selenium_playwright'),
  ('EMP-190', 'ci_cd_pipeline'),
  ('EMP-190', 'test_reporting'),
  ('EMP-191', 'automation_testing_playwright'),
  ('EMP-191', 'api_testing'),
  ('EMP-191', 'performance_testing'),
  ('EMP-192', 'automation_testing'),
  ('EMP-192', 'ci_cd_integration'),
  ('EMP-192', 'test_framework_design'),
  ('EMP-193', 'automation_testing'),
  ('EMP-193', 'script_writing'),
  ('EMP-193', 'api_testing'),
  ('EMP-193', 'performance_testing'),
  ('EMP-194', 'playwright'),
  ('EMP-194', 'cypress'),
  ('EMP-194', 'performance_testing'),
  ('EMP-194', 'security_testing'),
  ('EMP-195', 'automation_testing_selenium_playwright'),
  ('EMP-195', 'ci_cd_pipeline'),
  ('EMP-195', 'test_reporting'),
  ('EMP-196', 'automation_testing_playwright'),
  ('EMP-196', 'api_testing'),
  ('EMP-196', 'performance_testing'),
  ('EMP-197', 'automation_testing'),
  ('EMP-197', 'ci_cd_integration'),
  ('EMP-197', 'test_framework_design'),
  ('EMP-198', 'automation_testing'),
  ('EMP-198', 'script_writing'),
  ('EMP-198', 'api_testing'),
  ('EMP-198', 'performance_testing'),
  ('EMP-199', 'playwright'),
  ('EMP-199', 'cypress'),
  ('EMP-199', 'performance_testing'),
  ('EMP-199', 'security_testing'),
  ('EMP-200', 'automation_testing_selenium_playwright'),
  ('EMP-200', 'ci_cd_pipeline'),
  ('EMP-200', 'test_reporting'),
  ('EMP-201', 'automation_testing_playwright'),
  ('EMP-201', 'api_testing'),
  ('EMP-201', 'performance_testing'),
  ('EMP-202', 'automation_testing'),
  ('EMP-202', 'ci_cd_integration'),
  ('EMP-202', 'test_framework_design'),
  ('EMP-203', 'automation_testing'),
  ('EMP-203', 'script_writing'),
  ('EMP-203', 'api_testing'),
  ('EMP-203', 'performance_testing'),
  ('EMP-204', 'playwright'),
  ('EMP-204', 'cypress'),
  ('EMP-204', 'performance_testing'),
  ('EMP-204', 'security_testing'),
  ('EMP-205', 'automation_testing_selenium_playwright'),
  ('EMP-205', 'ci_cd_pipeline'),
  ('EMP-205', 'test_reporting')
) AS v(emp, skill)
ON CONFLICT (employee_id, skill_id) DO NOTHING;

-- ===== END ENHANCED DATA =====
