export { VectorInsertFailedError, VectorQueryFailedError } from './errors'
export { findExistingHashes, insertChunks } from './ingest'
export type { Chunk, NewChunk } from './schema'
export { agentVectorSchema, chunks } from './schema'
export type { SearchHit, SearchOptions } from './search'
export { searchChunks } from './search'
