/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedWorkflowsRouteImport } from './routes/_authed/workflows'
import { Route as AuthedToolsRouteImport } from './routes/_authed/tools'
import { Route as AuthedThreadsRouteImport } from './routes/_authed/threads'
import { Route as AuthedSetupRouteImport } from './routes/_authed/setup'
import { Route as AuthedRunsRouteImport } from './routes/_authed/runs'
import { Route as AuthedMetricsRouteImport } from './routes/_authed/metrics'
import { Route as AuthedCorpusRouteImport } from './routes/_authed/corpus'
import { Route as AuthedAuditRouteImport } from './routes/_authed/audit'
import { Route as AuthedAgentsRouteImport } from './routes/_authed/agents'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkflowsRoute = AuthedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedToolsRoute = AuthedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedThreadsRoute = AuthedThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSetupRoute = AuthedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRunsRoute = AuthedRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMetricsRoute = AuthedMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCorpusRoute = AuthedCorpusRouteImport.update({
  id: '/corpus',
  path: '/corpus',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditRoute = AuthedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAgentsRoute = AuthedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/agents': typeof AuthedAgentsRoute
  '/audit': typeof AuthedAuditRoute
  '/corpus': typeof AuthedCorpusRoute
  '/metrics': typeof AuthedMetricsRoute
  '/runs': typeof AuthedRunsRoute
  '/setup': typeof AuthedSetupRoute
  '/threads': typeof AuthedThreadsRoute
  '/tools': typeof AuthedToolsRoute
  '/workflows': typeof AuthedWorkflowsRoute
}
export interface FileRoutesByTo {
  '/agents': typeof AuthedAgentsRoute
  '/audit': typeof AuthedAuditRoute
  '/corpus': typeof AuthedCorpusRoute
  '/metrics': typeof AuthedMetricsRoute
  '/runs': typeof AuthedRunsRoute
  '/setup': typeof AuthedSetupRoute
  '/threads': typeof AuthedThreadsRoute
  '/tools': typeof AuthedToolsRoute
  '/workflows': typeof AuthedWorkflowsRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/agents': typeof AuthedAgentsRoute
  '/_authed/audit': typeof AuthedAuditRoute
  '/_authed/corpus': typeof AuthedCorpusRoute
  '/_authed/metrics': typeof AuthedMetricsRoute
  '/_authed/runs': typeof AuthedRunsRoute
  '/_authed/setup': typeof AuthedSetupRoute
  '/_authed/threads': typeof AuthedThreadsRoute
  '/_authed/tools': typeof AuthedToolsRoute
  '/_authed/workflows': typeof AuthedWorkflowsRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/audit'
    | '/corpus'
    | '/metrics'
    | '/runs'
    | '/setup'
    | '/threads'
    | '/tools'
    | '/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agents'
    | '/audit'
    | '/corpus'
    | '/metrics'
    | '/runs'
    | '/setup'
    | '/threads'
    | '/tools'
    | '/workflows'
    | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/agents'
    | '/_authed/audit'
    | '/_authed/corpus'
    | '/_authed/metrics'
    | '/_authed/runs'
    | '/_authed/setup'
    | '/_authed/threads'
    | '/_authed/tools'
    | '/_authed/workflows'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workflows': {
      id: '/_authed/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthedWorkflowsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tools': {
      id: '/_authed/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthedToolsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/threads': {
      id: '/_authed/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof AuthedThreadsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/setup': {
      id: '/_authed/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthedSetupRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/runs': {
      id: '/_authed/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof AuthedRunsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/metrics': {
      id: '/_authed/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AuthedMetricsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/corpus': {
      id: '/_authed/corpus'
      path: '/corpus'
      fullPath: '/corpus'
      preLoaderRoute: typeof AuthedCorpusRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit': {
      id: '/_authed/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthedAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/agents': {
      id: '/_authed/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthedAgentsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAgentsRoute: typeof AuthedAgentsRoute
  AuthedAuditRoute: typeof AuthedAuditRoute
  AuthedCorpusRoute: typeof AuthedCorpusRoute
  AuthedMetricsRoute: typeof AuthedMetricsRoute
  AuthedRunsRoute: typeof AuthedRunsRoute
  AuthedSetupRoute: typeof AuthedSetupRoute
  AuthedThreadsRoute: typeof AuthedThreadsRoute
  AuthedToolsRoute: typeof AuthedToolsRoute
  AuthedWorkflowsRoute: typeof AuthedWorkflowsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAgentsRoute: AuthedAgentsRoute,
  AuthedAuditRoute: AuthedAuditRoute,
  AuthedCorpusRoute: AuthedCorpusRoute,
  AuthedMetricsRoute: AuthedMetricsRoute,
  AuthedRunsRoute: AuthedRunsRoute,
  AuthedSetupRoute: AuthedSetupRoute,
  AuthedThreadsRoute: AuthedThreadsRoute,
  AuthedToolsRoute: AuthedToolsRoute,
  AuthedWorkflowsRoute: AuthedWorkflowsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
