/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedMeRouteImport } from './routes/_authed/me'
import { Route as LoginProviderCallbackRouteImport } from './routes/login.$provider.callback'
import { Route as AuthedTenantsIdRouteImport } from './routes/_authed/tenants.$id'
import { Route as AuthedTenantsIdWorkflowsRouteImport } from './routes/_authed/tenants.$id.workflows'
import { Route as AuthedTenantsIdToolsRouteImport } from './routes/_authed/tenants.$id.tools'
import { Route as AuthedTenantsIdThreadsRouteImport } from './routes/_authed/tenants.$id.threads'
import { Route as AuthedTenantsIdSetupRouteImport } from './routes/_authed/tenants.$id.setup'
import { Route as AuthedTenantsIdRunsRouteImport } from './routes/_authed/tenants.$id.runs'
import { Route as AuthedTenantsIdMetricsRouteImport } from './routes/_authed/tenants.$id.metrics'
import { Route as AuthedTenantsIdCorpusRouteImport } from './routes/_authed/tenants.$id.corpus'
import { Route as AuthedTenantsIdConnectorsRouteImport } from './routes/_authed/tenants.$id.connectors'
import { Route as AuthedTenantsIdAuditRouteImport } from './routes/_authed/tenants.$id.audit'
import { Route as AuthedTenantsIdAgentsRouteImport } from './routes/_authed/tenants.$id.agents'
import { Route as AuthedTenantsIdConnectorsCidConsentRouteImport } from './routes/_authed/tenants.$id.connectors.$cid.consent'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMeRoute = AuthedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthedRoute,
} as any)
const LoginProviderCallbackRoute = LoginProviderCallbackRouteImport.update({
  id: '/$provider/callback',
  path: '/$provider/callback',
  getParentRoute: () => LoginRoute,
} as any)
const AuthedTenantsIdRoute = AuthedTenantsIdRouteImport.update({
  id: '/tenants/$id',
  path: '/tenants/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTenantsIdWorkflowsRoute =
  AuthedTenantsIdWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => AuthedTenantsIdRoute,
  } as any)
const AuthedTenantsIdToolsRoute = AuthedTenantsIdToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthedTenantsIdRoute,
} as any)
const AuthedTenantsIdThreadsRoute = AuthedTenantsIdThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => AuthedTenantsIdRoute,
} as any)
const AuthedTenantsIdSetupRoute = AuthedTenantsIdSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthedTenantsIdRoute,
} as any)
const AuthedTenantsIdRunsRoute = AuthedTenantsIdRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AuthedTenantsIdRoute,
} as any)
const AuthedTenantsIdMetricsRoute = AuthedTenantsIdMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AuthedTenantsIdRoute,
} as any)
const AuthedTenantsIdCorpusRoute = AuthedTenantsIdCorpusRouteImport.update({
  id: '/corpus',
  path: '/corpus',
  getParentRoute: () => AuthedTenantsIdRoute,
} as any)
const AuthedTenantsIdConnectorsRoute =
  AuthedTenantsIdConnectorsRouteImport.update({
    id: '/connectors',
    path: '/connectors',
    getParentRoute: () => AuthedTenantsIdRoute,
  } as any)
const AuthedTenantsIdAuditRoute = AuthedTenantsIdAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedTenantsIdRoute,
} as any)
const AuthedTenantsIdAgentsRoute = AuthedTenantsIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthedTenantsIdRoute,
} as any)
const AuthedTenantsIdConnectorsCidConsentRoute =
  AuthedTenantsIdConnectorsCidConsentRouteImport.update({
    id: '/$cid/consent',
    path: '/$cid/consent',
    getParentRoute: () => AuthedTenantsIdConnectorsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/me': typeof AuthedMeRoute
  '/tenants/$id': typeof AuthedTenantsIdRouteWithChildren
  '/login/$provider/callback': typeof LoginProviderCallbackRoute
  '/tenants/$id/agents': typeof AuthedTenantsIdAgentsRoute
  '/tenants/$id/audit': typeof AuthedTenantsIdAuditRoute
  '/tenants/$id/connectors': typeof AuthedTenantsIdConnectorsRouteWithChildren
  '/tenants/$id/corpus': typeof AuthedTenantsIdCorpusRoute
  '/tenants/$id/metrics': typeof AuthedTenantsIdMetricsRoute
  '/tenants/$id/runs': typeof AuthedTenantsIdRunsRoute
  '/tenants/$id/setup': typeof AuthedTenantsIdSetupRoute
  '/tenants/$id/threads': typeof AuthedTenantsIdThreadsRoute
  '/tenants/$id/tools': typeof AuthedTenantsIdToolsRoute
  '/tenants/$id/workflows': typeof AuthedTenantsIdWorkflowsRoute
  '/tenants/$id/connectors/$cid/consent': typeof AuthedTenantsIdConnectorsCidConsentRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/me': typeof AuthedMeRoute
  '/tenants/$id': typeof AuthedTenantsIdRouteWithChildren
  '/login/$provider/callback': typeof LoginProviderCallbackRoute
  '/tenants/$id/agents': typeof AuthedTenantsIdAgentsRoute
  '/tenants/$id/audit': typeof AuthedTenantsIdAuditRoute
  '/tenants/$id/connectors': typeof AuthedTenantsIdConnectorsRouteWithChildren
  '/tenants/$id/corpus': typeof AuthedTenantsIdCorpusRoute
  '/tenants/$id/metrics': typeof AuthedTenantsIdMetricsRoute
  '/tenants/$id/runs': typeof AuthedTenantsIdRunsRoute
  '/tenants/$id/setup': typeof AuthedTenantsIdSetupRoute
  '/tenants/$id/threads': typeof AuthedTenantsIdThreadsRoute
  '/tenants/$id/tools': typeof AuthedTenantsIdToolsRoute
  '/tenants/$id/workflows': typeof AuthedTenantsIdWorkflowsRoute
  '/tenants/$id/connectors/$cid/consent': typeof AuthedTenantsIdConnectorsCidConsentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/_authed/me': typeof AuthedMeRoute
  '/_authed/tenants/$id': typeof AuthedTenantsIdRouteWithChildren
  '/login/$provider/callback': typeof LoginProviderCallbackRoute
  '/_authed/tenants/$id/agents': typeof AuthedTenantsIdAgentsRoute
  '/_authed/tenants/$id/audit': typeof AuthedTenantsIdAuditRoute
  '/_authed/tenants/$id/connectors': typeof AuthedTenantsIdConnectorsRouteWithChildren
  '/_authed/tenants/$id/corpus': typeof AuthedTenantsIdCorpusRoute
  '/_authed/tenants/$id/metrics': typeof AuthedTenantsIdMetricsRoute
  '/_authed/tenants/$id/runs': typeof AuthedTenantsIdRunsRoute
  '/_authed/tenants/$id/setup': typeof AuthedTenantsIdSetupRoute
  '/_authed/tenants/$id/threads': typeof AuthedTenantsIdThreadsRoute
  '/_authed/tenants/$id/tools': typeof AuthedTenantsIdToolsRoute
  '/_authed/tenants/$id/workflows': typeof AuthedTenantsIdWorkflowsRoute
  '/_authed/tenants/$id/connectors/$cid/consent': typeof AuthedTenantsIdConnectorsCidConsentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/me'
    | '/tenants/$id'
    | '/login/$provider/callback'
    | '/tenants/$id/agents'
    | '/tenants/$id/audit'
    | '/tenants/$id/connectors'
    | '/tenants/$id/corpus'
    | '/tenants/$id/metrics'
    | '/tenants/$id/runs'
    | '/tenants/$id/setup'
    | '/tenants/$id/threads'
    | '/tenants/$id/tools'
    | '/tenants/$id/workflows'
    | '/tenants/$id/connectors/$cid/consent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/me'
    | '/tenants/$id'
    | '/login/$provider/callback'
    | '/tenants/$id/agents'
    | '/tenants/$id/audit'
    | '/tenants/$id/connectors'
    | '/tenants/$id/corpus'
    | '/tenants/$id/metrics'
    | '/tenants/$id/runs'
    | '/tenants/$id/setup'
    | '/tenants/$id/threads'
    | '/tenants/$id/tools'
    | '/tenants/$id/workflows'
    | '/tenants/$id/connectors/$cid/consent'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/me'
    | '/_authed/tenants/$id'
    | '/login/$provider/callback'
    | '/_authed/tenants/$id/agents'
    | '/_authed/tenants/$id/audit'
    | '/_authed/tenants/$id/connectors'
    | '/_authed/tenants/$id/corpus'
    | '/_authed/tenants/$id/metrics'
    | '/_authed/tenants/$id/runs'
    | '/_authed/tenants/$id/setup'
    | '/_authed/tenants/$id/threads'
    | '/_authed/tenants/$id/tools'
    | '/_authed/tenants/$id/workflows'
    | '/_authed/tenants/$id/connectors/$cid/consent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/me': {
      id: '/_authed/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthedMeRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/login/$provider/callback': {
      id: '/login/$provider/callback'
      path: '/$provider/callback'
      fullPath: '/login/$provider/callback'
      preLoaderRoute: typeof LoginProviderCallbackRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_authed/tenants/$id': {
      id: '/_authed/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/tenants/$id'
      preLoaderRoute: typeof AuthedTenantsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tenants/$id/workflows': {
      id: '/_authed/tenants/$id/workflows'
      path: '/workflows'
      fullPath: '/tenants/$id/workflows'
      preLoaderRoute: typeof AuthedTenantsIdWorkflowsRouteImport
      parentRoute: typeof AuthedTenantsIdRoute
    }
    '/_authed/tenants/$id/tools': {
      id: '/_authed/tenants/$id/tools'
      path: '/tools'
      fullPath: '/tenants/$id/tools'
      preLoaderRoute: typeof AuthedTenantsIdToolsRouteImport
      parentRoute: typeof AuthedTenantsIdRoute
    }
    '/_authed/tenants/$id/threads': {
      id: '/_authed/tenants/$id/threads'
      path: '/threads'
      fullPath: '/tenants/$id/threads'
      preLoaderRoute: typeof AuthedTenantsIdThreadsRouteImport
      parentRoute: typeof AuthedTenantsIdRoute
    }
    '/_authed/tenants/$id/setup': {
      id: '/_authed/tenants/$id/setup'
      path: '/setup'
      fullPath: '/tenants/$id/setup'
      preLoaderRoute: typeof AuthedTenantsIdSetupRouteImport
      parentRoute: typeof AuthedTenantsIdRoute
    }
    '/_authed/tenants/$id/runs': {
      id: '/_authed/tenants/$id/runs'
      path: '/runs'
      fullPath: '/tenants/$id/runs'
      preLoaderRoute: typeof AuthedTenantsIdRunsRouteImport
      parentRoute: typeof AuthedTenantsIdRoute
    }
    '/_authed/tenants/$id/metrics': {
      id: '/_authed/tenants/$id/metrics'
      path: '/metrics'
      fullPath: '/tenants/$id/metrics'
      preLoaderRoute: typeof AuthedTenantsIdMetricsRouteImport
      parentRoute: typeof AuthedTenantsIdRoute
    }
    '/_authed/tenants/$id/corpus': {
      id: '/_authed/tenants/$id/corpus'
      path: '/corpus'
      fullPath: '/tenants/$id/corpus'
      preLoaderRoute: typeof AuthedTenantsIdCorpusRouteImport
      parentRoute: typeof AuthedTenantsIdRoute
    }
    '/_authed/tenants/$id/connectors': {
      id: '/_authed/tenants/$id/connectors'
      path: '/connectors'
      fullPath: '/tenants/$id/connectors'
      preLoaderRoute: typeof AuthedTenantsIdConnectorsRouteImport
      parentRoute: typeof AuthedTenantsIdRoute
    }
    '/_authed/tenants/$id/audit': {
      id: '/_authed/tenants/$id/audit'
      path: '/audit'
      fullPath: '/tenants/$id/audit'
      preLoaderRoute: typeof AuthedTenantsIdAuditRouteImport
      parentRoute: typeof AuthedTenantsIdRoute
    }
    '/_authed/tenants/$id/agents': {
      id: '/_authed/tenants/$id/agents'
      path: '/agents'
      fullPath: '/tenants/$id/agents'
      preLoaderRoute: typeof AuthedTenantsIdAgentsRouteImport
      parentRoute: typeof AuthedTenantsIdRoute
    }
    '/_authed/tenants/$id/connectors/$cid/consent': {
      id: '/_authed/tenants/$id/connectors/$cid/consent'
      path: '/$cid/consent'
      fullPath: '/tenants/$id/connectors/$cid/consent'
      preLoaderRoute: typeof AuthedTenantsIdConnectorsCidConsentRouteImport
      parentRoute: typeof AuthedTenantsIdConnectorsRoute
    }
  }
}

interface AuthedTenantsIdConnectorsRouteChildren {
  AuthedTenantsIdConnectorsCidConsentRoute: typeof AuthedTenantsIdConnectorsCidConsentRoute
}

const AuthedTenantsIdConnectorsRouteChildren: AuthedTenantsIdConnectorsRouteChildren =
  {
    AuthedTenantsIdConnectorsCidConsentRoute:
      AuthedTenantsIdConnectorsCidConsentRoute,
  }

const AuthedTenantsIdConnectorsRouteWithChildren =
  AuthedTenantsIdConnectorsRoute._addFileChildren(
    AuthedTenantsIdConnectorsRouteChildren,
  )

interface AuthedTenantsIdRouteChildren {
  AuthedTenantsIdAgentsRoute: typeof AuthedTenantsIdAgentsRoute
  AuthedTenantsIdAuditRoute: typeof AuthedTenantsIdAuditRoute
  AuthedTenantsIdConnectorsRoute: typeof AuthedTenantsIdConnectorsRouteWithChildren
  AuthedTenantsIdCorpusRoute: typeof AuthedTenantsIdCorpusRoute
  AuthedTenantsIdMetricsRoute: typeof AuthedTenantsIdMetricsRoute
  AuthedTenantsIdRunsRoute: typeof AuthedTenantsIdRunsRoute
  AuthedTenantsIdSetupRoute: typeof AuthedTenantsIdSetupRoute
  AuthedTenantsIdThreadsRoute: typeof AuthedTenantsIdThreadsRoute
  AuthedTenantsIdToolsRoute: typeof AuthedTenantsIdToolsRoute
  AuthedTenantsIdWorkflowsRoute: typeof AuthedTenantsIdWorkflowsRoute
}

const AuthedTenantsIdRouteChildren: AuthedTenantsIdRouteChildren = {
  AuthedTenantsIdAgentsRoute: AuthedTenantsIdAgentsRoute,
  AuthedTenantsIdAuditRoute: AuthedTenantsIdAuditRoute,
  AuthedTenantsIdConnectorsRoute: AuthedTenantsIdConnectorsRouteWithChildren,
  AuthedTenantsIdCorpusRoute: AuthedTenantsIdCorpusRoute,
  AuthedTenantsIdMetricsRoute: AuthedTenantsIdMetricsRoute,
  AuthedTenantsIdRunsRoute: AuthedTenantsIdRunsRoute,
  AuthedTenantsIdSetupRoute: AuthedTenantsIdSetupRoute,
  AuthedTenantsIdThreadsRoute: AuthedTenantsIdThreadsRoute,
  AuthedTenantsIdToolsRoute: AuthedTenantsIdToolsRoute,
  AuthedTenantsIdWorkflowsRoute: AuthedTenantsIdWorkflowsRoute,
}

const AuthedTenantsIdRouteWithChildren = AuthedTenantsIdRoute._addFileChildren(
  AuthedTenantsIdRouteChildren,
)

interface AuthedRouteChildren {
  AuthedMeRoute: typeof AuthedMeRoute
  AuthedTenantsIdRoute: typeof AuthedTenantsIdRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedMeRoute: AuthedMeRoute,
  AuthedTenantsIdRoute: AuthedTenantsIdRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface LoginRouteChildren {
  LoginProviderCallbackRoute: typeof LoginProviderCallbackRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginProviderCallbackRoute: LoginProviderCallbackRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
