export const COMMON_IANA_TIMEZONES: ReadonlyArray<{ value: string; label: string }> = [
  { value: 'Asia/Ho_Chi_Minh', label: 'Ho Chi Minh City (UTC+7)' },
  { value: 'Asia/Bangkok', label: 'Bangkok (UTC+7)' },
  { value: 'Asia/Singapore', label: 'Singapore (UTC+8)' },
  { value: 'Asia/Hong_Kong', label: 'Hong Kong (UTC+8)' },
  { value: 'Asia/Tokyo', label: 'Tokyo (UTC+9)' },
  { value: 'Asia/Seoul', label: 'Seoul (UTC+9)' },
  { value: 'Asia/Kolkata', label: 'Mumbai/Kolkata (UTC+5:30)' },
  { value: 'Asia/Dubai', label: 'Dubai (UTC+4)' },
  { value: 'Europe/London', label: 'London (UTC+0 / DST)' },
  { value: 'Europe/Paris', label: 'Paris (UTC+1 / DST)' },
  { value: 'Europe/Berlin', label: 'Berlin (UTC+1 / DST)' },
  { value: 'Europe/Moscow', label: 'Moscow (UTC+3)' },
  { value: 'America/New_York', label: 'New York (UTC-5 / DST)' },
  { value: 'America/Chicago', label: 'Chicago (UTC-6 / DST)' },
  { value: 'America/Denver', label: 'Denver (UTC-7 / DST)' },
  { value: 'America/Los_Angeles', label: 'Los Angeles (UTC-8 / DST)' },
  { value: 'America/Sao_Paulo', label: 'São Paulo (UTC-3)' },
  { value: 'Australia/Sydney', label: 'Sydney (UTC+10 / DST)' },
  { value: 'Pacific/Auckland', label: 'Auckland (UTC+12 / DST)' },
  { value: 'UTC', label: 'UTC' },
]
